import type { DocumentElement } from "../gold-corpus-v2.types.js";
import { DocumentSection } from "../gold-corpus-v2.types.js";
import type { CaseSeedData } from "../gold-corpus-v2.types.js";
import type { TributarioScenarioConfig } from "./tributario-scenario.types.js";

function h(s: string): number {
  let n = 2166136261;
  for (let i = 0; i < s.length; i++) n = Math.imul(n ^ s.charCodeAt(i), 16777619);
  return n >>> 0;
}

function dn(seed: CaseSeedData, salt: string, min: number, range: number): number {
  return min + (h(seed.cpf + salt) % range);
}

function fmt(cents: number): string {
  return `R$ ${(cents / 100).toFixed(2).replace(".", ",")}`;
}

function cnpj(seed: CaseSeedData): string {
  return `${String(dn(seed, "c1t", 10, 89)).padStart(2, "0")}.${String(dn(seed, "c2t", 100, 899)).padStart(3, "0")}.${String(dn(seed, "c3t", 100, 899)).padStart(3, "0")}/0001-${String(dn(seed, "c4t", 10, 89)).padStart(2, "0")}`;
}

function empresa(seed: CaseSeedData): string {
  const nomes = ["Alfa Empreendimentos", "Beta Participações", "Gama Comércio", "Delta Indústria", "Ômega Serviços"];
  return `${nomes[h(seed.cpf + "empt") % nomes.length]} Ltda.`;
}

// ─── TRIB-001: EMBARGOS_EXECUCAO_FISCAL (GOOD) ────────────────────────────────
function buildEmbargosExecucaoFiscal(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const debitoCents = dn(seed, "deb1", 5000000, 40000000);
  const cda = `${dn(seed, "cda1a", 10, 89)}.${dn(seed, "cda1b", 1000, 8999)}.${dn(seed, "cda1c", 1000, 8999)}-${dn(seed, "cda1d", 1, 9)}`;
  const tributo = ["IRPJ", "PIS/COFINS", "CSLL", "IRPJ e CSLL"][h(seed.cpf + "trib1") % 4];
  const anoBase = 2018 + (h(seed.cpf + "ano1") % 5);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${emp.toUpperCase()}, CNPJ n.º ${cn}, vem opor\n\nEMBARGOS À EXECUÇÃO FISCAL\n\nem face da Fazenda Pública Federal\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [emp, cn] },
    { id: "certidao_divida_ativa", section: DocumentSection.DOS_FATOS, fullContent: `A CDA n.º ${cda} consubstancia débito de ${tributo} do ano-base ${anoBase}, no valor de ${fmt(debitoCents)}, inscrito em Dívida Ativa da União nos termos do art. 201 do CTN. O embargante impugna a exigibilidade, eis que o crédito tributário está prescrito (CTN art. 174) e/ou a CDA não preenche os requisitos do art. 202 do CTN.`, lightContent: `A CDA em cobrança indica débito de ${tributo}, cuja exigibilidade é impugnada pelos embargos.`, omittedContent: `[CDA não identificada com número, tributo, ano-base e valor — fundamento dos embargos não especificado]`, omissionDescription: "ausência de identificação da CDA com número, tributo, ano-base e valor do débito objeto dos embargos", correctPresenceKeywords: [cda, tributo, String(anoBase)] },
    { id: "fatos_embargos", section: DocumentSection.DOS_FATOS, fullContent: `A cobrança refere-se a lançamento de ${tributo} relativo ao ano-base ${anoBase}. Ocorre que: (a) o crédito tributário foi constituído em ${seed.baseDate} e (b) a execução foi proposta em ${seed.derDate}, ultrapassando o prazo quinquenal do art. 174 do CTN, contado da constituição definitiva. O tributo foi quitado mediante DARF n.º ${dn(seed, "darf1", 10000000, 89999999)}, porém desconsiderado pelo Fisco.`, lightContent: `O embargante contesta a exigibilidade do crédito cobrado pela Fazenda.`, omittedContent: `[fatos que fundamentam os embargos — data de constituição do crédito, pagamento e prazo prescricional — não identificados]`, omissionDescription: "ausência de identificação dos fatos que fundamentam os embargos com datas, valores e argumento prescricional ou de pagamento", correctPresenceKeywords: [seed.baseDate, seed.derDate, "art. 174"] },
    { id: "excepcao_preexecutividade", section: DocumentSection.DO_DIREITO, fullContent: `Os embargos à execução fiscal (Lei 6.830/1980 art. 16) são o meio adequado para impugnar a CDA. A prescrição tributária ocorre em 5 anos (CTN art. 174), contados da constituição definitiva do crédito (Súm. 622 STJ). O pagamento via DARF extingue o crédito (CTN art. 156 I). Requer-se também, no mérito, a revisão das multas de ofício (CTN art. 112), que não podem ultrapassar 75% do tributo principal.`, lightContent: `Os embargos à execução fiscal contestam a exigibilidade do crédito fiscal.`, omittedContent: `[fundamento legal dos embargos, prescrição e critérios de extinção do crédito não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal dos embargos, do prazo prescricional e dos critérios de extinção do crédito tributário", correctPresenceKeywords: ["CTN art. 174", "Súm. 622", "Lei 6.830"] },
    { id: "pedidos_embargos", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) reconhecimento da prescrição e extinção do crédito tributário (CTN arts. 156 V e 174); (b) subsidiariamente, exclusão das multas excessivas; (c) efeito suspensivo (LEF art. 16 §1.º); (d) condenação da Fazenda em custas e honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer o reconhecimento da prescrição ou extinção do crédito tributário.`, omittedContent: `[pedido de embargos sem especificação dos fundamentos extintivos e dos efeitos pleiteados]`, omissionDescription: "pedido de embargos à execução fiscal sem especificação dos fundamentos extintivos e dos efeitos processuais pleiteados", correctPresenceKeywords: ["CTN art. 156", "LEF art. 16", "efeito suspensivo"] },
  ];
}

// ─── TRIB-002: COMPENSACAO_CREDITO_TRIBUTARIO (MODERATE) ──────────────────────
function buildCompensacaoCredito(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const creditoCents = dn(seed, "cred2", 2000000, 15000000);
  const tributoCredor = ["PIS", "COFINS", "CSLL", "IPI"][h(seed.cpf + "tc2") % 4];
  const tributoDevedor = ["IRPJ", "CSLL", "PIS", "COFINS"][h(seed.cpf + "td2") % 4];
  const periodos = dn(seed, "per2", 12, 36);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${emp.toUpperCase()}, CNPJ n.º ${cn}, vem propor\n\nAÇÃO DE COMPENSAÇÃO DE CRÉDITO TRIBUTÁRIO\n\nem face da União Federal\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [emp, cn] },
    { id: "fatos_credito_tributario", section: DocumentSection.DOS_FATOS, fullContent: `A autora apurou crédito de ${tributoCredor} no valor de ${fmt(creditoCents)}, relativo a ${periodos} competências mensais de ${seed.baseDate} a ${seed.derDate}, decorrente de recolhimento a maior em razão de exclusão indevida de receitas da base de cálculo. O crédito foi reconhecido pela própria RFB em processo administrativo n.º ${dn(seed, "proc2", 10000, 89999)}.`, lightContent: `A autora possui crédito tributário de ${tributoCredor} a ser compensado com débitos de ${tributoDevedor}.`, omittedContent: `[origem, período e valor do crédito tributário não identificados — compensação sem fundamento fático]`, omissionDescription: "ausência de identificação da origem, período e valor do crédito tributário a ser compensado", correctPresenceKeywords: [tributoCredor, fmt(creditoCents), seed.baseDate] },
    { id: "demonstrativo_credito", section: DocumentSection.DOS_FATOS, fullContent: `Demonstrativo do crédito (${tributoCredor}) — ${periodos} competências:\n• Base de cálculo mensal média: ${fmt(Math.round(creditoCents / periodos / 1.05))}\n• Alíquota aplicada: ${[1.65, 7.60, 0.65, 3.00][h(seed.cpf + "aliq2") % 4].toFixed(2)}%\n• Crédito mensal médio: ${fmt(Math.round(creditoCents / periodos))}\n• Total apurado: ${fmt(creditoCents)}\n• Saldo disponível para compensação com ${tributoDevedor}: ${fmt(creditoCents)}`, lightContent: `O demonstrativo analítico do crédito de ${tributoCredor} será apresentado no processo.`, omittedContent: `[demonstrativo analítico do crédito tributário por competência não apresentado na petição]`, omissionDescription: "ausência de demonstrativo analítico do crédito tributário por competência com base de cálculo, alíquota e valor mensal", correctPresenceKeywords: [fmt(creditoCents), tributoCredor, "competências"] },
    { id: "direito_compensacao", section: DocumentSection.DO_DIREITO, fullContent: `O art. 170 do CTN e o art. 74 da Lei 9.430/1996 (com redação da Lei 10.637/2002) autorizam a compensação de créditos tributários de tributos administrados pela RFB. A Súmula 461 do STJ pacificou que é devida a compensação. O crédito, devidamente homologado, pode ser utilizado para quitar ${tributoDevedor} (Instrução Normativa RFB n.º 2.055/2021).`, lightContent: `A compensação tributária entre ${tributoCredor} e ${tributoDevedor} é autorizada pela legislação federal.`, omittedContent: `[fundamento legal da compensação tributária e normas aplicáveis não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal da compensação tributária com identificação das normas aplicáveis", correctPresenceKeywords: ["CTN art. 170", "Lei 9.430", "Súmula 461"] },
    { id: "pedidos_compensacao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) reconhecimento do crédito de ${tributoCredor} no valor de ${fmt(creditoCents)}; (b) autorização para compensação com débitos de ${tributoDevedor}; (c) inibição de execução fiscal durante a compensação; (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer o reconhecimento do crédito e a autorização para compensação tributária.`, omittedContent: `[pedido de compensação sem especificação do crédito, do débito e dos fundamentos legais]`, omissionDescription: "pedido de compensação tributária sem especificação do crédito, do tributo a compensar e dos fundamentos legais", correctPresenceKeywords: [fmt(creditoCents), tributoCredor, tributoDevedor] },
  ];
}

// ─── TRIB-003: EXCLUSAO_SIMPLES_NACIONAL (SEVERE) ─────────────────────────────
function buildExclusaoSimplesNacional(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const receitaCents = dn(seed, "rec3", 50000000, 200000000);
  const multaCents = dn(seed, "mul3", 1000000, 5000000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${emp.toUpperCase()}, CNPJ n.º ${cn}, apresenta\n\nRECURSO INOMINADO\n\nem face de acórdão que manteve a exclusão do Simples Nacional\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [emp, cn] },
    { id: "decisao_recorrida_simples", section: DocumentSection.DOS_FATOS, fullContent: `O acórdão recorrido manteve a exclusão do Simples Nacional (LC 123/2006 art. 29) da recorrente, por suposto excesso de receita bruta. A receita apurada pelo Fisco foi ${fmt(receitaCents)}, superior ao limite anual de ${fmt(48000000)} (LC 123/2006 art. 3.º IV). O recorrente contesta os critérios de apuração e a proporcionalidade da multa de ${fmt(multaCents)}.`, lightContent: `O acórdão manteve a exclusão do Simples Nacional por excesso de receita bruta.`, omittedContent: `[decisão recorrida e valores de receita apurados pelo Fisco não identificados com precisão]`, omissionDescription: "ausência de identificação precisa da decisão recorrida e dos valores de receita que fundamentam a exclusão do Simples Nacional", correctPresenceKeywords: [fmt(receitaCents), "LC 123", "exclusão"] },
    { id: "fatos_simples", section: DocumentSection.DO_DIREITO, fullContent: `A receita bruta de ${fmt(receitaCents)} foi apurada pelo Fisco sem excluir: (a) receitas de exportação (LC 123/2006 art. 3.º §1.º); (b) transferências entre filiais; (c) devoluções. A receita ajustada, deduzidos ${fmt(Math.round(receitaCents * 0.18))} de itens não tributáveis, é de ${fmt(Math.round(receitaCents * 0.82))}, dentro do limite legal. O recorrente juntou planilha analítica demonstrando o ajuste.`, lightContent: `A receita bruta apurada pelo Fisco incluiu parcelas indevidamente, superando artificialmente o limite do Simples.`, omittedContent: `[demonstração dos ajustes na receita bruta que reduziriam o valor abaixo do limite do Simples Nacional não realizada]`, omissionDescription: "ausência de demonstração dos ajustes na receita bruta (exclusões legais) que reduziriam o valor abaixo do limite do Simples Nacional", correctPresenceKeywords: [fmt(receitaCents), "LC 123", "receita bruta"] },
    { id: "notificacao_simples", section: DocumentSection.DOS_FATOS, fullContent: `O CGSN notificou a empresa em ${seed.baseDate} (Comunicado n.º ${dn(seed, "com3", 1000, 8999)}/CGSN) concedendo prazo de 30 dias para regularização ou impugnação, nos termos do art. 30 da LC 123/2006. A empresa protocolou impugnação tempestiva em ${seed.derDate}.`, lightContent: `A empresa foi notificada sobre a exclusão e protocolou impugnação administrativa.`, omittedContent: "", omissionDescription: "ausência de comprovação de que a notificação prévia de exclusão do Simples foi recebida e de que houve oportunidade de impugnação administrativa", absentContent: null, correctPresenceKeywords: ["notificou", seed.baseDate, "LC 123"] },
    { id: "pedido_recursal_simples", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer o provimento do recurso para: (a) anular a exclusão do Simples Nacional; (b) reconhecer os ajustes na receita bruta; (c) cancelar a multa de ${fmt(multaCents)}; (d) honorários recursais.`, lightContent: `Requer a anulação da exclusão do Simples Nacional e o cancelamento das multas.`, omittedContent: `[pedido recursal sem identificação dos fundamentos para anulação e valor da multa]`, omissionDescription: "pedido recursal sem identificação dos fundamentos para anulação da exclusão e do valor da multa a ser cancelada", correctPresenceKeywords: [fmt(multaCents), "Simples Nacional", "anular"] },
  ];
}

// ─── TRIB-004: RESTITUICAO_TRIBUTO_INDEVIDO (MODERATE) ────────────────────────
function buildRestituicaoTributoIndevido(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const tributo = ["IRPJ", "COFINS", "PIS", "CSLL"][h(seed.cpf + "trib4") % 4];
  const valorCents = dn(seed, "val4", 1000000, 8000000);
  const anoBase = 2019 + (h(seed.cpf + "ano4") % 4);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${emp.toUpperCase()}, CNPJ n.º ${cn}, vem propor\n\nAÇÃO DE RESTITUIÇÃO DE TRIBUTO PAGO INDEVIDAMENTE\n\nem face da União Federal\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [emp, cn] },
    { id: "fatos_pagamento_indevido", section: DocumentSection.DOS_FATOS, fullContent: `A autora recolheu ${tributo} no valor de ${fmt(valorCents)} no exercício ${anoBase}, sobre base de cálculo que incluiu receitas de exportação indevidamente — imunes por força do art. 149 §2.º I da CF/88. O pagamento foi efetuado via DARF n.º ${dn(seed, "darf4", 10000000, 89999999)} em ${seed.baseDate}. O pedido de restituição administrativo (PA n.º ${dn(seed, "pa4", 100000, 899999)}) foi indeferido em ${seed.derDate}.`, lightContent: `A autora realizou recolhimento indevido de ${tributo} sobre base de cálculo que incluiu receitas imunes.`, omittedContent: `[data, valor e número do DARF do pagamento indevido não identificados — ausência de prova do pagamento]`, omissionDescription: "ausência de identificação da data, valor e número do DARF do pagamento indevido de " + tributo, correctPresenceKeywords: [seed.baseDate, fmt(valorCents), tributo] },
    { id: "comprovante_pagamento", section: DocumentSection.DAS_PROVAS, fullContent: `Comprova-se o pagamento indevido mediante: (a) DARF n.º ${dn(seed, "darf4", 10000000, 89999999)} de ${seed.baseDate} no valor de ${fmt(valorCents)}; (b) SPED Contábil do exercício ${anoBase} demonstrando as receitas de exportação indevidamente tributadas; (c) ECF — Escrituração Contábil Fiscal do exercício ${anoBase}; (d) indeferimento administrativo (PA n.º ${dn(seed, "pa4", 100000, 899999)}).`, lightContent: `A prova do pagamento indevido será produzida documentalmente no curso do processo.`, omittedContent: `[comprovante do pagamento indevido (DARF, SPED ou ECF) não juntado à petição inicial]`, omissionDescription: "ausência de juntada de comprovante do pagamento indevido (DARF, SPED ou ECF) para embasar o pedido de restituição", correctPresenceKeywords: [fmt(valorCents), "SPED", "ECF"] },
    { id: "direito_restituicao", section: DocumentSection.DO_DIREITO, fullContent: `O art. 165 do CTN assegura o direito à restituição de tributo pago indevidamente. As receitas de exportação são imunes à contribuição do PIS/COFINS e ao IRPJ sobre tais resultados (CF/88 art. 149 §2.º I; RE 564.413/SC — STF). A restituição é acrescida de SELIC (Lei 9.250/1995 art. 39 §4.º).`, lightContent: `A legislação tributária assegura o direito à restituição do tributo pago indevidamente.`, omittedContent: `[fundamento legal do direito à restituição e imunidade aplicável não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal do direito à restituição e da imunidade constitucional aplicável", correctPresenceKeywords: ["CTN art. 165", "CF/88 art. 149", "SELIC"] },
    { id: "pedidos_restituicao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) restituição de ${fmt(valorCents)} a título de ${tributo} pago indevidamente, acrescido de SELIC; (b) compensação com débitos futuros de qualquer espécie administrada pela RFB; (c) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a restituição do tributo pago indevidamente acrescido de juros.`, omittedContent: `[pedido de restituição sem valor especificado e sem indicação do tributo e da imunidade aplicável]`, omissionDescription: "pedido de restituição de tributo indevido sem especificação do valor, do tributo e do fundamento da imunidade", correctPresenceKeywords: [fmt(valorCents), tributo, "SELIC"] },
  ];
}

// ─── TRIB-005: PRESCRICAO_TRIBUTARIA (GOOD) ───────────────────────────────────
function buildPrescricaoTributaria(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const debitoCents = dn(seed, "deb5", 3000000, 20000000);
  const tributo = ["IRPJ", "CSLL", "PIS/COFINS", "IPI"][h(seed.cpf + "trib5") % 4];
  const anoConstituicao = 2013 + (h(seed.cpf + "ano5") % 5);
  const anoExecucao = anoConstituicao + 6;
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${emp.toUpperCase()}, CNPJ n.º ${cn}, apresenta\n\nRECURSO ESPECIAL\n\nem face de acórdão que afastou a prescrição tributária\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [emp, cn] },
    { id: "decisao_recorrida_prescricao", section: DocumentSection.DOS_FATOS, fullContent: `O acórdão recorrido afastou a prescrição do crédito de ${tributo} no valor de ${fmt(debitoCents)}, constituído em ${anoConstituicao}, entendendo que a execução fiscal ajuizada em ${anoExecucao} seria tempestiva por aplicação de causa suspensiva de parcelamento. O recorrente demonstra que o parcelamento foi revogado antes do transcurso do prazo e não suspendeu a prescrição (CTN art. 174 parágrafo único II).`, lightContent: `O acórdão afastou a prescrição do crédito tributário por entender válida causa suspensiva.`, omittedContent: `[decisão recorrida e ano de constituição do crédito não identificados com precisão]`, omissionDescription: "ausência de identificação precisa da decisão recorrida e dos dados do crédito tributário que fundamentam a arguição de prescrição", correctPresenceKeywords: [String(anoConstituicao), String(anoExecucao), fmt(debitoCents)] },
    { id: "fatos_prescricao", section: DocumentSection.DO_DIREITO, fullContent: `O crédito de ${tributo} foi definitivamente constituído em ${seed.baseDate} (${anoConstituicao}). O parcelamento eventualmente celebrado foi revogado em ${seed.derDate}, antes de quitada a 1.ª parcela, não produzindo efeito suspensivo (CTN art. 174 parágrafo único II; AgRg no REsp 1.534.584/PR). A execução fiscal foi ajuizada apenas em ${anoExecucao}, quando já transcorridos os 5 anos de prescrição (CTN art. 174 caput).`, lightContent: `O prazo prescricional de 5 anos transcorreu sem que houvesse causa suspensiva eficaz.`, omittedContent: `[datas de constituição do crédito, revogação do parcelamento e ajuizamento da execução não especificadas]`, omissionDescription: "ausência de especificação das datas de constituição do crédito, revogação do parcelamento e ajuizamento da execução para demonstrar a prescrição", correctPresenceKeywords: [String(anoConstituicao), String(anoExecucao), "CTN art. 174"] },
    { id: "calculo_prescricao", section: DocumentSection.DOS_FATOS, fullContent: `Linha do tempo: Constituição definitiva: ${seed.baseDate} (${anoConstituicao}) → Parcelamento revogado: ${seed.derDate} (sem efeito suspensivo) → Início do prazo prescricional: ${seed.baseDate} → Prescrição consumada em: ${anoConstituicao + 5} → Ajuizamento da execução: ${anoExecucao} (após a prescrição). O crédito estava prescrito quando da propositura da execução.`, lightContent: `O prazo prescricional de 5 anos foi contado da constituição definitiva sem interrupção eficaz.`, omittedContent: `[linha do tempo da prescrição com datas de constituição e ajuizamento não demonstrada]`, omissionDescription: "ausência de linha do tempo demonstrando as datas de constituição do crédito, eventual suspensão e ajuizamento da execução fiscal", correctPresenceKeywords: [String(anoConstituicao + 5), String(anoExecucao), "prescrição"] },
    { id: "pedido_recursal_prescricao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer o provimento do recurso especial para: (a) reconhecer a prescrição do crédito de ${tributo} no valor de ${fmt(debitoCents)} (CTN art. 174); (b) extinguir a execução fiscal; (c) condenar a Fazenda em honorários de sucumbência.`, lightContent: `Requer o reconhecimento da prescrição e a extinção da execução fiscal.`, omittedContent: `[pedido de reconhecimento da prescrição sem identificação do tributo, valor e prazo transcorrido]`, omissionDescription: "pedido de reconhecimento de prescrição sem especificação do tributo, do valor do crédito e da demonstração do prazo transcorrido", correctPresenceKeywords: [fmt(debitoCents), "CTN art. 174", "extinção"] },
  ];
}

// ─── TRIB-006: ANULATORIA_AUTO_INFRACAO (MODERATE) ───────────────────────────
function buildAnulatoriaAutoInfracao(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const multaCents = dn(seed, "mul6", 3000000, 20000000);
  const tributo = ["IRPJ", "COFINS", "PIS", "IPI"][h(seed.cpf + "trib6") % 4];
  const numAi = `${dn(seed, "ai6a", 1000, 8999)}-${dn(seed, "ai6b", 10, 99)}`;
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${emp.toUpperCase()}, CNPJ n.º ${cn}, vem propor\n\nAÇÃO ANULATÓRIA DE AUTO DE INFRAÇÃO\n\nem face da União Federal\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [emp, cn] },
    { id: "fatos_autuacao", section: DocumentSection.DOS_FATOS, fullContent: `Em ${seed.baseDate}, a Receita Federal lavrou o Auto de Infração n.º ${numAi} imputando à autora omissão de receita de ${tributo} no valor principal de ${fmt(multaCents)}, acrescido de multa de ofício de 75% e juros SELIC. A autuação decorre de presunção de omissão baseada em comparativo de CNPJ com faturamento do setor, sem exame efetivo dos livros contábeis (CTN art. 142).`, lightContent: `O Auto de Infração n.º ${numAi} imputou omissão de receita de ${tributo} sem análise dos livros contábeis.`, omittedContent: `[identificação do auto de infração, tributo autuado e fundamento da autuação não especificados]`, omissionDescription: "ausência de identificação do auto de infração, tributo autuado, valor e fundamento da autuação fiscal", correctPresenceKeywords: [numAi, tributo, fmt(multaCents)] },
    { id: "impugnacao_tecnica", section: DocumentSection.DOS_FATOS, fullContent: `A autuação é impugnável porque: (a) a presunção de omissão de receita baseada em comparativo setorial é ilidível por prova em contrário (CTN art. 149 parágrafo único; REsp 1.148.444/RS); (b) a autora apresentou os livros Diário e Razão ao fiscal (Termo de Verificação n.º ${dn(seed, "tv6", 1000, 9999)}), os quais não foram analisados; (c) a metodologia de comparativo de CNPJ é reconhecidamente imprecisa pelo CARF (Processo Administrativo n.º ${dn(seed, "pa6", 10000, 89999)}.000/${dn(seed, "pa6b", 2019, 4)}).`, lightContent: `A autuação é impugnável por vícios na metodologia fiscal e por ausência de análise dos livros contábeis.`, omittedContent: `[impugnação técnica ao método fiscal utilizado no auto de infração não realizada com dados concretos]`, omissionDescription: "ausência de impugnação técnica à metodologia fiscal utilizada no auto de infração com dados concretos dos livros contábeis e precedentes administrativos", correctPresenceKeywords: ["CTN art. 149", "CARF", "livros"] },
    { id: "direito_anulacao", section: DocumentSection.DO_DIREITO, fullContent: `O lançamento tributário deve ser lastreado em prova concreta da omissão (CTN art. 142). A presunção de omissão de receita admite prova em contrário (RE 576.161/BA — STF; Súm. CARF 25). A multa de ofício de 75% pressupõe dolo ou fraude; ausentes estes, a multa máxima é de 75% apenas para sonegação provada (CTN art. 44 I; Lei 9.430/1996 art. 44).`, lightContent: `O auto de infração é nulo por vício no lançamento e pela presunção ilidível de omissão de receita.`, omittedContent: `[direito à anulação do auto de infração, vícios do lançamento e limite das multas não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento dos vícios do lançamento tributário e dos limites legais das multas de ofício", correctPresenceKeywords: ["CTN art. 142", "Súm. CARF", "multa"] },
    { id: "pedidos_anulacao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) anulação do Auto de Infração n.º ${numAi}; (b) subsidiariamente, redução da multa de ofício para 75% do tributo principal com exclusão dos acréscimos; (c) suspensão da exigibilidade (CTN art. 151 V); (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a anulação do auto de infração e a suspensão da exigibilidade do crédito.`, omittedContent: `[pedido de anulação sem identificação do auto de infração e dos fundamentos extintivos]`, omissionDescription: "pedido de anulação de auto de infração sem identificação do número do AI e dos fundamentos legais para a anulação", correctPresenceKeywords: [numAi, "CTN art. 151", "anulação"] },
  ];
}

// ─── TRIB-007: IMUNIDADE_TRIBUTARIA (LIGHT) ───────────────────────────────────
function buildImunidadeTributaria(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const impostosCents = dn(seed, "imp7", 500000, 5000000);
  const tipoEntidade = ["entidade filantrópica (CF art. 150 VI c)", "templo de qualquer culto (CF art. 150 VI b)", "partido político (CF art. 150 VI c)", "instituição de educação sem fins lucrativos (CF art. 150 VI c)"][h(seed.cpf + "ent7") % 4];
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${emp.toUpperCase()}, CNPJ n.º ${cn}, vem propor\n\nAÇÃO DECLARATÓRIA DE IMUNIDADE TRIBUTÁRIA\n\nem face da União Federal e/ou Município\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [emp, cn] },
    { id: "fatos_imunidade", section: DocumentSection.DOS_FATOS, fullContent: `A autora é ${tipoEntidade}, devidamente registrada, e vem sofrendo cobrança indevida de ${fmt(impostosCents)} a título de IPTU, IRPJ e CSLL sobre seu patrimônio e rendas destinados integralmente às suas finalidades essenciais, em violação à imunidade constitucional do art. 150 VI c da CF/88 e do art. 14 do CTN.`, lightContent: `A autora possui imunidade tributária constitucionalmente assegurada e sofre cobranças indevidas.`, omittedContent: `[natureza jurídica da entidade, tributos cobrados e valores não identificados com precisão]`, omissionDescription: "ausência de identificação precisa da natureza jurídica da entidade imune, dos tributos cobrados e dos valores indevidos", correctPresenceKeywords: [tipoEntidade.split(" ")[0], fmt(impostosCents), "art. 150"] },
    { id: "prova_requisitos_imunidade", section: DocumentSection.DAS_PROVAS, fullContent: `A imunidade é demonstrada pelos seguintes documentos: (a) Estatuto Social com cláusula de destinação integral das rendas às finalidades essenciais; (b) certidão de inexistência de distribuição de lucros (art. 14 I CTN); (c) Balanço Patrimonial do exercício ${2023 + (h(seed.cpf + "ano7") % 2)} com comprovação da destinação dos recursos; (d) Declaração de Informações Imunes e Isentas (DIRF) atualizada.`, lightContent: `A condição de entidade imune será comprovada documentalmente no processo.`, omittedContent: `[prova documental dos requisitos da imunidade tributária (estatuto, balanço, destinação de rendas) não juntada]`, omissionDescription: "ausência de juntada dos documentos que comprovam os requisitos da imunidade tributária (estatuto, balanço, destinação das rendas às finalidades essenciais)", correctPresenceKeywords: ["Estatuto", "art. 14", "CTN"] },
    { id: "direito_imunidade", section: DocumentSection.DO_DIREITO, fullContent: `A CF/88 art. 150 VI c garante imunidade tributária às instituições de educação e de assistência social sem fins lucrativos. Os requisitos do art. 14 do CTN (não distribuição de lucros, aplicação integral dos recursos no país, escrituração regular) são plenamente atendidos. A jurisprudência do STF (ADI 1.802/DF; RE 566.622/RS) consolida a imunidade ampla, incluindo rendas não estritamente ligadas às atividades-fim.`, lightContent: `A imunidade tributária do art. 150 VI c da CF/88 abrange o patrimônio e as rendas da entidade.`, omittedContent: `[fundamento constitucional e legal da imunidade e demonstração do cumprimento dos requisitos do CTN não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento constitucional da imunidade e da demonstração do cumprimento dos requisitos do art. 14 do CTN", correctPresenceKeywords: ["CF/88 art. 150", "CTN art. 14", "STF"] },
    { id: "pedidos_imunidade", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) declaração de imunidade tributária sobre o patrimônio e rendas destinadas às finalidades essenciais; (b) repetição de ${fmt(impostosCents)} cobrados indevidamente; (c) suspensão de cobranças futuras; (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer o reconhecimento da imunidade tributária e a restituição dos tributos cobrados indevidamente.`, omittedContent: `[pedido de declaração de imunidade sem identificação dos tributos e do valor a repetir]`, omissionDescription: "pedido de declaração de imunidade tributária sem identificação dos tributos e do valor indevidamente cobrado a ser restituído", correctPresenceKeywords: [fmt(impostosCents), "imunidade", "restituição"] },
  ];
}

// ─── TRIB-008: PARCELAMENTO_TRIBUTARIO (MODERATE) ─────────────────────────────
function buildParcelamentoTributario(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const totalCents = dn(seed, "tot8", 10000000, 80000000);
  const parcelas = dn(seed, "par8", 36, 84);
  const parcelaCents = Math.round(totalCents / parcelas);
  const desconto = dn(seed, "desc8", 20, 50);
  const totalDescCents = Math.round(totalCents * (1 - desconto / 100));
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${emp.toUpperCase()}, CNPJ n.º ${cn}, apresenta\n\nCUMPRIMENTO DE SENTENÇA — PARCELAMENTO TRIBUTÁRIO\n\nem face da União Federal\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [emp, cn] },
    { id: "titulo_parcelamento", section: DocumentSection.DOS_FATOS, fullContent: `A sentença transitada em julgado em ${seed.baseDate} determinou o ingresso da autora no programa de parcelamento PERT (Lei 13.496/2017), com desconto de ${desconto}% sobre as multas e encargos, totalizando ${fmt(totalDescCents)} a ser quitado em ${parcelas} parcelas mensais.`, lightContent: `A sentença determinou o ingresso da autora no parcelamento tributário com desconto sobre as multas.`, omittedContent: `[título executivo do parcelamento e programa identificado não especificados]`, omissionDescription: "ausência de identificação do título executivo, do programa de parcelamento e dos parâmetros fixados na sentença", correctPresenceKeywords: [seed.baseDate, fmt(totalDescCents), String(parcelas)] },
    { id: "termos_parcelamento", section: DocumentSection.DO_DIREITO, fullContent: `O PERT (Lei 13.496/2017) permite o parcelamento de débitos federais em até 120 meses com descontos de até 100% de multas e encargos para pagamento à vista. O desconto de ${desconto}% sobre multas e juros é fixado com base no art. 2.º da Lei 13.496/2017. A sentença homologou o ingresso com base na modalidade ${["pagamento à vista com uso de crédito", "parcelamento em 60x", "parcelamento em 84x", "parcelamento em 120x"][h(seed.cpf + "mod8") % 4]}.`, lightContent: `Os termos do PERT determinam o desconto aplicável e o número de parcelas.`, omittedContent: `[modalidade do PERT, percentual de desconto e número de parcelas fixados na sentença não identificados]`, omissionDescription: "ausência de identificação da modalidade do PERT, do percentual de desconto e do número de parcelas fixados na sentença", correctPresenceKeywords: ["Lei 13.496", "PERT", String(desconto)] },
    { id: "calculo_parcelas", section: DocumentSection.DAS_PROVAS, fullContent: `Cálculo do parcelamento: Dívida bruta ${fmt(totalCents)} − desconto ${desconto}% sobre multas/encargos (${fmt(totalCents - totalDescCents)}) = Total parcelado ${fmt(totalDescCents)} ÷ ${parcelas} parcelas = ${fmt(parcelaCents)}/mês. 1.ª parcela vence em ${seed.derDate}.`, lightContent: `O valor das parcelas mensais será calculado com base nos parâmetros da sentença.`, omittedContent: `[cálculo das parcelas mensais com base no desconto e no total parcelado não demonstrado]`, omissionDescription: "ausência de demonstração do cálculo das parcelas mensais com base no desconto aplicado e no total do parcelamento PERT", correctPresenceKeywords: [fmt(parcelaCents), String(parcelas), fmt(totalDescCents)] },
    { id: "pedidos_parcelamento", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) intimação da União para implementar o parcelamento com ${parcelas} parcelas de ${fmt(parcelaCents)}; (b) suspensão de penhoras e protesto; (c) honorários executivos de 10% (CPC art. 85 §1.º).`, lightContent: `Requer a implementação do parcelamento e a suspensão das medidas constritivas.`, omittedContent: `[pedido executivo sem valor das parcelas e número de prestações especificados]`, omissionDescription: "pedido executivo de parcelamento tributário sem especificação do valor das parcelas e do número de prestações", correctPresenceKeywords: [fmt(parcelaCents), String(parcelas), "suspensão"] },
  ];
}

// ─── TRIB-009: REDIRECIONAMENTO_EXECUCAO (LIGHT) ──────────────────────────────
function buildRedirecionamentoExecucao(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const debitoCents = dn(seed, "deb9", 2000000, 15000000);
  const socioName = ["João Carlos Pereira", "Roberto Lima Santos", "Ana Maria Alves", "Carlos Eduardo Figueiredo"][h(seed.cpf + "soc9") % 4];
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${socioName.toUpperCase()}, CPF n.º ${seed.cpf}, apresenta\n\nAGRAVO DE INSTRUMENTO\n\ncontra decisão que determinou o redirecionamento da execução fiscal\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [socioName, seed.cpf] },
    { id: "decisao_recorrida_redir", section: DocumentSection.DOS_FATOS, fullContent: `A decisão agravada determinou o redirecionamento da execução fiscal de ${fmt(debitoCents)} contra o agravante, sócio da ${emp} (CNPJ ${cn}), com base no art. 135 III do CTN, alegando gestão fraudulenta. O agravante comprova que se retirou da sociedade em ${seed.baseDate}, antes do fato gerador do débito (${seed.derDate}), e que não praticou qualquer ato de gestão irregular.`, lightContent: `A decisão redirecionou a execução fiscal contra o agravante com base em suposta gestão fraudulenta.`, omittedContent: `[dados da decisão recorrida, valor do débito e data de retirada do agravante não identificados]`, omissionDescription: "ausência de identificação dos dados da decisão recorrida, do valor do débito e da data de retirada do sócio da sociedade", correctPresenceKeywords: [fmt(debitoCents), seed.baseDate, "art. 135"] },
    { id: "fatos_responsabilidade", section: DocumentSection.DOS_FATOS, fullContent: `O agravante se retirou da ${emp} em ${seed.baseDate}, conforme Alteração Contratual arquivada na JUCE sob n.º ${dn(seed, "juce9", 10000, 89999)}/${2020 + h(seed.cpf + "ya") % 4}. Os débitos de ${fmt(debitoCents)} foram constituídos apenas em ${seed.derDate}, quando o agravante já não era sócio. A Súmula 430 do STJ impede o redirecionamento nesses casos.`, lightContent: `O agravante demonstra que sua retirada da sociedade antecedeu a constituição do débito tributário.`, omittedContent: `[documento de retirada da sociedade e data de constituição do débito não especificados]`, omissionDescription: "ausência de especificação do documento de retirada da sociedade e da demonstração de que o débito foi constituído após a saída do sócio", correctPresenceKeywords: [seed.baseDate, seed.derDate, "Súmula 430"] },
    { id: "fundamento_redirecionamento", section: DocumentSection.DO_DIREITO, fullContent: `O redirecionamento exige prova do ato ilícito praticado pelo sócio-gerente (CTN art. 135 III; Súm. 430 STJ). A mera inadimplência não autoriza o redirecionamento (REsp 1.101.728/SP — 1.ª Seção do STJ, repetitivo). A retirada regular antes do fato gerador exclui a responsabilidade pessoal (Súm. 430 STJ). A decisão agravada, ao redirecionar sem prova de ato ilícito, viola o due process of law (CF/88 art. 5.º LIV).`, lightContent: `O redirecionamento exige prova de ato ilícito do sócio, não sendo cabível pela mera inadimplência.`, omittedContent: `[fundamento jurídico para contestar o redirecionamento com base na Súmula 430 STJ e no CTN não desenvolvido]`, omissionDescription: "ausência de desenvolvimento do fundamento jurídico para contestar o redirecionamento, com base na Súmula 430 STJ e no requisito de prova de ato ilícito do sócio", correctPresenceKeywords: ["CTN art. 135", "Súm. 430", "REsp 1.101.728"] },
    { id: "pedido_recursal_redir", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer o provimento do agravo para: (a) cassar a decisão de redirecionamento; (b) excluir o agravante do polo passivo da execução fiscal; (c) honorários recursais. Tutela de urgência para suspender os efeitos do redirecionamento.`, lightContent: `Requer a cassação da decisão de redirecionamento e a exclusão do agravante do polo passivo.`, omittedContent: `[pedido recursal sem identificação do fundamento para exclusão do polo passivo e da tutela de urgência]`, omissionDescription: "pedido recursal de agravo sem identificação do fundamento para exclusão do polo passivo e do pedido de tutela de urgência", correctPresenceKeywords: ["redirecionamento", "polo passivo", "tutela"] },
  ];
}

// ─── TRIB-010: MANDADO_SEGURANCA_TRIBUTARIO (MODERATE) ────────────────────────
function buildMandadoSegurancaTributario(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const tributo = ["COFINS", "PIS", "CSLL", "IRPJ"][h(seed.cpf + "trib10") % 4];
  const valorCents = dn(seed, "val10", 2000000, 10000000);
  const atoCoator = ["cobrança de" + " " + tributo + " sem autorização legal", "negativa de aproveitamento de crédito de " + tributo, "exigência de GNRE antes da saída da mercadoria", "restrição de emissão de NF por débito em discussão"][h(seed.cpf + "ato10") % 4];
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${emp.toUpperCase()}, CNPJ n.º ${cn}, vem impetrar\n\nMANDADO DE SEGURANÇA TRIBUTÁRIO\n\ncontra ato do Delegado da Receita Federal de ${seed.city}\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [emp, cn] },
    { id: "fatos_ato_coator", section: DocumentSection.DOS_FATOS, fullContent: `A autoridade coatora praticou ato de ${atoCoator}, no valor de ${fmt(valorCents)}, em ${seed.baseDate}, sem amparo legal e em violação ao direito líquido e certo da impetrante (Lei 12.016/2009 art. 1.º). O ato consubstancia abuso de poder tributário, pois a impetrante possui liminar favorável no Processo n.º ${seed.processNumber}-APL impedindo a cobrança.`, lightContent: `A autoridade coatora praticou ato ilegal que viola direito líquido e certo da impetrante.`, omittedContent: `[identificação do ato coator, autoridade responsável, data e valor da cobrança indevida não especificados]`, omissionDescription: "ausência de identificação do ato coator, da autoridade responsável, da data e do valor da cobrança indevida", correctPresenceKeywords: [seed.baseDate, fmt(valorCents), "ato coator"] },
    { id: "direito_liquido_certo", section: DocumentSection.DO_DIREITO, fullContent: `O direito líquido e certo da impetrante resulta de: (a) imunidade/isenção aplicável à operação (CF/88 art. 150 ou Lei Complementar); (b) liminar favorável já concedida; (c) ausência de base legal para a exigência de ${tributo} na hipótese. O writ é cabível para combater atos ilegais de autoridade tributária (CF/88 art. 5.º LXIX; Lei 12.016/2009).`, lightContent: `O mandado de segurança é o remédio constitucional adequado para combater ato ilegal da autoridade tributária.`, omittedContent: `[demonstração do direito líquido e certo com fundamento legal específico não realizada]`, omissionDescription: "ausência de demonstração do direito líquido e certo com identificação do fundamento legal específico que torna ilegal a cobrança de " + tributo, correctPresenceKeywords: ["CF/88 art. 5.º LXIX", "Lei 12.016", "direito líquido"] },
    { id: "prova_pre_constituida", section: DocumentSection.DAS_PROVAS, fullContent: `Prova pré-constituída: (a) Notificação da autoridade coatora de ${seed.baseDate}; (b) Cópia da liminar favorável nos autos do Processo n.º ${seed.processNumber}-APL; (c) GIA/DCTF demonstrando as bases de cálculo; (d) Contrato social e certificados de regularidade da impetrante.`, lightContent: `A prova pré-constituída será juntada com a petição inicial do mandado de segurança.`, omittedContent: `[prova pré-constituída do ato coator não juntada à impetração]`, omissionDescription: "ausência de juntada de prova pré-constituída do ato coator, requisito essencial do mandado de segurança tributário", correctPresenceKeywords: ["Notificação", seed.baseDate, "liminar"] },
    { id: "pedidos_ms_tributario", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) liminar para suspender os efeitos do ato coator (Lei 12.016/2009 art. 7.º III); (b) no mérito, concessão definitiva do mandado de segurança; (c) declaração da ilegalidade da cobrança de ${tributo} no valor de ${fmt(valorCents)}; (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a concessão de liminar e do mandado de segurança para suspender a cobrança indevida.`, omittedContent: `[pedido de mandado de segurança sem identificação do ato coator, tributo e valor indevido]`, omissionDescription: "pedido de mandado de segurança tributário sem identificação do ato coator, do tributo e do valor da cobrança indevida", correctPresenceKeywords: [fmt(valorCents), "Lei 12.016", "liminar"] },
  ];
}

// ─── TRIB-011: ISENCAO_IRPF_DOENCA (GOOD) ────────────────────────────────────
function buildIsencaoIrpfDoenca(seed: CaseSeedData): DocumentElement[] {
  const doencas = ["cardiopatia grave (Lei 7.713/1988 art. 6.º XIV)", "neoplasia maligna (Lei 7.713/1988 art. 6.º XIV)", "hepatopatia grave (Lei 7.713/1988 art. 6.º XIV)", "nefropatia grave (Lei 7.713/1988 art. 6.º XIV)"];
  const doenca = doencas[h(seed.cpf + "doc11") % doencas.length];
  const rendimentosCents = dn(seed, "rend11", 400000, 1500000);
  const irPagoCents = Math.round(rendimentosCents * 0.15);
  const cid = ["I25", "C50", "K70", "N18"][h(seed.cpf + "doc11") % 4];
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE REPETIÇÃO DE INDÉBITO — ISENÇÃO DE IRPF\n\nem face da União Federal\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, seed.cpf] },
    { id: "fatos_doenca", section: DocumentSection.DOS_FATOS, fullContent: `O(a) autor(a) é portador(a) de ${doenca} (CID-10: ${cid}), diagnosticada em ${seed.baseDate} pelo Dr. ${["Marcelo", "Paulo", "André", "Luiz"][h(seed.cpf + "dr11") % 4]} Costa (CRM ${dn(seed, "crm11", 10000, 89999)}). Desde ${seed.derDate}, percebe proventos de aposentadoria no valor de ${fmt(rendimentosCents)}/mês, sobre os quais a Receita Federal reteve IRPF na fonte — indevidamente — no total de ${fmt(irPagoCents)}.`, lightContent: `O(a) autor(a) portador(a) de doença grave teve IRPF retido indevidamente sobre seus proventos de aposentadoria.`, omittedContent: `[diagnóstico, CID, data e médico responsável pela doença grave que fundamenta a isenção não identificados]`, omissionDescription: "ausência de identificação do diagnóstico da doença grave com CID, data e médico responsável para fundamentar a isenção de IRPF", correctPresenceKeywords: [cid, seed.baseDate, fmt(irPagoCents)] },
    { id: "laudo_medico_isencao", section: DocumentSection.DAS_PROVAS, fullContent: `Laudo médico emitido pelo Dr. ${["Marcelo", "Paulo", "André", "Luiz"][h(seed.cpf + "dr11") % 4]} Costa (CRM ${dn(seed, "crm11", 10000, 89999)}) atesta que o(a) autor(a) é portador(a) de ${doenca}, CID-10 ${cid}, com diagnóstico em ${seed.baseDate}, em caráter de permanência. Junta-se ainda: exames complementares, laudos de especialistas e declaração de saúde da previdência social.`, lightContent: `O laudo médico comprovando a doença grave será juntado com a petição inicial.`, omittedContent: `[laudo médico comprobatório da doença grave (CID, médico, data) não juntado à petição inicial]`, omissionDescription: "ausência de juntada de laudo médico comprobatório da doença grave com CID, nome do médico e data, requisito essencial para reconhecimento da isenção de IRPF", correctPresenceKeywords: [cid, "laudo médico", seed.baseDate] },
    { id: "direito_isencao", section: DocumentSection.DO_DIREITO, fullContent: `O art. 6.º XIV da Lei 7.713/1988 isenta de IRPF os proventos de aposentadoria percebidos por portadores de ${doenca}. A isenção é ampla e alcança o rendimento total dos proventos, independentemente de o laudo ter sido emitido após a aposentadoria (Súm. 627 STJ). O IRPF retido no valor de ${fmt(irPagoCents)} é indevido e deve ser restituído com SELIC (Lei 9.250/1995 art. 39 §4.º).`, lightContent: `A isenção de IRPF para portadores de doença grave está prevista no art. 6.º XIV da Lei 7.713/1988.`, omittedContent: `[fundamento legal da isenção de IRPF para portadores de doença grave e Súmula do STJ não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal da isenção de IRPF para portadores de doença grave e da Súmula 627 do STJ", correctPresenceKeywords: ["Lei 7.713", "art. 6.º XIV", "Súm. 627"] },
    { id: "pedidos_isencao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) declaração da isenção de IRPF sobre os proventos de aposentadoria por força do art. 6.º XIV da Lei 7.713/1988; (b) restituição de ${fmt(irPagoCents)} retidos indevidamente, acrescidos de SELIC; (c) compensação com débitos futuros; (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer o reconhecimento da isenção e a restituição do IRPF retido indevidamente.`, omittedContent: `[pedido de isenção sem identificação da doença, do valor retido e do fundamento legal]`, omissionDescription: "pedido de isenção de IRPF sem identificação da doença grave, do valor retido indevidamente e do fundamento legal específico", correctPresenceKeywords: [fmt(irPagoCents), "Lei 7.713", "SELIC"] },
  ];
}

// ─── TRIB-012: DECLARATORIA_INEXIGIBILIDADE (LIGHT) ──────────────────────────
function buildDeclaratoriaInexigibilidade(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const tributo = ["CSLL", "PIS", "COFINS", "IRPJ"][h(seed.cpf + "trib12") % 4];
  const valorCents = dn(seed, "val12", 1000000, 8000000);
  const tese = ["inconstitucionalidade da base de cálculo ampliada do PIS/COFINS (RE 574.706/PR — STF)", "inaplicabilidade do IRPJ sobre juros Selic na repetição de indébito (STJ Tema 962)", "exclusão do ISS da base de cálculo do PIS/COFINS (STJ Tema 634)", "inconstitucionalidade da CSLL sobre resultados de exportação"][h(seed.cpf + "tese12") % 4];
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${emp.toUpperCase()}, CNPJ n.º ${cn}, vem propor\n\nAÇÃO DECLARATÓRIA DE INEXIGIBILIDADE TRIBUTÁRIA\n\nem face da União Federal\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [emp, cn] },
    { id: "fatos_inexigibilidade", section: DocumentSection.DOS_FATOS, fullContent: `A autora recolheu ${tributo} no valor de ${fmt(valorCents)} com base na tese da Fazenda, porém o STF/STJ firmou o entendimento de ${tese}. Com a decisão favorável transitada em julgado, os créditos recolhidos a maior de ${seed.baseDate} a ${seed.derDate} são inexigíveis e devem ser restituídos.`, lightContent: `A autora recolheu ${tributo} indevidamente em decorrência de tese tributária afastada pelo STF/STJ.`, omittedContent: `[tributo indevidamente recolhido, período e tese jurídica vitoriosa no STF/STJ não identificados]`, omissionDescription: "ausência de identificação do tributo indevidamente recolhido, do período e da tese jurídica firmada pelo STF/STJ que torna os valores inexigíveis", correctPresenceKeywords: [tributo, fmt(valorCents), seed.baseDate] },
    { id: "fundamento_inexigibilidade", section: DocumentSection.DO_DIREITO, fullContent: `A inexigibilidade decorre da tese firmada: ${tese}. A decisão é de aplicação obrigatória (CPC art. 927 V; CF/88 art. 102 §2.º). A autora tem direito à restituição do indébito (CTN art. 165) acrescido de SELIC (Lei 9.250/1995 art. 39 §4.º), pelo prazo prescricional de 5 anos (CTN art. 168 I).`, lightContent: `A inexigibilidade tributária é reconhecida por decisão vinculante do STF/STJ.`, omittedContent: `[fundamento jurídico da inexigibilidade com citação da decisão vinculante do STF/STJ não desenvolvido]`, omissionDescription: "ausência de desenvolvimento do fundamento jurídico da inexigibilidade com citação da decisão vinculante do STF/STJ e do prazo prescricional para repetição", correctPresenceKeywords: ["CPC art. 927", "CTN art. 165", "SELIC"] },
    { id: "direito_declaratoria", section: DocumentSection.DO_DIREITO, fullContent: `A ação declaratória é o instrumento adequado para obter a certeza jurídica da inexigibilidade tributária (CPC art. 19 I) cumulada com a condenação à restituição (STJ, REsp 1.111.164/BA — Recurso Repetitivo). A habilitação do crédito é feita via PER/DCOMP (IN RFB 2.055/2021).`, lightContent: `A ação declaratória é o meio processual adequado para reconhecer a inexigibilidade e obter a restituição.`, omittedContent: `[adequação da ação declaratória e mecanismo de habilitação do crédito não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento da adequação da ação declaratória e do mecanismo de habilitação do crédito junto à RFB", correctPresenceKeywords: ["CPC art. 19", "PER/DCOMP", "REsp 1.111.164"] },
    { id: "pedidos_declaratoria", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) declaração da inexigibilidade de ${tributo} com base na tese vitoriosa; (b) condenação à restituição de ${fmt(valorCents)} acrescidos de SELIC; (c) autorização para compensação via PER/DCOMP; (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a declaração de inexigibilidade e a restituição do tributo indevidamente recolhido.`, omittedContent: `[pedido declaratório sem identificação do tributo, do valor e da tese jurídica aplicável]`, omissionDescription: "pedido declaratório de inexigibilidade sem identificação do tributo, do valor indevidamente recolhido e da tese jurídica aplicável", correctPresenceKeywords: [fmt(valorCents), tributo, "PER/DCOMP"] },
  ];
}

// ─── TRIB-013: CREDITO_ICMS_PRESUMIDO (GOOD) ──────────────────────────────────
function buildCreditoIcmsPresumido(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const creditoCents = dn(seed, "icms13", 3000000, 15000000);
  const periodos = dn(seed, "per13", 12, 24);
  const aliqEstado = dn(seed, "aliq13", 7, 5);
  const aliqFederal = 12;
  const difAliq = aliqFederal - aliqEstado;
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${emp.toUpperCase()}, CNPJ n.º ${cn}, vem propor\n\nAÇÃO DECLARATÓRIA DE CRÉDITO DE ICMS PRESUMIDO\n\nem face do Estado e da União Federal\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [emp, cn] },
    { id: "fatos_credito_icms", section: DocumentSection.DOS_FATOS, fullContent: `A autora adquiriu mercadorias de fornecedores localizados em estado que concedeu crédito de ICMS presumido de ${aliqEstado}% (Convênio ICMS autorizado pelo CONFAZ), enquanto a alíquota interestadual é de ${aliqFederal}%. Ao longo de ${periodos} competências (${seed.baseDate} a ${seed.derDate}), o crédito presumido de ICMS acumulado equivale a ${fmt(creditoCents)}.`, lightContent: `A autora possui crédito de ICMS presumido decorrente de aquisições interestaduais com incentivo fiscal.`, omittedContent: `[origem do crédito presumido de ICMS, Convênio CONFAZ aplicável e período não identificados]`, omissionDescription: "ausência de identificação da origem do crédito presumido de ICMS com identificação do Convênio CONFAZ e do período de apuração", correctPresenceKeywords: [String(aliqEstado), fmt(creditoCents), "CONFAZ"] },
    { id: "calculo_credito_icms", section: DocumentSection.DOS_FATOS, fullContent: `Demonstrativo do crédito presumido de ICMS: Alíquota interestadual: ${aliqFederal}% − Alíquota do estado de origem: ${aliqEstado}% = Diferença: ${difAliq}%. Base de cálculo total em ${periodos} meses: ${fmt(Math.round(creditoCents / difAliq * 100))}. Crédito total apurado: ${fmt(creditoCents)}. O crédito é aproveitável conforme art. 23 da LC 87/1996 (Lei Kandir).`, lightContent: `O crédito de ICMS presumido será apurado conforme os Convênios CONFAZ aplicáveis.`, omittedContent: `[cálculo do crédito presumido de ICMS por competência com base de cálculo e alíquotas não demonstrado]`, omissionDescription: "ausência de cálculo do crédito presumido de ICMS por competência com identificação das alíquotas (interestadual e do estado de origem) e da base de cálculo", correctPresenceKeywords: [String(aliqEstado), fmt(creditoCents), "LC 87"] },
    { id: "direito_icms", section: DocumentSection.DO_DIREITO, fullContent: `A LC 87/1996 (Lei Kandir) garante o direito ao aproveitamento de créditos de ICMS nas operações interestaduais (art. 23). O STF, no RE 628.075/RS, reconheceu o direito ao crédito presumido de ICMS concedido por estado mediante Convênio CONFAZ. A glosa do crédito pelo Fisco sem autorização do CONFAZ viola a harmonia federativa (CF/88 art. 155 §2.º XII g).`, lightContent: `O aproveitamento do crédito presumido de ICMS é assegurado pela LC 87/1996 e pela jurisprudência do STF.`, omittedContent: `[fundamento legal do crédito presumido de ICMS e jurisprudência do STF não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal do crédito presumido de ICMS e da jurisprudência do STF sobre o tema", correctPresenceKeywords: ["LC 87/1996", "RE 628.075", "CONFAZ"] },
    { id: "pedidos_icms", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) declaração do direito ao aproveitamento do crédito presumido de ICMS no valor de ${fmt(creditoCents)} (${periodos} competências); (b) autorização para compensação com ICMS a recolher; (c) cancelamento de auto de infração por glosa; (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a declaração do direito ao crédito presumido de ICMS e sua compensação.`, omittedContent: `[pedido de aproveitamento do crédito de ICMS sem valor e período especificados]`, omissionDescription: "pedido de aproveitamento de crédito presumido de ICMS sem especificação do valor, do período e do Convênio CONFAZ aplicável", correctPresenceKeywords: [fmt(creditoCents), String(periodos), "compensação"] },
  ];
}

// ─── TRIB-014: DECADENCIA_TRIBUTARIA (MODERATE) ───────────────────────────────
function buildDecadenciaTributaria(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const tributo = ["IRPJ", "CSLL", "IPI", "PIS"][h(seed.cpf + "trib14") % 4];
  const valorCents = dn(seed, "val14", 3000000, 18000000);
  const anoFatoGerador = 2014 + (h(seed.cpf + "ano14") % 4);
  const anoLancamento = anoFatoGerador + 6;
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${emp.toUpperCase()}, CNPJ n.º ${cn}, apresenta\n\nAPELAÇÃO CÍVEL\n\nem face de sentença que afastou a decadência tributária\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [emp, cn] },
    { id: "decisao_recorrida_decadencia", section: DocumentSection.DOS_FATOS, fullContent: `A sentença recorrida afastou a decadência do lançamento de ${tributo} no valor de ${fmt(valorCents)}, referente ao fato gerador de ${anoFatoGerador}, sob o argumento de que o prazo decadencial teria sido interrompido por notificação de início de procedimento fiscal em ${seed.baseDate}. O apelante demonstra que a notificação não produz interrupção da decadência (CTN art. 173 I).`, lightContent: `A sentença afastou a decadência do lançamento tributário, rejeitando a defesa do apelante.`, omittedContent: `[sentença recorrida, ano do fato gerador, valor e argumento de decadência não identificados]`, omissionDescription: "ausência de identificação da sentença recorrida, do ano do fato gerador, do valor do crédito e do argumento de decadência", correctPresenceKeywords: [String(anoFatoGerador), fmt(valorCents), "CTN art. 173"] },
    { id: "fatos_decadencia", section: DocumentSection.DO_DIREITO, fullContent: `O fato gerador de ${tributo} ocorreu em ${anoFatoGerador}. O prazo decadencial de 5 anos para o lançamento (CTN art. 173 I) venceu em ${anoFatoGerador + 5}. O lançamento foi formalizado apenas em ${anoLancamento} — após o prazo decadencial. A notificação de início de fiscalização não interrompe a decadência (CTN art. 173 I; REsp 1.143.124/SC — STJ).`, lightContent: `O prazo decadencial de 5 anos transcorreu antes do lançamento tributário.`, omittedContent: `[ano do fato gerador, prazo decadencial e data do lançamento tardio não demonstrados]`, omissionDescription: "ausência de demonstração do ano do fato gerador, do prazo decadencial de 5 anos e da data do lançamento tardio que ultrapassou o prazo", correctPresenceKeywords: [String(anoFatoGerador), String(anoFatoGerador + 5), String(anoLancamento)] },
    { id: "calculo_prazo_decadencia", section: DocumentSection.DOS_FATOS, fullContent: `Linha do tempo da decadência: Fato gerador: ${seed.baseDate} (${anoFatoGerador}) → Prazo decadencial de 5 anos (CTN art. 173 I): encerrado em ${anoFatoGerador + 5} → Lançamento efetuado em ${seed.derDate} (${anoLancamento}) → Decadência consumada: crédito extinto (CTN art. 156 V). A notificação de ${seed.baseDate} é ineficaz para interromper a decadência (não há interrupção prevista no CTN art. 173).`, lightContent: `O prazo decadencial de 5 anos encerrou-se antes do lançamento formal do crédito tributário.`, omittedContent: `[linha do tempo da decadência com datas do fato gerador, encerramento do prazo e data do lançamento não demonstrada]`, omissionDescription: "ausência de linha do tempo demonstrando as datas do fato gerador, encerramento do prazo decadencial de 5 anos e data do lançamento tributário tardio", correctPresenceKeywords: [String(anoFatoGerador + 5), String(anoLancamento), "CTN art. 156"] },
    { id: "pedido_recursal_decadencia", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer o provimento do apelo para: (a) reconhecer a decadência do lançamento de ${tributo} no valor de ${fmt(valorCents)} (CTN arts. 156 V e 173 I); (b) anular o lançamento; (c) honorários recursais.`, lightContent: `Requer o reconhecimento da decadência e a anulação do lançamento tributário.`, omittedContent: `[pedido de reconhecimento da decadência sem identificação do tributo, do valor e do prazo transcorrido]`, omissionDescription: "pedido de reconhecimento de decadência tributária sem especificação do tributo, do valor do crédito e da demonstração do prazo decadencial", correctPresenceKeywords: [fmt(valorCents), "CTN art. 173", "decadência"] },
  ];
}

// ─── TRIB-015: CUMPRIMENTO_TRIBUTARIO (GOOD) ──────────────────────────────────
function buildCumprimentoTributario(seed: CaseSeedData): DocumentElement[] {
  const emp = empresa(seed);
  const cn = cnpj(seed);
  const principalCents = dn(seed, "pc15t", 3000000, 12000000);
  const selicPct = dn(seed, "sel15", 8, 20);
  const totalCents = Math.round(principalCents * (1 + selicPct / 100));
  const correcaoCents = totalCents - principalCents;
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${emp.toUpperCase()}, CNPJ n.º ${cn}, apresenta\n\nCUMPRIMENTO DE SENTENÇA TRIBUTÁRIA\n\nem face da União Federal\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [emp, cn] },
    { id: "titulo_tributario", section: DocumentSection.DOS_FATOS, fullContent: `A sentença transitada em julgado em ${seed.baseDate} reconheceu o direito da autora à restituição de tributo pago indevidamente no valor principal de ${fmt(principalCents)}, acrescido de correção pela taxa SELIC (Lei 9.250/1995 art. 39 §4.º; CTN art. 167 parágrafo único).`, lightContent: `A sentença transitada em julgado reconheceu o direito à restituição do tributo indevidamente recolhido.`, omittedContent: `[título executivo e parâmetros da sentença tributária não identificados]`, omissionDescription: "ausência de identificação do título executivo com valores, data da sentença e parâmetros de atualização", correctPresenceKeywords: [seed.baseDate, fmt(principalCents), "SELIC"] },
    { id: "parametros_tributario", section: DocumentSection.DO_DIREITO, fullContent: `Parâmetros da liquidação: correção pela SELIC acumulada de ${seed.baseDate} a ${seed.derDate} (${selicPct}%) sobre ${fmt(principalCents)} = ${fmt(correcaoCents)} de atualização. Total a restituir: ${fmt(totalCents)} (CTN art. 167 parágrafo único; Lei 9.250/1995 art. 39 §4.º). Não há dedução de IRPF sobre valores restituídos de tributo indevido (Súm. 447 STJ).`, lightContent: `Os parâmetros de atualização pela SELIC são os fixados na sentença.`, omittedContent: `[cálculo da atualização pela SELIC e total a restituir não demonstrados]`, omissionDescription: "ausência de cálculo da atualização pela SELIC e do total a restituir no cumprimento de sentença tributária", correctPresenceKeywords: [fmt(totalCents), fmt(correcaoCents), "Súm. 447"] },
    { id: "memoria_calculo_tributario", section: DocumentSection.DAS_PROVAS, fullContent: `Memória de cálculo: Principal ${fmt(principalCents)} + SELIC ${selicPct}% = ${fmt(correcaoCents)} → Total ${fmt(totalCents)}. Planilha de cálculo elaborada com base nas taxas SELIC acumuladas divulgadas pelo Banco Central (de ${seed.baseDate} a ${seed.derDate}).`, lightContent: `A memória de cálculo será apresentada com base nas taxas SELIC do período.`, omittedContent: `[memória de cálculo com taxas SELIC e planilha não apresentada no cumprimento de sentença tributária]`, omissionDescription: "ausência de memória de cálculo com taxas SELIC por período e planilha de atualização no cumprimento de sentença tributária", correctPresenceKeywords: [fmt(totalCents), "SELIC", String(selicPct)] },
    { id: "pedidos_executivos_tributario", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) expedição de precatório/RPV no valor de ${fmt(totalCents)} (CF/88 art. 100); (b) preferência de RPV se o valor for inferior a 60 salários mínimos; (c) honorários executivos de 10% (CPC art. 85 §1.º).`, lightContent: `Requer a expedição de precatório/RPV para pagamento do valor reconhecido na sentença.`, omittedContent: `[pedido de precatório/RPV sem valor especificado e fundamento constitucional]`, omissionDescription: "pedido de precatório/RPV no cumprimento de sentença tributária sem especificação do valor total e do fundamento constitucional", correctPresenceKeywords: [fmt(totalCents), "CF/88 art. 100", "RPV"] },
  ];
}

// ─── Dispatch ──────────────────────────────────────────────────────────────────

export function buildTributarioElements(
  config: TributarioScenarioConfig,
  seed: CaseSeedData,
): DocumentElement[] {
  switch (config.issueType) {
    case "EMBARGOS_EXECUCAO_FISCAL":       return buildEmbargosExecucaoFiscal(seed);
    case "COMPENSACAO_CREDITO_TRIBUTARIO": return buildCompensacaoCredito(seed);
    case "EXCLUSAO_SIMPLES_NACIONAL":      return buildExclusaoSimplesNacional(seed);
    case "RESTITUICAO_TRIBUTO_INDEVIDO":   return buildRestituicaoTributoIndevido(seed);
    case "PRESCRICAO_TRIBUTARIA":          return buildPrescricaoTributaria(seed);
    case "ANULATORIA_AUTO_INFRACAO":       return buildAnulatoriaAutoInfracao(seed);
    case "IMUNIDADE_TRIBUTARIA":           return buildImunidadeTributaria(seed);
    case "PARCELAMENTO_TRIBUTARIO":        return buildParcelamentoTributario(seed);
    case "REDIRECIONAMENTO_EXECUCAO":      return buildRedirecionamentoExecucao(seed);
    case "MANDADO_SEGURANCA_TRIBUTARIO":   return buildMandadoSegurancaTributario(seed);
    case "ISENCAO_IRPF_DOENCA":            return buildIsencaoIrpfDoenca(seed);
    case "DECLARATORIA_INEXIGIBILIDADE":   return buildDeclaratoriaInexigibilidade(seed);
    case "CREDITO_ICMS_PRESUMIDO":         return buildCreditoIcmsPresumido(seed);
    case "DECADENCIA_TRIBUTARIA":          return buildDecadenciaTributaria(seed);
    case "CUMPRIMENTO_TRIBUTARIO":         return buildCumprimentoTributario(seed);
    default:
      throw new Error(`Builder não encontrado para issueType: ${(config as { issueType: string }).issueType}`);
  }
}
