/**
 * FASE 9.0.9 — Consumidor Element Factory
 */

import type { DocumentElement, CaseSeedData } from "../gold-corpus-v2.types.js";
import { DocumentSection } from "../gold-corpus-v2.types.js";
import type { ConsumidorScenarioConfig } from "./consumidor-scenario.types.js";

function h(s: string): number {
  let n = 2166136261;
  for (let i = 0; i < s.length; i++) n = Math.imul(n ^ s.charCodeAt(i), 16777619);
  return n >>> 0;
}

function dn(seed: CaseSeedData, salt: string, min: number, range: number): number {
  return min + (h(seed.cpf + salt) % range);
}

function fmt(cents: number): string {
  return `R$ ${(cents / 100).toFixed(2).replace(".", ",")}`;
}

function reu(seed: CaseSeedData): string {
  const nomes = ["Banco Itaú S.A.", "Operadora Saúde S/A", "Construtora Alpha Ltda.", "Telecom Brasil S.A.", "Seguradora Nacional S/A"];
  return nomes[h(seed.cpf + "ru") % nomes.length];
}

function fornecedor(seed: CaseSeedData): string {
  const nomes = ["Magazine Econômico S.A.", "Eletro Fácil Ltda.", "SuperMercado Brasil S.A.", "Loja Virtual Comex Ltda."];
  return nomes[h(seed.cpf + "forn") % nomes.length];
}

// ─── CONS-001: DANO_MORAL_CONSUMIDOR (GOOD) ──────────────────────────────────
function buildDanoMoralConsumidor(seed: CaseSeedData): DocumentElement[] {
  const r = reu(seed);
  const danoCents = dn(seed, "dm1", 500000, 3000000);
  const materialCents = dn(seed, "mat1", 100000, 500000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE INDENIZAÇÃO POR DANO MORAL — RELAÇÃO DE CONSUMO\n\nem face de ${r.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, r] },
    { id: "fatos_dano", section: DocumentSection.DOS_FATOS, fullContent: `Em ${seed.baseDate}, o(a) autor(a) adquiriu produto/contratou serviço de ${r}, pagando ${fmt(materialCents)}. O fornecedor, contudo, não cumpriu o acordado, expondo o consumidor a situação vexatória: ${["cobrança indevida com negativação no SPC/SERASA", "serviço não prestado com retenção do valor pago", "produto entregue defeituoso e recusa de troca", "encerramento unilateral de conta com retenção de saldo"][h(seed.cpf + "fat1") % 4]}. A conduta ilícita ocorreu em ${seed.derDate} e causou abalo psicológico documentado.`, lightContent: `O autor sofreu dano moral em relação de consumo com o fornecedor réu.`, omittedContent: `[data do evento, conduta ilícita do fornecedor e abalo causado não identificados]`, omissionDescription: "ausência de identificação precisa da data do evento, da conduta ilícita do fornecedor e do abalo psicológico causado ao consumidor", correctPresenceKeywords: [seed.baseDate, fmt(materialCents), r] },
    { id: "nexo_causal_dano", section: DocumentSection.DAS_PROVAS, fullContent: `Comprovam o nexo causal: (a) contrato assinado em ${seed.baseDate} (código ${seed.processNumber.slice(-6)}); (b) boletim de ocorrência registrado em ${seed.derDate}; (c) print-screens das tentativas de solução administrativa (${dn(seed, "nco1", 3, 8)} registros no SAC); (d) extrato bancário com desconto indevido de ${fmt(materialCents)}; (e) laudo psicológico atestando ansiedade e estresse.`, lightContent: `O nexo causal entre a conduta do réu e o dano sofrido será comprovado por documentos.`, omittedContent: `[nexo causal entre conduta do réu e dano — documentos comprobatórios não juntados]`, omissionDescription: "ausência de documentos comprobatórios do nexo causal entre a conduta do fornecedor e o dano moral sofrido pelo consumidor", correctPresenceKeywords: [seed.baseDate, fmt(materialCents), "SAC"] },
    { id: "valor_dano_moral", section: DocumentSection.DO_DIREITO, fullContent: `O CDC arts. 6.º VI e 14 impõem ao fornecedor responsabilidade objetiva. O dano moral (CC art. 186; CDC art. 6.º VI) é incontestável: o consumidor foi submetido a ${["humilhação pública", "situação de constrangimento", "privação de direito fundamental", "abalo à honra e credibilidade"][h(seed.cpf + "hum1") % 4]}. Quantificação: dano moral de ${fmt(danoCents)} (critério bifásico: STJ REsp 1.152.541/RS) + dano material de ${fmt(materialCents)} comprovado.`, lightContent: `O dano moral do consumidor é indenizável com base no CDC e CC, com quantificação conforme critério bifásico do STJ.`, omittedContent: `[valor do dano moral, critério de quantificação e base legal não identificados]`, omissionDescription: "ausência de identificação do valor do dano moral, do critério de quantificação (bifásico ou punitivo) e da base legal (CDC art. 6.º VI e CC art. 186)", correctPresenceKeywords: [fmt(danoCents), "CDC art. 6.º", "REsp 1.152.541"] },
    { id: "pedidos_dano_moral", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) tutela de urgência para exclusão das restrições creditícias (CDC art. 42; CPC art. 300); (b) condenação em dano moral de ${fmt(danoCents)} (CDC arts. 6.º VI e 14); (c) restituição do dano material de ${fmt(materialCents)} (CDC art. 18); (d) honorários (CPC art. 85). Valor da causa: ${seed.causeValue}.`, lightContent: `Requer indenização por dano moral e material com base no CDC.`, omittedContent: `[pedido de indenização sem valor do dano e fundamento legal especificados]`, omissionDescription: "pedido de indenização por dano moral sem especificação do valor pretendido e do fundamento legal (CDC arts. 6.º VI e 14)", correctPresenceKeywords: [fmt(danoCents), "CDC art. 6.º", fmt(materialCents)] },
  ];
}

// ─── CONS-002: NEGATIVACAO_INDEVIDA (MODERATE) ───────────────────────────────
function buildNegativacaoIndevida(seed: CaseSeedData): DocumentElement[] {
  const r = reu(seed);
  const danoCents = dn(seed, "dm2", 500000, 2000000);
  const debitoCents = dn(seed, "db2", 50000, 300000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE DECLARATÓRIA DE INEXIGIBILIDADE C/C DANO MORAL (NEGATIVAÇÃO INDEVIDA)\n\nem face de ${r.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, r] },
    { id: "fatos_negativacao", section: DocumentSection.DOS_FATOS, fullContent: `O(A) autor(a) tomou ciência em ${seed.baseDate} de que seu nome foi inscrito nos cadastros de proteção ao crédito (SPC e SERASA) por iniciativa de ${r}, referente a débito de ${fmt(debitoCents)} que não reconhece como legítimo — o débito foi quitado em ${seed.derDate} conforme comprovante de pagamento em posse do autor.`, lightContent: `O autor foi negativado indevidamente pelo réu por débito já quitado.`, omittedContent: `[data da negativação, valor negativado e prova de quitação não identificados]`, omissionDescription: "ausência de identificação da data da negativação, do valor inscrito e do comprovante de quitação do débito", correctPresenceKeywords: [seed.baseDate, fmt(debitoCents), seed.derDate] },
    { id: "prova_indevidade", section: DocumentSection.DAS_PROVAS, fullContent: `Comprovam a indevididade: (a) comprovante de pagamento do débito em ${seed.derDate} — Banco ${["Itaú", "Bradesco", "Santander", "BB"][h(seed.cpf + "bk2") % 4]}, agência ${dn(seed, "ag2", 1000, 8999)}, autenticação ${dn(seed, "aut2", 100000000, 899999999)}; (b) consulta ao SERASA/SPC com o apontamento indevido; (c) print-screen da tentativa de estorno no SAC de ${r} em ${seed.baseDate}.`, lightContent: `A quitação do débito e a indevididade da negativação serão comprovadas por documentos.`, omittedContent: `[prova do pagamento do débito e da indevididade da negativação não juntada aos autos]`, omissionDescription: "ausência de juntada da prova do pagamento do débito e da indevididade da negativação (comprovante bancário, consulta SERASA/SPC)", correctPresenceKeywords: [seed.derDate, "SERASA", "SAC"] },
    { id: "direito_negativacao", section: DocumentSection.DO_DIREITO, fullContent: `A Súmula 385 do STJ e o CDC art. 42 §único vedam a cobrança indevida. A negativação indevida gera dano moral in re ipsa (STJ Súmula 388). O CDC art. 43 §3.º exige notificação prévia ao devedor antes da inscrição no cadastro de inadimplentes. A ausência de notificação é fato autônomo de ilicitude. Quantificação do dano: ${fmt(danoCents)}.`, lightContent: `A negativação indevida gera dano moral in re ipsa conforme CDC e STJ.`, omittedContent: `[fundamento legal da negativação indevida (CDC, Súmulas STJ) e valor do dano não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal da negativação indevida (CDC art. 43, Súmulas 385 e 388 do STJ) e do valor do dano moral", correctPresenceKeywords: ["Súmula 385", "CDC art. 43", fmt(danoCents)] },
    { id: "pedidos_negativacao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) tutela de urgência para exclusão imediata da negativação (CPC art. 300); (b) declaração de inexigibilidade do débito; (c) condenação em dano moral de ${fmt(danoCents)} (CDC arts. 6.º e 42); (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a exclusão da negativação indevida e indenização por dano moral.`, omittedContent: `[pedido de exclusão da negativação e indenização sem valor e fundamento legal]`, omissionDescription: "pedido de exclusão da negativação indevida sem identificação do valor do dano moral e do fundamento legal (CDC arts. 6.º e 42)", correctPresenceKeywords: [fmt(danoCents), "CDC art. 6.º", "CPC art. 300"] },
  ];
}

// ─── CONS-003: RECUSA_COBERTURA_PLANO (SEVERE) ───────────────────────────────
function buildRecusaCobertura(seed: CaseSeedData): DocumentElement[] {
  const r = "Operadora Saúde S/A";
  const procedimento = ["cirurgia cardíaca de urgência", "quimioterapia para neoplasia maligna", "transplante de medula óssea", "cirurgia neurológica de urgência"][h(seed.cpf + "proc3") % 4];
  const danoCents = dn(seed, "dm3", 2000000, 10000000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, apresenta\n\nRECURSO DE APELAÇÃO\n\nem face de sentença que negou tutela para cobertura de ${procedimento}\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, procedimento] },
    { id: "decisao_recorrida_plano", section: DocumentSection.DOS_FATOS, fullContent: `A sentença recorrida negou a tutela de urgência para compelir ${r} a custear ${procedimento}, sob o argumento de que o procedimento estaria fora do rol da ANS (RN 465/2021). O recorrente demonstra que: (a) a doença está coberta pelo contrato; (b) o procedimento é indicação médica necessária (Lei 9.656/1998 art. 10 §1.º); (c) a recusa é abusiva (CDC art. 51 IV).`, lightContent: `A sentença negou a tutela para cobertura do procedimento por entendê-lo fora do rol ANS.`, omittedContent: `[sentença recorrida, procedimento negado e fundamento da recusa não identificados]`, omissionDescription: "ausência de identificação da sentença recorrida, do procedimento negado e do fundamento utilizado para negar a cobertura do plano de saúde", correctPresenceKeywords: [procedimento, "Lei 9.656", "CDC art. 51"] },
    { id: "fundamento_cobertura", section: DocumentSection.DO_DIREITO, fullContent: `A recusa é ilegal: (a) STJ Tese 1.03 (Tema 1.069) — o rol ANS é exemplificativo para doenças raras/graves; (b) Lei 9.656/1998 art. 10 §1.º — cobertura obrigatória de urgência/emergência; (c) CDC art. 51 IV — cláusula de exclusão abusiva; (d) CFM proibiu a negativa para procedimentos indicados pelo médico assistente. Precedentes: STJ REsp 2.029.175 e AgRg REsp 1.900.342.`, lightContent: `A recusa de cobertura do plano de saúde é ilegal com base no CDC e na Lei dos Planos.`, omittedContent: `[fundamento legal da ilegalidade da recusa de cobertura (CDC, Lei 9.656, Tese STJ) não desenvolvido]`, omissionDescription: "ausência de desenvolvimento do fundamento legal que torna ilegal a recusa de cobertura (Tese STJ 1.03, Lei 9.656/1998 art. 10, CDC art. 51 IV)", correctPresenceKeywords: ["Tese 1.03", "Lei 9.656", "CDC art. 51"] },
    { id: "laudo_medico_plano", section: DocumentSection.DAS_PROVAS, fullContent: `Laudo do Dr. ${["Carlos Almeida", "Maria Souza", "João Costa", "Ana Lima"][h(seed.cpf + "dr3") % 4]} (CRM ${dn(seed, "crm3", 10000, 89999)}) de ${seed.baseDate}: urgência/necessidade de ${procedimento} — risco de morte sem o procedimento. Junta-se: (a) solicitação médica; (b) negativa escrita de ${r} de ${seed.derDate}; (c) orçamento hospitalar: ${fmt(danoCents)}.`, lightContent: `O laudo médico atesta a urgência e necessidade do procedimento negado pelo plano de saúde.`, omittedContent: "", omissionDescription: "ausência de laudo médico que comprove a urgência e necessidade do procedimento negado pelo plano de saúde, indispensável para a tutela", absentContent: null, correctPresenceKeywords: ["laudo", "urgência", fmt(danoCents)] },
    { id: "pedido_recursal_plano", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer o provimento do apelo para: (a) concessão de tutela para custeio de ${procedimento}; (b) multa diária de ${fmt(dn(seed, "mul3", 100000, 500000))} por descumprimento (CPC art. 537); (c) condenação em dano moral de ${fmt(dn(seed, "dm3b", 1000000, 5000000))} (CDC art. 6.º VI); (d) honorários recursais.`, lightContent: `Requer o provimento do recurso para obrigar o plano a custear o procedimento urgente.`, omittedContent: `[pedido recursal de cobertura sem identificação do procedimento e da multa por descumprimento]`, omissionDescription: "pedido recursal de cobertura de plano de saúde sem identificação do procedimento, do valor da multa por descumprimento e do dano moral", correctPresenceKeywords: [procedimento, "CPC art. 537", "CDC art. 6.º"] },
  ];
}

// ─── CONS-004: PRODUTO_DEFEITUOSO (MODERATE) ─────────────────────────────────
function buildProdutoDefeituoso(seed: CaseSeedData): DocumentElement[] {
  const f = fornecedor(seed);
  const produtoCents = dn(seed, "prd4", 100000, 500000);
  const danoCents = dn(seed, "dm4", 300000, 1500000);
  const produto = ["aparelho de televisão 55\"", "refrigerador duplex 460L", "smartphone de última geração", "notebook i7"][h(seed.cpf + "prod4") % 4];
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE INDENIZAÇÃO — PRODUTO DEFEITUOSO (CDC ART. 12)\n\nem face de ${f.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, f] },
    { id: "fatos_produto", section: DocumentSection.DOS_FATOS, fullContent: `Em ${seed.baseDate}, o(a) autor(a) adquiriu ${produto} de ${f} pelo valor de ${fmt(produtoCents)} (nota fiscal n.º ${dn(seed, "nf4", 10000, 99999)}). Desde a entrega, em ${seed.derDate}, o produto apresenta defeito grave: ${["não liga após 7 dias de uso", "tela com manchas permanentes desde o unboxing", "motor com barulho excessivo e superaquecimento", "bateria que não carrega acima de 30%"][h(seed.cpf + "def4") % 4]}. O(A) autor(a) tentou solução no SAC em ${dn(seed, "nco4", 3, 5)} oportunidades sem êxito.`, lightContent: `O produto adquirido pelo autor apresenta defeito grave e o fornecedor se recusa a solucionar o problema.`, omittedContent: `[data da compra, produto, defeito apresentado e tentativas de solução extrajudicial não identificados]`, omissionDescription: "ausência de identificação da data da compra, do produto adquirido, do defeito apresentado e das tentativas de solução extrajudicial no SAC do fornecedor", correctPresenceKeywords: [seed.baseDate, fmt(produtoCents), produto] },
    { id: "laudo_produto", section: DocumentSection.DAS_PROVAS, fullContent: `Laudo técnico elaborado pelo perito ${["Eng. Paulo Ramos", "Tec. Rafael Oliveira", "Eng. Sandra Moura"][h(seed.cpf + "per4") % 3]} (CREA ${dn(seed, "crea4", 10000, 89999)}) em ${seed.derDate}: defeito de fabricação no ${["display", "motor", "chip de processamento", "conjunto de baterias"][h(seed.cpf + "comp4") % 4]}, vício oculto (CDC art. 26 §3.º), sem responsabilidade do consumidor. Valor de reparo ou substituição: ${fmt(produtoCents)}.`, lightContent: `Laudo técnico atesta que o defeito do produto é de fabricação, sem responsabilidade do consumidor.`, omittedContent: `[laudo técnico comprobatório do defeito de fabricação do produto não juntado aos autos]`, omissionDescription: "ausência de juntada de laudo técnico comprobatório do defeito de fabricação do produto, indispensável para responsabilização do fornecedor (CDC art. 12)", correctPresenceKeywords: ["laudo técnico", "defeito de fabricação", fmt(produtoCents)] },
    { id: "direito_produto", section: DocumentSection.DO_DIREITO, fullContent: `O CDC art. 12 impõe responsabilidade objetiva do fabricante por produtos defeituosos. O CDC art. 18 prevê: substituição, devolução do valor ou abatimento proporcional. O prazo para reclamar (CDC art. 26 II) é de 90 dias para vício aparente e 5 anos para vício oculto (CDC art. 27). O STJ, no REsp 1.613.334/SP, consagrou a responsabilidade solidária de todos os fornecedores da cadeia.`, lightContent: `O fornecedor tem responsabilidade objetiva pelo produto defeituoso conforme CDC art. 12.`, omittedContent: `[responsabilidade objetiva do fornecedor, prazo de reclamação e solidariedade da cadeia não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento da responsabilidade objetiva do fornecedor (CDC art. 12), do prazo de reclamação (CDC art. 26) e da solidariedade da cadeia de fornecimento", correctPresenceKeywords: ["CDC art. 12", "CDC art. 18", "REsp 1.613.334"] },
    { id: "pedidos_produto", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) substituição do produto por novo de mesma espécie (CDC art. 18 I) ou devolução de ${fmt(produtoCents)}; (b) indenização por dano moral de ${fmt(danoCents)} (CDC art. 6.º VI); (c) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer substituição do produto defeituoso e indenização por dano moral.`, omittedContent: `[pedido de substituição ou devolução do produto sem valor e fundamento legal]`, omissionDescription: "pedido de responsabilização por produto defeituoso sem identificação do valor do produto, do dano moral e do fundamento legal (CDC arts. 12 e 18)", correctPresenceKeywords: [fmt(produtoCents), fmt(danoCents), "CDC art. 18"] },
  ];
}

// ─── CONS-005: COBRANA_INDEVIDA (GOOD) ───────────────────────────────────────
function buildCobrancaIndevida(seed: CaseSeedData): DocumentElement[] {
  const r = reu(seed);
  const cobrancaCents = dn(seed, "cb5", 50000, 500000);
  const danoCents = dn(seed, "dm5", 300000, 1500000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, apresenta\n\nRECURSO DE APELAÇÃO\n\nem face de sentença que negou pedido de devolução em dobro por cobrança indevida\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, r] },
    { id: "decisao_recorrida_cobranca", section: DocumentSection.DOS_FATOS, fullContent: `A sentença condenou ${r} à devolução simples de ${fmt(cobrancaCents)}, negando a devolução em dobro (CDC art. 42 §único) por entender não demonstrada a má-fé do fornecedor. O recorrente demonstra que: a cobrança de ${fmt(cobrancaCents)} era manifestamente indevida desde ${seed.baseDate}, pois o serviço foi cancelado em ${seed.derDate}, mas os débitos continuaram por ${dn(seed, "mes5", 3, 10)} meses.`, lightContent: `A sentença deferiu apenas devolução simples, negando a devolução em dobro por ausência de má-fé provada.`, omittedContent: `[sentença recorrida, valor cobrado indevidamente e período de cobrança indevida não identificados]`, omissionDescription: "ausência de identificação da sentença recorrida, do valor cobrado indevidamente e do período de cobrança indevida após o cancelamento do serviço", correctPresenceKeywords: [seed.baseDate, fmt(cobrancaCents), seed.derDate] },
    { id: "razoes_cobranca", section: DocumentSection.DO_DIREITO, fullContent: `O CDC art. 42 §único é expresso: quem paga o indevido tem direito à devolução em dobro, salvo engano justificável. O STJ, no REsp 1.424.304/SP (Tema 1.057), fixou que a devolução em dobro prescinde de demonstração de má-fé, bastando a cobrança indevida. O valor devido é ${fmt(cobrancaCents * 2)} (dobro de ${fmt(cobrancaCents)}) + dano moral de ${fmt(danoCents)}.`, lightContent: `O CDC art. 42 §único assegura devolução em dobro da cobrança indevida.`, omittedContent: `[fundamento legal da devolução em dobro (CDC art. 42) e tese do STJ não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal da devolução em dobro da cobrança indevida (CDC art. 42 §único e REsp 1.424.304/SP do STJ)", correctPresenceKeywords: ["CDC art. 42", "REsp 1.424.304", fmt(cobrancaCents * 2)] },
    { id: "prova_pagamento", section: DocumentSection.DAS_PROVAS, fullContent: `Comprovam a cobrança indevida: (a) contrato de cancelamento do serviço assinado em ${seed.derDate}; (b) extratos bancários com ${dn(seed, "mes5", 3, 10)} débitos indevidos totalizando ${fmt(cobrancaCents)}; (c) notificação extrajudicial ao fornecedor em ${seed.baseDate} sem resposta; (d) comprovante de quitação de toda a dívida anterior ao cancelamento.`, lightContent: `A cobrança indevida e o pagamento das parcelas serão comprovados por extratos bancários e contratos.`, omittedContent: `[extratos comprobatórios da cobrança indevida após cancelamento não juntados]`, omissionDescription: "ausência de juntada dos extratos bancários comprobatórios da cobrança indevida após o cancelamento do serviço e da notificação extrajudicial", correctPresenceKeywords: [seed.derDate, fmt(cobrancaCents), "notificação extrajudicial"] },
    { id: "pedido_recursal_cobranca", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer o provimento do apelo para: (a) condenação em devolução em dobro de ${fmt(cobrancaCents * 2)} (CDC art. 42 §único); (b) manutenção da condenação em dano moral de ${fmt(danoCents)}; (c) honorários recursais (CPC art. 85 §11).`, lightContent: `Requer a reforma da sentença para condenar o fornecedor à devolução em dobro.`, omittedContent: `[pedido recursal de devolução em dobro sem valor e fundamento legal especificados]`, omissionDescription: "pedido recursal de devolução em dobro da cobrança indevida sem identificação do valor (dobro) e do fundamento legal (CDC art. 42 §único)", correctPresenceKeywords: [fmt(cobrancaCents * 2), "CDC art. 42", "CPC art. 85"] },
  ];
}

// ─── CONS-006: RESCISAO_CONTRATO_CONSUMIDOR (MODERATE) ───────────────────────
function buildRescisaoContrato(seed: CaseSeedData): DocumentElement[] {
  const r = fornecedor(seed);
  const valorCents = dn(seed, "rv6", 200000, 2000000);
  const multaCents = dn(seed, "rm6", 50000, 300000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE RESCISÃO CONTRATUAL C/C INDENIZAÇÃO (RELAÇÃO DE CONSUMO)\n\nem face de ${r.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, r] },
    { id: "fatos_contrato", section: DocumentSection.DOS_FATOS, fullContent: `Em ${seed.baseDate}, o(a) autor(a) celebrou com ${r} contrato de ${["prestação de serviço de streaming", "curso online de idiomas", "plano de saúde odontológico", "software de gestão empresarial"][h(seed.cpf + "cont6") % 4]} pelo valor de ${fmt(valorCents)}. O fornecedor descumpriu as obrigações desde ${seed.derDate}, negando o serviço contratado sem qualquer justificativa, descumprindo o CDC art. 35 III.`, lightContent: `O fornecedor descumpriu o contrato de serviço firmado com o consumidor.`, omittedContent: `[data do contrato, serviço contratado, valor pago e descumprimento pelo fornecedor não identificados]`, omissionDescription: "ausência de identificação da data do contrato, do serviço contratado, do valor pago e das condutas concretas de descumprimento pelo fornecedor", correctPresenceKeywords: [seed.baseDate, fmt(valorCents), seed.derDate] },
    { id: "motivacao_rescisao", section: DocumentSection.DOS_FATOS, fullContent: `O(A) autor(a) notificou ${r} em ${seed.derDate} (protocolo ${dn(seed, "prot6", 100000, 899999)}) para cumprir ou resolver o contrato. Decorrido o prazo de ${dn(seed, "prazo6", 10, 30)} dias sem manifestação do réu, o consumidor exerce o direito de rescisão por inadimplemento (CC art. 475; CDC art. 35 III), com direito à devolução integral de ${fmt(valorCents)} e à multa contratual de ${fmt(multaCents)}.`, lightContent: `O consumidor notificou o fornecedor para resolver o contrato e não obteve resposta.`, omittedContent: `[notificação extrajudicial, prazo concedido ao fornecedor e exercício do direito de rescisão não identificados]`, omissionDescription: "ausência de identificação da notificação extrajudicial ao fornecedor, do prazo concedido e do exercício formal do direito de rescisão por inadimplemento (CC art. 475; CDC art. 35 III)", correctPresenceKeywords: [seed.derDate, fmt(valorCents), fmt(multaCents)] },
    { id: "direito_rescisao", section: DocumentSection.DO_DIREITO, fullContent: `O CDC art. 35 III assegura ao consumidor, quando o fornecedor não cumpre a oferta, o direito de rescindir o contrato com devolução integral do valor pago. O CC art. 475 autoriza a resolução por inadimplemento. A multa contratual (CC art. 413) é exigível no valor de ${fmt(multaCents)}. Dano moral in re ipsa: ${fmt(dn(seed, "dm6", 300000, 1500000))}.`, lightContent: `O CDC e o CC autorizam a rescisão do contrato por inadimplemento do fornecedor com devolução integral.`, omittedContent: `[fundamento legal da rescisão por inadimplemento e valor da multa contratual não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal da rescisão por inadimplemento (CDC art. 35 III e CC art. 475) e do valor da multa contratual exigível", correctPresenceKeywords: ["CDC art. 35", "CC art. 475", fmt(multaCents)] },
    { id: "pedidos_rescisao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) rescisão do contrato por inadimplemento do fornecedor (CDC art. 35 III; CC art. 475); (b) devolução de ${fmt(valorCents)}; (c) multa contratual de ${fmt(multaCents)}; (d) dano moral; (e) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a rescisão do contrato com devolução do valor pago e aplicação da multa contratual.`, omittedContent: `[pedido de rescisão sem valor a devolver, multa contratual e fundamento legal]`, omissionDescription: "pedido de rescisão contratual sem identificação do valor a devolver, da multa contratual e do fundamento legal (CDC art. 35 III)", correctPresenceKeywords: [fmt(valorCents), fmt(multaCents), "CDC art. 35"] },
  ];
}

// ─── CONS-007: OVERBOOKING (LIGHT) ───────────────────────────────────────────
function buildOverbooking(seed: CaseSeedData): DocumentElement[] {
  const companhia = ["TAM Linhas Aéreas", "GOL Linhas Aéreas", "Azul Linhas Aéreas", "LATAM Brasil"][h(seed.cpf + "cia7") % 4];
  const danoCents = dn(seed, "dm7", 500000, 2000000);
  const voo = `${["LA", "G3", "AD", "JJ"][h(seed.cpf + "iata7") % 4]}${dn(seed, "voo7", 1000, 8999)}`;
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE INDENIZAÇÃO — OVERBOOKING E CANCELAMENTO DE VOO\n\nem face de ${companhia.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, companhia] },
    { id: "fatos_overbooking", section: DocumentSection.DOS_FATOS, fullContent: `Em ${seed.baseDate}, o(a) autor(a) adquiriu bilhete do voo ${voo} operado por ${companhia}, com partida de ${seed.city} às ${dn(seed, "hora7", 6, 18)}h${["00", "15", "30", "45"][h(seed.cpf + "min7") % 4]}. Ao se apresentar no aeroporto no horário previsto, foi informado(a) de preterição de embarque por overbooking, sem qualquer justificativa técnica ou de segurança, em violação ao CDC art. 14 e à Resolução ANAC 400/2016.`, lightContent: `O autor foi impedido de embarcar no voo por prática de overbooking pela companhia aérea.`, omittedContent: `[data do voo, número do voo e prática de overbooking pela companhia aérea não identificados]`, omissionDescription: "ausência de identificação da data do voo, do número do voo e da prática de overbooking que impediu o embarque do consumidor", correctPresenceKeywords: [seed.baseDate, voo, "overbooking"] },
    { id: "prova_bilhete", section: DocumentSection.DAS_PROVAS, fullContent: `Comprovam a preterição: (a) bilhete eletrônico do voo ${voo} (e-ticket ${dn(seed, "et7", 100000000, 899999999)}); (b) cartão de embarque emitido; (c) declaração da companhia reconhecendo overbooking; (d) recibo de voucher de hotel/refeição fornecido pelo aeroporto; (e) comprovante de reagendamento para voo ${dn(seed, "nova7", 4, 28)} horas depois.`, lightContent: `O bilhete eletrônico e o cartão de embarque comprovarão o overbooking e a preterição do autor.`, omittedContent: `[bilhete eletrônico, cartão de embarque e documentos comprobatórios do overbooking não especificados]`, omissionDescription: "ausência de especificação dos documentos comprobatórios do overbooking (bilhete eletrônico, cartão de embarque, declaração da companhia)", correctPresenceKeywords: [voo, "e-ticket", "cartão de embarque"] },
    { id: "direito_overbooking", section: DocumentSection.DO_DIREITO, fullContent: `A Resolução ANAC 400/2016 art. 23 obriga a companhia a oferecer reacomodação imediata ou reembolso integral. O CDC arts. 6.º e 14 impõem responsabilidade objetiva. O dano moral in re ipsa decorre do próprio overbooking (STJ AgRg REsp 1.550.285/RJ). A companhia é solidariamente responsável com a operadora (CDC art. 7.º §único). Dano moral: ${fmt(danoCents)}.`, lightContent: `A companhia aérea tem responsabilidade objetiva pelo overbooking conforme ANAC e CDC.`, omittedContent: `[fundamento legal do overbooking (ANAC 400/2016, CDC) e valor do dano moral não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal do overbooking (Res. ANAC 400/2016, CDC arts. 6.º e 14) e do valor do dano moral in re ipsa", correctPresenceKeywords: ["ANAC 400/2016", "CDC art. 14", fmt(danoCents)] },
    { id: "pedidos_overbooking", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) indenização por dano moral de ${fmt(danoCents)} (CDC art. 14; Res. ANAC 400/2016); (b) dano material: hospedagem ${fmt(dn(seed, "hosp7", 20000, 80000))} + refeições ${fmt(dn(seed, "ref7", 5000, 20000))}; (c) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer indenização por dano moral e dano material decorrente do overbooking.`, omittedContent: `[pedido de indenização por overbooking sem valores e fundamento legal]`, omissionDescription: "pedido de indenização por overbooking sem identificação dos valores de dano moral e material e do fundamento legal (CDC art. 14 e Res. ANAC 400/2016)", correctPresenceKeywords: [fmt(danoCents), "CDC art. 14", "ANAC"] },
  ];
}

// ─── CONS-008: FURTO_CELULAR_BANCO (MODERATE) ────────────────────────────────
function buildFurtoCelularBanco(seed: CaseSeedData): DocumentElement[] {
  const banco = ["Banco Itaú S.A.", "Bradesco S.A.", "Santander Brasil S.A.", "Nubank Pagamentos S.A."][h(seed.cpf + "banco8") % 4];
  const furtoCents = dn(seed, "ft8", 500000, 5000000);
  const juros = 1 + dn(seed, "jur8", 1, 8) / 100;
  const totalCents = Math.round(furtoCents * juros);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, apresenta\n\nCUMPRIMENTO DE SENTENÇA — INDENIZAÇÃO POR FURTO DE CELULAR COM FRAUDE BANCÁRIA\n\nem face de ${banco.toUpperCase()}\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, banco] },
    { id: "titulo_furto", section: DocumentSection.DOS_FATOS, fullContent: `A sentença transitada em julgado em ${seed.baseDate} condenou ${banco} ao pagamento de ${fmt(furtoCents)} ao autor, em razão de fraude bancária praticada após furto de celular em ${seed.derDate}, na qual terceiro efetuou transações PIX não autorizadas no valor de ${fmt(furtoCents)}, com responsabilidade objetiva do banco (STJ REsp 1.884.778/SP; Tema 1.068).`, lightContent: `A sentença condenou o banco ao pagamento de indenização pela fraude bancária após furto de celular.`, omittedContent: `[título executivo, valor condenado e data da sentença não identificados]`, omissionDescription: "ausência de identificação do título executivo, do valor condenado pela sentença e da data do trânsito em julgado", correctPresenceKeywords: [seed.baseDate, fmt(furtoCents), "REsp 1.884.778"] },
    { id: "parametros_furto", section: DocumentSection.DO_DIREITO, fullContent: `A execução segue o rito do CPC art. 523. O STJ Tema 1.068 (REsp 1.884.778/SP) consagrou a responsabilidade objetiva dos bancos por fraudes em transações eletrônicas, ainda que mediante furto do aparelho. O crédito é atualizado pelo IPCA-E + juros de 1%/mês desde o evento (${seed.derDate}).`, lightContent: `A execução segue o CPC e o crédito é atualizado com IPCA-E e juros de 1%/mês.`, omittedContent: `[rito da execução, índice de atualização e juros aplicáveis não identificados]`, omissionDescription: "ausência de identificação do rito da execução (CPC art. 523), do índice de atualização (IPCA-E) e dos juros aplicáveis ao crédito condenado", correctPresenceKeywords: ["CPC art. 523", "IPCA-E", "Tema 1.068"] },
    { id: "memoria_calculo_furto", section: DocumentSection.DAS_PROVAS, fullContent: `Memória de cálculo atualizada até ${seed.baseDate}: Principal: ${fmt(furtoCents)} | Atualização IPCA-E: ${fmt(Math.round(furtoCents * 0.03))} | Juros: ${fmt(Math.round(furtoCents * 0.05))} | Total: ${fmt(totalCents)}. Planilha de cálculo elaborada pelo contador ${["João Pereira", "Maria Santos", "Carlos Lima"][h(seed.cpf + "cnt8") % 3]} (CRC ${dn(seed, "crc8", 10000, 89999)}).`, lightContent: `A memória de cálculo atualizada com IPCA-E e juros está elaborada até a data de execução.`, omittedContent: `[memória de cálculo atualizada com IPCA-E e juros não apresentada na inicial executiva]`, omissionDescription: "ausência de juntada da memória de cálculo atualizada com o índice IPCA-E e juros de mora, indispensável para a execução (CPC art. 524)", correctPresenceKeywords: [fmt(totalCents), fmt(furtoCents), "IPCA-E"] },
    { id: "pedidos_furto_exec", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) intimação de ${banco} para pagar ${fmt(totalCents)} em 15 dias (CPC art. 523); (b) em caso de não pagamento, expedição de penhora on-line (BACENJUD); (c) multa de 10% e honorários de 10% (CPC art. 523 §1.º).`, lightContent: `Requer o pagamento do crédito executado com penhora on-line em caso de inadimplemento.`, omittedContent: `[pedido executivo sem valor atualizado, prazo e sanção por inadimplemento]`, omissionDescription: "pedido executivo sem identificação do valor total atualizado, do prazo legal de pagamento e da sanção por inadimplemento (multa e honorários CPC art. 523 §1.º)", correctPresenceKeywords: [fmt(totalCents), "CPC art. 523", "BACENJUD"] },
  ];
}

// ─── CONS-009: SERVICO_DEFEITUOSO (LIGHT) ────────────────────────────────────
function buildServicoDef(seed: CaseSeedData): DocumentElement[] {
  const r = fornecedor(seed);
  const servicoCents = dn(seed, "sv9", 100000, 500000);
  const danoCents = dn(seed, "dm9", 200000, 1000000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE INDENIZAÇÃO — SERVIÇO DEFEITUOSO (CDC ART. 14)\n\nem face de ${r.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, r] },
    { id: "fatos_servico", section: DocumentSection.DOS_FATOS, fullContent: `Em ${seed.baseDate}, o(a) autor(a) contratou de ${r} o serviço de ${["instalação de ar condicionado", "reforma de banheiro", "pintura de apartamento", "instalação de sistema de câmeras"][h(seed.cpf + "serv9") % 4]} pelo valor de ${fmt(servicoCents)}. O serviço foi prestado de forma defeituosa em ${seed.derDate}: ${["vazamento após instalação", "pintura com bolhas em toda a superfície", "câmeras sem sinal após 48h", "ar condicionado com gás vazando"][h(seed.cpf + "def9") % 4]}, causando danos materiais e morais.`, lightContent: `O serviço contratado foi prestado de forma defeituosa pelo fornecedor réu.`, omittedContent: `[data da contratação, serviço prestado, defeito apresentado e danos causados não identificados]`, omissionDescription: "ausência de identificação da data da contratação, do serviço prestado, do defeito apresentado e dos danos materiais e morais causados ao consumidor", correctPresenceKeywords: [seed.baseDate, fmt(servicoCents), seed.derDate] },
    { id: "prova_servico_defeito", section: DocumentSection.DAS_PROVAS, fullContent: `Comprovam o defeito: (a) laudo técnico do PROCON de ${seed.city} em ${seed.derDate}; (b) fotografias do defeito com geolocalização e timestamp; (c) orçamento de ${dn(seed, "orc9", 1, 3)} empresas para correção, totalizando ${fmt(Math.round(servicoCents * 1.3))}; (d) prints do chat do SAC de ${r} admitindo o defeito.`, lightContent: `O defeito do serviço será comprovado por laudo técnico e fotografias.`, omittedContent: `[laudo técnico e documentos comprobatórios do defeito do serviço não especificados ou não juntados]`, omissionDescription: "ausência de especificação dos documentos comprobatórios do defeito do serviço (laudo técnico PROCON, fotografias, orçamentos de correção)", correctPresenceKeywords: ["PROCON", seed.derDate, fmt(Math.round(servicoCents * 1.3))] },
    { id: "direito_servico", section: DocumentSection.DO_DIREITO, fullContent: `O CDC art. 14 impõe responsabilidade objetiva do fornecedor por serviço defeituoso. O CDC art. 20 prevê: reexecução do serviço, restituição do valor ou abatimento proporcional. O prazo de reclamação é de 90 dias (CDC art. 26 II). O dano moral in re ipsa resulta da frustração do consumidor com o serviço defeituoso. Dano moral pretendido: ${fmt(danoCents)}.`, lightContent: `O fornecedor tem responsabilidade objetiva pelo serviço defeituoso conforme CDC art. 14.`, omittedContent: `[responsabilidade objetiva por serviço defeituoso (CDC art. 14) e opções do consumidor (CDC art. 20) não desenvolvidas]`, omissionDescription: "ausência de desenvolvimento da responsabilidade objetiva por serviço defeituoso (CDC art. 14) e das opções do consumidor para remediar o vício (CDC art. 20)", correctPresenceKeywords: ["CDC art. 14", "CDC art. 20", fmt(danoCents)] },
    { id: "pedidos_servico", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) reexecução do serviço ou devolução de ${fmt(servicoCents)} (CDC art. 20); (b) dano material de ${fmt(Math.round(servicoCents * 0.3))} (correção adicional); (c) dano moral de ${fmt(danoCents)} (CDC art. 14); (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer reexecução ou devolução do serviço defeituoso e indenização por dano moral.`, omittedContent: `[pedido por serviço defeituoso sem valor do serviço, dano material e moral]`, omissionDescription: "pedido por serviço defeituoso sem identificação do valor do serviço, do dano material de correção e do dano moral pretendido", correctPresenceKeywords: [fmt(servicoCents), fmt(danoCents), "CDC art. 20"] },
  ];
}

// ─── CONS-010: PRATICA_ABUSIVA (MODERATE) ────────────────────────────────────
function buildPraticaAbusiva(seed: CaseSeedData): DocumentElement[] {
  const r = reu(seed);
  const danoCents = dn(seed, "dm10", 500000, 2000000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DECLARATÓRIA DE NULIDADE DE CLÁUSULA ABUSIVA C/C DANO MORAL\n\nem face de ${r.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, r] },
    { id: "fatos_abusiva", section: DocumentSection.DOS_FATOS, fullContent: `O(A) autor(a) celebrou com ${r} contrato de adesão em ${seed.baseDate}. O contrato contém cláusula ${["de renovação automática sem notificação prévia", "de cobrança de taxa de fidelidade sem prestação equivalente", "de limitação de indenização a valor irrisório", "de foro exclusivo em cidade distante do consumidor"][h(seed.cpf + "cl10") % 4]} que viola o CDC art. 51. Referida cláusula foi aplicada causando prejuízo de ${fmt(dn(seed, "prej10", 100000, 500000))} ao consumidor.`, lightContent: `O contrato de adesão contém cláusula abusiva que causou prejuízo ao autor.`, omittedContent: `[cláusula abusiva específica do contrato, data da aplicação e prejuízo causado não identificados]`, omissionDescription: "ausência de identificação da cláusula abusiva específica do contrato, da data de aplicação e do prejuízo concreto causado ao consumidor", correctPresenceKeywords: [seed.baseDate, "CDC art. 51", r] },
    { id: "clausula_abusiva", section: DocumentSection.DOS_FATOS, fullContent: `A cláusula ${dn(seed, "ncl10", 5, 20)} do contrato de ${seed.baseDate} é nula de pleno direito (CDC art. 51 IV e XV): (a) viola o equilíbrio contratual; (b) é excessivamente onerosa para o consumidor; (c) não foi informada com destaque ao aderir ao contrato (CDC art. 54 §4.º); (d) restringe direitos do consumidor (CDC art. 51 I). Transcrição da cláusula: "[${["renovação automática sem aviso prévio de 30 dias", "multa rescisória de 100% do saldo devedor", "limitação de cobertura a 50% do valor do bem", "foro exclusivo da sede do fornecedor"][h(seed.cpf + "trans10") % 4]}]".`, lightContent: `A cláusula abusiva do contrato de adesão é nula de pleno direito conforme CDC art. 51.`, omittedContent: `[identificação e transcrição da cláusula abusiva com o número da cláusula e texto não apresentados]`, omissionDescription: "ausência de identificação e transcrição da cláusula abusiva com número da cláusula, texto e análise do porquê é nula (CDC art. 51 IV e XV)", correctPresenceKeywords: [seed.baseDate, "CDC art. 51", "CDC art. 54"] },
    { id: "direito_abusiva", section: DocumentSection.DO_DIREITO, fullContent: `O CDC art. 51 elenca as cláusulas nulas de pleno direito em contratos de consumo. A nulidade é declarada de ofício (STJ REsp 1.200.705/RS). O dano moral resulta da aplicação da cláusula abusiva: ${fmt(danoCents)} (CDC art. 6.º VI). O PROCON pode instaurar procedimento sancionatório (CDC art. 56).`, lightContent: `O CDC art. 51 declara nulas as cláusulas abusivas e garante indenização por dano moral.`, omittedContent: `[fundamento legal da nulidade (CDC art. 51), dano moral e sanção administrativa não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal da nulidade das cláusulas abusivas (CDC art. 51), do dano moral e da possibilidade de sanção administrativa pelo PROCON", correctPresenceKeywords: ["CDC art. 51", "REsp 1.200.705", fmt(danoCents)] },
    { id: "pedidos_abusiva", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) declaração de nulidade da cláusula (CDC art. 51); (b) devolução do valor indevidamente cobrado; (c) dano moral de ${fmt(danoCents)}; (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a declaração de nulidade da cláusula abusiva e indenização por dano moral.`, omittedContent: `[pedido de nulidade da cláusula sem identificação da cláusula e dos valores]`, omissionDescription: "pedido de nulidade de cláusula abusiva sem identificação da cláusula, do valor indevidamente cobrado e do dano moral pretendido", correctPresenceKeywords: [fmt(danoCents), "CDC art. 51", "devolução"] },
  ];
}

// ─── CONS-011: EXTRAVIO_BAGAGEM (GOOD) ───────────────────────────────────────
function buildExtravioMala(seed: CaseSeedData): DocumentElement[] {
  const companhia = ["TAM Linhas Aéreas", "GOL Linhas Aéreas", "Azul Linhas Aéreas", "LATAM Brasil"][h(seed.cpf + "cia11") % 4];
  const bagagemCents = dn(seed, "bag11", 200000, 1500000);
  const danoCents = dn(seed, "dm11", 500000, 2000000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE INDENIZAÇÃO — EXTRAVIO DE BAGAGEM\n\nem face de ${companhia.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, companhia] },
    { id: "fatos_extravio", section: DocumentSection.DOS_FATOS, fullContent: `Em ${seed.baseDate}, o(a) autor(a) embarcou no voo ${["LA", "G3", "AD", "JJ"][h(seed.cpf + "voo11") % 4]}${dn(seed, "nvoo11", 1000, 8999)} operado por ${companhia}, com destino a ${["São Paulo", "Rio de Janeiro", "Brasília", "Fortaleza"][h(seed.cpf + "dst11") % 4]}. Ao chegar ao destino, em ${seed.derDate}, constatou o extravio total de sua bagagem despachada (${dn(seed, "vol11", 1, 3)} volume(s)), contendo bens avaliados em ${fmt(bagagemCents)}. Registro de ocorrência n.º ${dn(seed, "rrr11", 10000, 89999)} feito no aeroporto.`, lightContent: `A bagagem do autor foi extraviada pela companhia aérea durante o transporte.`, omittedContent: `[data do voo, destino, volume extraviado e valor dos bens não identificados]`, omissionDescription: "ausência de identificação da data do voo, do destino, do volume extraviado e do valor dos bens contidos na bagagem extraviada", correctPresenceKeywords: [seed.baseDate, fmt(bagagemCents), seed.derDate] },
    { id: "prova_extravio", section: DocumentSection.DAS_PROVAS, fullContent: `Comprovam o extravio: (a) registro de ocorrência n.º ${dn(seed, "rrr11", 10000, 89999)} emitido pela companhia no aeroporto; (b) relação de bens extraviados com notas fiscais totalizando ${fmt(bagagemCents)}; (c) comprovante de despacho da bagagem (tag ${dn(seed, "tag11", 1000000, 8999999)}); (d) resposta de ${companhia} negando indenização além do limite tarifário.`, lightContent: `O extravio da bagagem será comprovado por registro de ocorrência e comprovante de despacho.`, omittedContent: `[registro de ocorrência, notas fiscais dos bens extraviados e resposta da companhia não especificados]`, omissionDescription: "ausência de especificação dos documentos comprobatórios do extravio (registro de ocorrência, relação de bens com notas fiscais, comprovante de despacho)", correctPresenceKeywords: [fmt(bagagemCents), "tag", "registro de ocorrência"] },
    { id: "direito_extravio", section: DocumentSection.DO_DIREITO, fullContent: `O STJ Tema 210 (REsp 1.289.629/SP) e o CDC art. 14 consagram a responsabilidade objetiva da companhia aérea pelo extravio de bagagem. A Convenção de Montreal (Decreto 5.910/2006) limita a indenização, mas o CDC prevalece nas relações domésticas (STF RE 636.331/RJ). Dano moral in re ipsa: ${fmt(danoCents)} (STJ AgRg REsp 1.550.285/RJ). Dano material: ${fmt(bagagemCents)}.`, lightContent: `A companhia aérea tem responsabilidade objetiva pelo extravio de bagagem conforme CDC e STJ.`, omittedContent: `[responsabilidade objetiva pelo extravio, prevalência do CDC e valores dos danos não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento da responsabilidade objetiva pelo extravio (CDC art. 14), da prevalência do CDC sobre a Convenção de Montreal e dos valores dos danos", correctPresenceKeywords: ["Tema 210", "CDC art. 14", fmt(danoCents)] },
    { id: "pedidos_extravio", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) indenização por dano material de ${fmt(bagagemCents)} (CDC art. 14; Tema 210 STJ); (b) dano moral de ${fmt(danoCents)}; (c) honorários (CPC art. 85). Valor da causa: ${seed.causeValue}.`, lightContent: `Requer indenização por dano material e moral pelo extravio de bagagem.`, omittedContent: `[pedido de indenização por extravio sem valores e fundamento legal especificados]`, omissionDescription: "pedido de indenização por extravio de bagagem sem identificação do valor do dano material e moral e do fundamento legal (CDC art. 14 e Tema 210 STJ)", correctPresenceKeywords: [fmt(bagagemCents), fmt(danoCents), "Tema 210"] },
  ];
}

// ─── CONS-012: PUBLICIDADE_ENGANOSA (LIGHT) ──────────────────────────────────
function buildPublicidadeEnganosa(seed: CaseSeedData): DocumentElement[] {
  const r = fornecedor(seed);
  const danoCents = dn(seed, "dm12", 300000, 1500000);
  const precoAnunciado = dn(seed, "pa12", 100000, 500000);
  const preco_cobrado = precoAnunciado + dn(seed, "pc12", 50000, 200000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, apresenta\n\nRECURSO DE APELAÇÃO\n\nem face de sentença que negou pretensão de publicidade enganosa\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, r] },
    { id: "decisao_recorrida_pub", section: DocumentSection.DOS_FATOS, fullContent: `A sentença recorrida negou o pedido por entender que a divergência entre o preço anunciado (${fmt(precoAnunciado)}) e o efetivamente cobrado (${fmt(preco_cobrado)}) seria "mero erro material" insuficiente para configurar publicidade enganosa. O recorrente demonstra que: (a) a divergência é de ${fmt(preco_cobrado - precoAnunciado)} (${Math.round((preco_cobrado - precoAnunciado) / precoAnunciado * 100)}%); (b) a oferta vincula o fornecedor (CDC art. 30).`, lightContent: `A sentença negou o pedido por entender que a divergência de preço seria mero erro material.`, omittedContent: `[sentença recorrida, preço anunciado, preço cobrado e diferença percentual não identificados]`, omissionDescription: "ausência de identificação da sentença recorrida, do preço anunciado, do preço efetivamente cobrado e da divergência percentual que configura publicidade enganosa", correctPresenceKeywords: [fmt(precoAnunciado), fmt(preco_cobrado), "CDC art. 30"] },
    { id: "prova_publicidade", section: DocumentSection.DAS_PROVAS, fullContent: `Comprovam a publicidade enganosa: (a) printscreen do anúncio com preço ${fmt(precoAnunciado)} de ${seed.baseDate} (hash verificável MD5 ${dn(seed, "md512", 10000000, 89999999)}); (b) nota fiscal emitida pelo réu em ${seed.derDate} com cobrança de ${fmt(preco_cobrado)}; (c) print do e-mail de confirmação com preço divergente; (d) comprovante de pagamento no valor cobrado.`, lightContent: `A publicidade enganosa será comprovada por printscreen do anúncio e nota fiscal da cobrança.`, omittedContent: `[printscreen do anúncio enganoso e comprovantes da cobrança divergente não juntados]`, omissionDescription: "ausência de juntada do printscreen do anúncio enganoso com data e da nota fiscal com o preço efetivamente cobrado, essenciais para comprovar a publicidade enganosa", correctPresenceKeywords: [fmt(precoAnunciado), fmt(preco_cobrado), seed.baseDate] },
    { id: "fundamento_pub", section: DocumentSection.DO_DIREITO, fullContent: `O CDC art. 30 vincula o fornecedor à oferta veiculada; o CDC art. 35 I assegura ao consumidor o cumprimento da oferta pelo preço anunciado. A divergência de ${Math.round((preco_cobrado - precoAnunciado) / precoAnunciado * 100)}% configura publicidade enganosa (CDC art. 37 §1.º). O CONAR reconhece o princípio da veracidade publicitária. Dano moral: ${fmt(danoCents)}.`, lightContent: `O CDC arts. 30 e 37 asseguram ao consumidor o direito ao preço anunciado na publicidade.`, omittedContent: `[fundamento legal da publicidade enganosa (CDC arts. 30 e 37) e percentual de divergência não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal da publicidade enganosa (CDC arts. 30 e 37 §1.º) e do percentual de divergência que caracteriza a enganosidade", correctPresenceKeywords: ["CDC art. 30", "CDC art. 37", fmt(danoCents)] },
    { id: "pedido_recursal_pub", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer o provimento do apelo para: (a) condenação ao cumprimento da oferta pelo preço anunciado de ${fmt(precoAnunciado)} ou devolução da diferença (${fmt(preco_cobrado - precoAnunciado)}) (CDC art. 35 I); (b) dano moral de ${fmt(danoCents)} (CDC art. 6.º VI); (c) honorários recursais.`, lightContent: `Requer a condenação ao cumprimento da oferta pelo preço anunciado.`, omittedContent: `[pedido recursal de publicidade enganosa sem valor do preço anunciado e diferença a devolver]`, omissionDescription: "pedido recursal de publicidade enganosa sem identificação do preço anunciado, da diferença a devolver e do fundamento legal (CDC art. 35 I)", correctPresenceKeywords: [fmt(precoAnunciado), fmt(preco_cobrado - precoAnunciado), "CDC art. 35"] },
  ];
}

// ─── CONS-013: CONTRATO_BANCARIO_ABUSIVO (GOOD) ──────────────────────────────
function buildContratoBancario(seed: CaseSeedData): DocumentElement[] {
  const banco = "Banco Itaú S.A.";
  const taxaAnual = dn(seed, "ta13", 30, 150);
  const saldoCents = dn(seed, "sld13", 500000, 5000000);
  const excessoCents = Math.round(saldoCents * 0.3);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO REVISIONAL DE CONTRATO BANCÁRIO C/C REPETIÇÃO DE INDÉBITO\n\nem face de ${banco.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, banco] },
    { id: "fatos_bancario", section: DocumentSection.DOS_FATOS, fullContent: `Em ${seed.baseDate}, o(a) autor(a) celebrou com ${banco} contrato de crédito pessoal n.º ${dn(seed, "cred13", 100000, 899999)} no valor de ${fmt(saldoCents)}, com taxa de juros de ${taxaAnual}% a.a. — muito acima da taxa média do mercado divulgada pelo BACEN para o período (${dn(seed, "med13", 15, 35)}% a.a.). O banco aplicou encargos abusivos que geraram saldo devedor artificialmente inflacionado de ${fmt(excessoCents)}.`, lightContent: `O banco celebrou contrato de crédito com taxa de juros muito acima da média de mercado.`, omittedContent: `[taxa de juros do contrato, taxa média BACEN e saldo devedor excedente não identificados]`, omissionDescription: "ausência de identificação da taxa de juros contratada, da taxa média de mercado divulgada pelo BACEN e do saldo devedor artificialmente inflacionado", correctPresenceKeywords: [seed.baseDate, fmt(saldoCents), String(taxaAnual)] },
    { id: "clausula_bancaria", section: DocumentSection.DAS_PROVAS, fullContent: `Comprovam a abusividade: (a) contrato de crédito n.º ${dn(seed, "cred13", 100000, 899999)} com taxa de ${taxaAnual}% a.a.; (b) planilha comparativa com taxa BACEN (${dn(seed, "med13", 15, 35)}% a.a.); (c) laudo de perito contábil (CRC ${dn(seed, "crc13", 10000, 89999)}) calculando excesso de encargos cobrados: ${fmt(excessoCents)}; (d) extratos do período ${seed.baseDate} a ${seed.derDate}.`, lightContent: `O contrato bancário e o laudo contábil comprovarão as taxas abusivas e o excesso de cobrança.`, omittedContent: `[contrato bancário, laudo contábil comparativo com taxa BACEN e excesso de encargos não juntados]`, omissionDescription: "ausência de juntada do contrato bancário, do laudo contábil comparativo com a taxa BACEN e do cálculo do excesso de encargos cobrados", correctPresenceKeywords: [String(taxaAnual), fmt(excessoCents), "BACEN"] },
    { id: "direito_bancario", section: DocumentSection.DO_DIREITO, fullContent: `O STJ Súmula 296 permite a revisão de juros abusivos em contratos bancários quando há onerosidade excessiva. O STJ Tema 27 (REsp 1.061.530/RS) consolidou: juros acima da média BACEN são presumidamente abusivos. A repetição de indébito (CC art. 876; CDC art. 42 §único) assegura a devolução em dobro do excesso cobrado: ${fmt(excessoCents * 2)}.`, lightContent: `O STJ admite revisão de juros abusivos em contratos bancários com repetição de indébito em dobro.`, omittedContent: `[revisão de juros abusivos (Súmula 296 STJ, Tema 27) e direito à repetição em dobro não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento da possibilidade de revisão dos juros abusivos (Súmula 296 e Tema 27 do STJ) e do direito à repetição de indébito em dobro", correctPresenceKeywords: ["Súmula 296", "Tema 27", fmt(excessoCents * 2)] },
    { id: "pedidos_bancario", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) revisão dos juros contratuais para a taxa média BACEN (${dn(seed, "med13", 15, 35)}% a.a.) (STJ Tema 27); (b) repetição de indébito em dobro do excesso: ${fmt(excessoCents * 2)} (CDC art. 42 §único); (c) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a revisão dos juros abusivos e a repetição em dobro do excesso cobrado.`, omittedContent: `[pedido revisional sem taxa pretendida, valor a restituir e fundamento legal]`, omissionDescription: "pedido revisional de contrato bancário sem identificação da taxa pretendida, do valor a restituir e do fundamento legal (Súmula 296 e Tema 27 do STJ)", correctPresenceKeywords: [fmt(excessoCents * 2), "Tema 27", "CDC art. 42"] },
  ];
}

// ─── CONS-014: VICIO_CONSTRUCAO (MODERATE) ───────────────────────────────────
function buildVicioConstrucao(seed: CaseSeedData): DocumentElement[] {
  const r = "Construtora Alpha Ltda.";
  const imovelCents = dn(seed, "im14", 10000000, 80000000);
  const reparoCents = dn(seed, "rep14", 500000, 3000000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE INDENIZAÇÃO POR VÍCIOS DE CONSTRUÇÃO\n\nem face de ${r.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, r] },
    { id: "fatos_vicio", section: DocumentSection.DOS_FATOS, fullContent: `O(A) autor(a) adquiriu imóvel construído por ${r} em ${seed.baseDate} pelo valor de ${fmt(imovelCents)} (matrícula ${dn(seed, "mat14", 10000, 89999)} CRI ${seed.city}). Após a entrega em ${seed.derDate}, verificou vícios de construção graves: ${["infiltrações em toda a laje", "fissuras estruturais nas paredes de carga", "recalque diferencial das fundações", "impermeabilização defeituosa da cobertura"][h(seed.cpf + "vic14") % 4]}. O prazo de garantia da NBR 5.674 ainda está em curso.`, lightContent: `O imóvel construído pelo réu apresenta vícios graves de construção após a entrega.`, omittedContent: `[data da aquisição, vício apresentado, data de descoberta e prazo de garantia não identificados]`, omissionDescription: "ausência de identificação da data de aquisição do imóvel, dos vícios de construção apresentados, da data de descoberta e do prazo de garantia aplicável", correctPresenceKeywords: [seed.baseDate, fmt(imovelCents), seed.derDate] },
    { id: "laudo_vicio_construcao", section: DocumentSection.DAS_PROVAS, fullContent: `Laudo de inspeção predial do Eng. ${["Ricardo Moura", "Paulo Costa", "Sandra Alves"][h(seed.cpf + "eng14") % 3]} (CREA ${dn(seed, "crea14", 10000, 89999)}) de ${seed.derDate}: vício de construção grave — defeito oculto (CC art. 441; CDC art. 26 §3.º) na ${["estrutura", "impermeabilização", "fundação", "cobertura"][h(seed.cpf + "comp14") % 4]}, responsabilidade da construtora. Orçamento de reparo: ${fmt(reparoCents)}.`, lightContent: `Laudo de inspeção predial atesta o vício de construção e quantifica o reparo.`, omittedContent: `[laudo de inspeção predial comprobatório dos vícios de construção não juntado aos autos]`, omissionDescription: "ausência de juntada do laudo de inspeção predial comprobatório dos vícios de construção, indispensável para a responsabilização da construtora (CC art. 618)", correctPresenceKeywords: ["laudo de inspeção", fmt(reparoCents), "CREA"] },
    { id: "direito_vicio", section: DocumentSection.DO_DIREITO, fullContent: `O CC art. 618 garante 5 anos de garantia para solidez e segurança da obra. O CDC art. 26 §3.º prevê prazo decadencial de 90 dias para vícios ocultos, contado do conhecimento do defeito. A construtora responde objetivamente (CDC art. 14) pelos vícios de construção. O STJ, no REsp 1.608.573/SP, consolidou que o prazo do CC art. 618 e do CDC se somam quando favoráveis ao consumidor.`, lightContent: `A construtora tem responsabilidade objetiva pelos vícios de construção conforme CC art. 618 e CDC.`, omittedContent: `[prazo de garantia da construção (CC art. 618), responsabilidade objetiva (CDC art. 14) e precedente do STJ não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do prazo de garantia da obra (CC art. 618), da responsabilidade objetiva da construtora (CDC art. 14) e do precedente do STJ que amplia a proteção do consumidor", correctPresenceKeywords: ["CC art. 618", "CDC art. 14", "REsp 1.608.573"] },
    { id: "pedidos_vicio", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) condenação em reparos do imóvel pelo custo de ${fmt(reparoCents)} (CDC art. 20 II); (b) alternativamente, abatimento proporcional do preço; (c) dano moral de ${fmt(dn(seed, "dm14", 300000, 1500000))}; (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer reparo dos vícios de construção ou abatimento proporcional do preço.`, omittedContent: `[pedido de reparos ou abatimento por vícios sem valor do reparo e fundamento legal]`, omissionDescription: "pedido de reparos por vícios de construção sem identificação do valor do reparo, da alternativa de abatimento e do fundamento legal (CDC art. 20 II e CC art. 618)", correctPresenceKeywords: [fmt(reparoCents), "CDC art. 20", "CC art. 618"] },
  ];
}

// ─── CONS-015: CUMPRIMENTO_CONSUMIDOR (GOOD) ─────────────────────────────────
function buildCumprimentoConsumidor(seed: CaseSeedData): DocumentElement[] {
  const r = reu(seed);
  const principalCents = dn(seed, "pr15", 500000, 5000000);
  const meses = dn(seed, "ms15", 3, 18);
  const totalCents = Math.round(principalCents * (1 + meses * 0.01));
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, apresenta\n\nCUMPRIMENTO DE SENTENÇA — INDENIZAÇÃO EM RELAÇÃO DE CONSUMO\n\nem face de ${r.toUpperCase()}\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, r] },
    { id: "titulo_consumidor", section: DocumentSection.DOS_FATOS, fullContent: `A sentença transitada em julgado em ${seed.baseDate} condenou ${r} ao pagamento de ${fmt(principalCents)} ao(à) autor(a), a título de indenização por dano moral e material em relação de consumo (CDC arts. 6.º VI e 14). O executado está inadimplente desde ${seed.derDate}, decorridos ${meses} meses do prazo de pagamento voluntário.`, lightContent: `A sentença condenou o fornecedor ao pagamento de indenização por dano em relação de consumo.`, omittedContent: `[título executivo, valor condenado e data do inadimplemento não identificados]`, omissionDescription: "ausência de identificação do título executivo, do valor condenado pela sentença e da data de início do inadimplemento", correctPresenceKeywords: [seed.baseDate, fmt(principalCents), seed.derDate] },
    { id: "parametros_consumidor", section: DocumentSection.DO_DIREITO, fullContent: `A execução segue o rito do CPC art. 523. O crédito é atualizado pelo IPCA-E + juros de 1%/mês (STJ REsp 1.492.221/PR) desde ${seed.derDate}. O CDC art. 6.º VI assegura reparação efetiva dos danos. O inadimplemento no prazo do CPC art. 523 §1.º enseja acréscimo de multa de 10% e honorários de 10%.`, lightContent: `A execução segue o CPC art. 523, com correção por IPCA-E e juros de 1%/mês.`, omittedContent: `[rito da execução, índice de correção e consequências do inadimplemento não identificados]`, omissionDescription: "ausência de identificação do rito da execução (CPC art. 523), do índice de correção monetária (IPCA-E) e das consequências do inadimplemento no prazo legal", correctPresenceKeywords: ["CPC art. 523", "IPCA-E", "CDC art. 6.º"] },
    { id: "memoria_calculo_consumidor", section: DocumentSection.DAS_PROVAS, fullContent: `Memória de cálculo atualizada até ${seed.baseDate}:\nPrincipal condenado: ${fmt(principalCents)}\nCorreção IPCA-E (${meses} meses): ${fmt(Math.round(principalCents * meses * 0.005))}\nJuros de mora (${meses} × 1%): ${fmt(Math.round(principalCents * meses * 0.01))}\nTotal atualizado: ${fmt(totalCents)}\nMulta CPC art. 523 §1.º (10%): ${fmt(Math.round(totalCents * 0.1))}\nHonorários (10%): ${fmt(Math.round(totalCents * 0.1))}\nTotal geral: ${fmt(Math.round(totalCents * 1.2))}`, lightContent: `A memória de cálculo atualizada com IPCA-E e juros de mora está elaborada.`, omittedContent: `[memória de cálculo atualizada com principal, correção, juros, multa e honorários não apresentada]`, omissionDescription: "ausência de memória de cálculo atualizada com discriminação do principal, da correção monetária (IPCA-E), dos juros de mora, da multa e dos honorários executivos", correctPresenceKeywords: [fmt(totalCents), fmt(principalCents), "IPCA-E"] },
    { id: "pedidos_consumidor_exec", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) intimação de ${r} para pagar ${fmt(Math.round(totalCents * 1.2))} em 15 dias (CPC art. 523); (b) em caso de inadimplemento, penhora on-line via SISBAJUD; (c) multa de 10% e honorários de 10% sobre o valor atualizado (CPC art. 523 §1.º).`, lightContent: `Requer o pagamento do crédito executado com penhora on-line em caso de inadimplemento.`, omittedContent: `[pedido executivo sem valor total, prazo e multa por inadimplemento]`, omissionDescription: "pedido executivo sem identificação do valor total atualizado, do prazo legal e da multa de 10% por inadimplemento (CPC art. 523 §1.º)", correctPresenceKeywords: [fmt(Math.round(totalCents * 1.2)), "CPC art. 523", "SISBAJUD"] },
  ];
}

// ─── Dispatch ─────────────────────────────────────────────────────────────────

export function buildConsumidorElements(
  config: ConsumidorScenarioConfig,
  seed: CaseSeedData,
): DocumentElement[] {
  switch (config.issueType) {
    case "DANO_MORAL_CONSUMIDOR":        return buildDanoMoralConsumidor(seed);
    case "NEGATIVACAO_INDEVIDA":         return buildNegativacaoIndevida(seed);
    case "RECUSA_COBERTURA_PLANO":       return buildRecusaCobertura(seed);
    case "PRODUTO_DEFEITUOSO":           return buildProdutoDefeituoso(seed);
    case "COBRANA_INDEVIDA":             return buildCobrancaIndevida(seed);
    case "RESCISAO_CONTRATO_CONSUMIDOR": return buildRescisaoContrato(seed);
    case "OVERBOOKING":                  return buildOverbooking(seed);
    case "FURTO_CELULAR_BANCO":          return buildFurtoCelularBanco(seed);
    case "SERVICO_DEFEITUOSO":           return buildServicoDef(seed);
    case "PRATICA_ABUSIVA":              return buildPraticaAbusiva(seed);
    case "EXTRAVIO_BAGAGEM":             return buildExtravioMala(seed);
    case "PUBLICIDADE_ENGANOSA":         return buildPublicidadeEnganosa(seed);
    case "CONTRATO_BANCARIO_ABUSIVO":    return buildContratoBancario(seed);
    case "VICIO_CONSTRUCAO":             return buildVicioConstrucao(seed);
    case "CUMPRIMENTO_CONSUMIDOR":       return buildCumprimentoConsumidor(seed);
    default:
      throw new Error(`Builder não encontrado para issueType: ${(config as { issueType: string }).issueType}`);
  }
}
