import type { DomainKnowledgePack } from "../domain-knowledge.types.js";

export const ambientalKnowledgePack: DomainKnowledgePack = {
  domain: "AMBIENTAL",
  label: "Direito Ambiental",
  description: "Licenciamento ambiental, infrações administrativas ambientais, responsabilidade civil ambiental e ações coletivas.",
  reviewerGoals: [
    "Demonstrar a regularidade ambiental do empreendimento ou da conduta com documentação da licença",
    "Contestar a infração ambiental com base na ausência de dano efetivo ou na regularidade da licença",
    "Demonstrar a responsabilidade objetiva do degradador e o nexo causal com o dano ambiental",
    "Identificar o passivo ambiental e o custo de recuperação com base em laudo técnico",
    "Apresentar o plano de recuperação como fundamento da tese de reparação adequada",
    "Antecipar as defesas sobre licenças, impacto mínimo e proporcionalidade da sanção",
    "Verificar a prescrição administrativa ambiental (art. 21 do Decreto 6.514/2008 — 3 anos)",
    "Identificar a responsabilidade solidária do proprietário atual por degradação anterior",
  ],
  commonDocuments: [
    "Licença Ambiental (LP, LI, LO, LAS, LAU) e condicionantes",
    "Auto de Infração Ambiental (AIA)",
    "Laudo técnico ambiental",
    "Estudo de Impacto Ambiental (EIA) e Relatório de Impacto (RIMA)",
    "Plano de Controle Ambiental (PCA)",
    "Plano de Recuperação de Área Degradada (PRAD)",
    "Relatório de monitoramento ambiental",
    "Certidão de cadastro ambiental (CAR — Cadastro Ambiental Rural)",
    "Outorga de uso de recursos hídricos (quando aplicável)",
    "Pareceres técnicos do órgão ambiental (IBAMA, SEMA, CETESB, órgão estadual)",
    "Fotografias e imagens de satélite (evidência de degradação ou de regularidade)",
    "Relatório de auditoria ambiental",
  ],
  commonProofs: [
    "Laudos técnicos de peritos especializados em meio ambiente",
    "Imagens de satélite comparativas (antes e depois da suposta degradação)",
    "Relatórios de monitoramento com dados de qualidade do ar, água e solo",
    "Documentos de licença e regularidade ambiental para o período",
    "Laudos de avaliação de dano ambiental com quantificação",
    "Relatórios de órgãos ambientais (IBAMA, SEMA, CETESB)",
  ],
  commonWeaknesses: [
    "Ausência de laudo técnico demonstrando (ou afastando) o dano ambiental efetivo",
    "Nexo causal entre a conduta e a degradação não demonstrado com dados técnicos",
    "Regularidade da licença não comprovada para a atividade e o período específico questionado",
    "Plano de recuperação inexistente ou incompleto quando exigível para demonstrar comprometimento",
    "Extensão territorial do dano não delimitada por laudo ou imagem georreferenciada",
    "Custo de recuperação ambiental sem memória de cálculo e PRAD elaborado por técnico",
    "Ausência de análise da proporcionalidade da multa administrativa em relação ao grau da infração",
    "Prescrição administrativa ambiental não verificada (3 anos — art. 21 do Decreto 6.514/2008)",
    "Responsabilidade solidária do proprietário anterior não endereçada quando relevante",
  ],
  commonDemonstrations: [
    "Demonstração da regularidade da licença ambiental para o período questionado (com condicionantes cumpridas)",
    "Laudo técnico demonstrando a extensão, a natureza e o custo do dano ambiental",
    "Linha do tempo do licenciamento e das condicionantes cumpridas",
    "Quadro de medidas mitigatórias e compensatórias já adotadas",
    "Demonstração do custo de recuperação com base em PRAD elaborado por técnico habilitado",
    "Comparativo de impacto: previsto no EIA vs. impacto real verificado",
    "Demonstração da prescrição administrativa com os marcos do art. 21 do Decreto 6.514/2008",
  ],
  commonCalculations: [
    "Custo de recuperação ambiental (PRAD com orçamento detalhado por etapa)",
    "Multa administrativa e proporcionalidade (grau do dano × benefício econômico da infração)",
    "Valor da indenização por dano ambiental (dano emergente + lucro cessante coletivo)",
    "Área degradada em hectares e custo por hectare de recuperação",
    "Prescrição administrativa: 3 anos a partir da data do conhecimento do fato pelo órgão (art. 21 do Decreto 6.514/2008)",
  ],
  commonCounterArguments: [
    "Ausência de dano ambiental efetivo (conduta sem resultado lesivo verificável)",
    "Regularidade da atividade com base na licença vigente à época dos fatos",
    "Proporcionalidade da sanção em relação ao grau e extensão do dano causado",
    "Prescrição da pretensão punitiva administrativa (art. 21 do Decreto 6.514/2008)",
    "Responsabilidade ambiental de terceiro (degradação anterior ao proprietário atual)",
    "Medidas de mitigação já adotadas e eficazes que reduziram ou eliminaram o dano",
  ],
  strengtheningOpportunities: [
    "Juntar laudo técnico especializado demonstrando a extensão real do dano (ou sua ausência)",
    "Apresentar PRAD com cronograma e custo de recuperação como proposta concreta ao Juízo",
    "Documentar todas as licenças válidas e condicionantes cumpridas para o período",
    "Incluir imagens de satélite comparativas georreferenciadas para delimitar a área afetada",
    "Antecipar a proporcionalidade da multa com análise do grau da infração e do benefício econômico",
    "Identificar precedentes do STJ sobre responsabilidade ambiental objetiva no caso concreto",
    "Verificar e demonstrar a prescrição administrativa com os marcos do art. 21 do Decreto 6.514/2008",
    "Endereçar expressamente a questão da responsabilidade solidária do proprietário anterior quando relevante",
  ],
  extractionHints: [
    "Licença ambiental: tipo (LP/LI/LO/LAS/LAU), número, atividade licenciada, condicionantes, validade",
    "Auto de infração: infração tipificada, área afetada, multa aplicada, data, órgão autuante",
    "Laudo ambiental: metodologia, parâmetros analisados, área georreferenciada, conclusões, autoria técnica",
    "CAR: código do imóvel, módulos fiscais, reserva legal cadastrada, área total",
    "PRAD: área a recuperar, espécies, cronograma, custo total, responsável técnico",
  ],
  cautionaryNotes: [
    "A responsabilidade ambiental é objetiva (STJ, Súmula 623) mas exige nexo causal demonstrado — a mera propriedade do imóvel não implica automaticamente responsabilidade por toda degradação identificada",
    "Medidas mitigatórias já adotadas podem reduzir o valor da indenização mas não afastam a responsabilidade pelo dano residual — não presuma que PRAD encerrado extingue a obrigação de indenizar",
    "A licença ambiental válida à época dos fatos pode afastar a ilicitude administrativa mas não necessariamente a responsabilidade civil — as esferas são independentes",
    "Imagens de satélite precisam ter a metodologia de análise documentada para ter valor probatório — a simples juntada de imagem sem laudo de interpretação pode ser questionada",
    "O CAR é declaratório e não constitutivo — a inscrição no CAR não regulariza situação irregular preexistente",
  ],
  placeholderGuidance: "Dados tipicamente pendentes de confirmação: [EMPREENDIMENTO/ATIVIDADE], [LICENÇA AMBIENTAL Nº], [ÁREA DEGRADADA EM HECTARES], [AGENTE DEGRADADOR], [DATA DA INFRAÇÃO], [MULTA ADMINISTRATIVA VALOR], [ÓRGÃO AMBIENTAL AUTUANTE], [CUSTO DO PRAD].",
};
