import type { DomainKnowledgePack } from "../domain-knowledge.types.js";

export const civelGeralKnowledgePack: DomainKnowledgePack = {
  domain: "CIVEL",
  label: "Cível Geral",
  description: "Ações cíveis em geral — responsabilidade civil, contratos, obrigações, indenizações e tutelas.",
  reviewerGoals: [
    "Demonstrar os fatos constitutivos do direito com documentação correspondente",
    "Demonstrar o dano, o nexo causal e a culpa ou dolo do réu",
    "Fortalecer a base contratual ou extracontratual da pretensão",
    "Apresentar o cálculo dos danos materiais e a justificativa do dano moral",
    "Antecipar preliminares e exceções previsíveis (prescrição, ilegitimidade, decadência)",
    "Documentar a inexecução contratual ou o ato ilícito com precisão",
    "Verificar a necessidade e urgência de tutela de urgência ou cautelar",
    "Identificar expressamente o prazo prescricional aplicável e demonstrar que foi observado",
  ],
  commonDocuments: [
    "Contrato e seus aditivos",
    "Notas fiscais e recibos de pagamento",
    "Laudo técnico ou pericial",
    "Orçamentos e comprovantes de despesas",
    "Comunicações formais (e-mail, carta, notificação extrajudicial)",
    "Boletim de Ocorrência",
    "Apólice de seguro (quando aplicável)",
    "Documentos de propriedade (imóveis, veículos)",
    "Prontuários médicos (responsabilidade civil médica)",
    "Extrato bancário demonstrando pagamentos e inadimplemento",
    "Ata notarial (preservação de prova digital)",
    "Notificação extrajudicial com AR demonstrando mora",
  ],
  commonProofs: [
    "Prova documental (contratos, notas fiscais, laudos)",
    "Prova testemunhal",
    "Prova pericial (dano em imóvel, laudo médico, avaliação de bens)",
    "Prova digital (prints, e-mails, mensagens com data e hora)",
    "Ata notarial (preservação de prova digital com validade probatória)",
  ],
  commonWeaknesses: [
    "Ato ilícito afirmado sem documentação do fato específico",
    "Nexo causal entre a conduta e o dano não demonstrado",
    "Dano material sem comprovação de valores com recibos ou laudos",
    "Dano moral genérico sem o fato específico causador do abalo",
    "Mora ou inadimplemento sem notificação extrajudicial prévia quando exigível",
    "Ausência de cálculo dos valores pleiteados",
    "Cláusula contratual não citada quando é o fundamento central da pretensão",
    "Prazo prescricional não identificado na petição (risco de reconhecimento de prescrição)",
    "Urgência não demonstrada quando há pedido de tutela de urgência",
    "Lucros cessantes sem demonstração dos ganhos esperados frustrados",
  ],
  commonDemonstrations: [
    "Linha do tempo do contrato ou da relação obrigacional",
    "Demonstração do inadimplemento com datas e valores",
    "Demonstração do dano material com comprovantes e laudos",
    "Demonstração do nexo causal entre a conduta e o dano",
    "Quadro de débitos e parcelas vencidas",
    "Demonstração da tentativa de resolução extrajudicial (notificação, prazo, ausência de resposta)",
    "Demonstração da urgência (periculum in mora) para tutela de urgência",
  ],
  commonCalculations: [
    "Danos materiais emergentes (gastos efetivos comprovados)",
    "Lucros cessantes (ganho esperado frustrado com base em histórico ou prova)",
    "Cláusula penal (quando contratual) com aplicação dos limites do art. 412 do CC",
    "Juros de mora (1% ao mês no CC) e correção monetária",
    "Dano moral (parâmetros jurisprudenciais do STJ para o caso concreto)",
    "Honorários periciais e despesas processuais estimadas",
  ],
  commonCounterArguments: [
    "Prescrição (art. 206 do CC — 1, 3 ou 5 anos conforme o caso)",
    "Excludentes de responsabilidade (caso fortuito, força maior, culpa da vítima, culpa de terceiro)",
    "Cumprimento parcial reduzindo o valor devido",
    "Ausência de dano ou dano não comprovado",
    "Cláusula de limitação de responsabilidade no contrato",
    "Decadência do direito potestativo (prazos do art. 178 e 179 do CC)",
    "Mora do credor (como excludente da mora do devedor)",
  ],
  strengtheningOpportunities: [
    "Apresentar linha do tempo detalhada do contrato e dos eventos relevantes",
    "Incluir notificação extrajudicial com AR e comprovante de recebimento para demonstrar mora",
    "Quantificar o dano material com recibos, laudos e orçamentos detalhados",
    "Apresentar precedentes do STJ com parâmetros de dano moral aplicáveis ao caso",
    "Identificar expressamente a cláusula contratual violada e suas consequências",
    "Antecipar as excludentes de responsabilidade com demonstração de sua inaplicabilidade",
    "Demonstrar a urgência com fatos concretos para fundamentar a tutela de urgência",
    "Calcular e mencionar expressamente o prazo prescricional aplicável e sua observância",
  ],
  extractionHints: [
    "Contrato: partes, objeto, valor, prazo, cláusula de penalidade, foro eleito",
    "Laudo técnico: dano identificado, causa, extensão, custo de reparo, data",
    "Nota fiscal: produto/serviço, valor, data, vendedor/CNPJ",
    "Extrato bancário: pagamentos realizados, inadimplemento, datas",
    "Notificação extrajudicial: data do envio, data de recebimento, objeto da notificação",
  ],
  cautionaryNotes: [
    "O prazo prescricional varia conforme o tipo de pretensão — não existe um único prazo prescricional cível; verificar o art. 206 do CC antes de mencionar qualquer prazo",
    "Lucros cessantes exigem prova do ganho esperado e da frustração — a simples afirmação de que houve prejuízo futuro sem base documental ou histórica é fragilidade real",
    "A cláusula penal substitui a indenização por perdas e danos salvo quando estipulada cumulativamente — não gere finding afirmando que são cumuláveis sem verificar a cláusula",
    "Tutela de urgência antecipada exige periculum in mora e fumus boni iuris demonstrados — a ausência de pedido de tutela pode ser estratégica (ex.: o réu já não pode desfazer o ato)",
    "Mora do credor (art. 400 do CC) exclui a mora do devedor — se o credor não aceitou o pagamento, a mora pode não estar configurada; isso é argumento do réu que pode ser antecipado",
  ],
  placeholderGuidance: "Dados tipicamente pendentes de confirmação: [PARTES DO CONTRATO], [OBJETO DO CONTRATO], [VALOR DO CONTRATO], [DATA DO INADIMPLEMENTO], [VALOR DO DANO MATERIAL], [VALOR DO DANO MORAL PLEITEADO], [PRAZO PRESCRICIONAL APLICÁVEL], [CLÁUSULA PENAL — VALOR].",
};
