import type { DomainKnowledgePack } from "../domain-knowledge.types.js";

export const consumidorKnowledgePack: DomainKnowledgePack = {
  domain: "CONSUMIDOR",
  label: "Direito do Consumidor",
  description: "Relações de consumo, responsabilidade objetiva, danos morais consumeristas, negativação indevida e práticas abusivas.",
  reviewerGoals: [
    "Demonstrar a relação de consumo e a incidência do CDC",
    "Individualizar a falha do produto ou do serviço com dados concretos",
    "Documentar o dano moral com o fato específico e os seus efeitos concretos",
    "Demonstrar o nexo causal entre a falha e o dano sofrido",
    "Documentar as tentativas de solução administrativa antes do ajuizamento",
    "Apresentar o cálculo do dano material e a justificativa do valor do dano moral",
    "Identificar cláusulas abusivas do contrato de adesão quando aplicável",
    "Verificar a aplicabilidade da devolução em dobro de cobranças indevidas (art. 42, § único do CDC)",
  ],
  commonDocuments: [
    "Contrato de prestação de serviço ou de compra e venda",
    "Nota fiscal, fatura ou recibo da transação",
    "Comprovante de pagamento",
    "Protocolo de atendimento (SAC, ouvidoria, Procon, e-mail)",
    "Prints de telas (aplicativo, site, chatbot) com data e hora visíveis",
    "E-mails e mensagens com a empresa",
    "Comprovante de negativação (Serasa, SPC, SCR) com data de inclusão",
    "Fatura com a cobrança contestada",
    "Ordem de serviço",
    "Boletim de Ocorrência (fraude ou produto falsificado)",
    "Laudo técnico do produto ou serviço defeituoso",
    "Comprovante de devolução e recusa pelo fornecedor",
    "Contrato de adesão completo (cláusulas que podem ser contestadas como abusivas)",
  ],
  commonProofs: [
    "Prints de aplicativos e sites com data/hora visíveis",
    "Protocolo de atendimento registrado com número e data",
    "E-mails com carimbo temporal",
    "Comprovante de negativação com data de inclusão e credor",
    "Laudo técnico demonstrando o defeito do produto ou serviço",
    "Testemunhos de terceiros que presenciaram o fato",
    "Ata notarial para preservação de prova digital",
  ],
  commonWeaknesses: [
    "Falha do produto ou serviço descrita genericamente sem individualização do problema",
    "Dano moral afirmado de forma genérica sem o fato específico que gerou o abalo",
    "Nexo causal entre a conduta do fornecedor e o dano não demonstrado",
    "Ausência de registros de protocolos de atendimento e reclamação administrativa",
    "Negativação indevida sem prova da ausência de débito ou do débito já quitado",
    "Ausência de prova da cobrança indevida (fatura ou extrato)",
    "Tentativa de resolução administrativa não documentada",
    "Prescrição quinquenal do CDC não analisada",
    "Cláusula abusiva identificada mas sem citação expressa do art. 51 do CDC",
  ],
  commonDemonstrations: [
    "Linha do tempo da relação de consumo (contratação — falha — reclamação — dano)",
    "Quadro de cobranças indevidas com datas e valores",
    "Demonstração da tentativa de solução extrajudicial (protocolos, prazos, respostas da empresa)",
    "Prova do dano material com notas fiscais e recibos",
    "Prova do nexo causal entre a falha e o dano sofrido",
    "Demonstração da negativação indevida com a data e o valor",
    "Identificação da cláusula abusiva com citação dos arts. 6º e 51 do CDC",
  ],
  commonCalculations: [
    "Dano material (valores pagos indevidamente + gastos derivados comprovados)",
    "Dano moral (parâmetros jurisprudenciais aplicáveis ao caso concreto)",
    "Devolução em dobro de cobrança indevida (art. 42, § único do CDC — exige má-fé)",
    "Multa contratual quando prevista",
    "Atualização monetária do indébito",
    "Prazo decadencial de vício oculto (90 dias para bens duráveis, 30 dias para não duráveis)",
  ],
  commonCounterArguments: [
    "Ausência de relação de consumo (negócio entre iguais ou B2B)",
    "Inexistência de falha — produto ou serviço entregue conforme contratado",
    "Dano moral não configurado (mero aborrecimento cotidiano sem consequências concretas)",
    "Culpa exclusiva do consumidor (uso inadequado ou contrário às instruções)",
    "Débito efetivamente existente (justificando a negativação ou cobrança)",
    "Prescrição quinquenal do CDC",
    "Devolução em dobro sem comprovação de má-fé (requisito para art. 42, § único)",
  ],
  strengtheningOpportunities: [
    "Juntar todos os protocolos de atendimento demonstrando a insistência e frustração do consumidor",
    "Incluir linha do tempo da relação de consumo com os eventos e as datas cronológicas",
    "Individualizar o fato gerador do dano moral com detalhes concretos e efeitos na vida do consumidor",
    "Apresentar precedentes do TJSP/TJRJ/STJ sobre o valor de dano moral em casos análogos",
    "Documentar o dano material com recibos e notas de cada despesa derivada do problema",
    "Antecipar a alegação de que o débito é legítimo com a prova de pagamento ou de inexistência",
    "Identificar cláusula abusiva do contrato de adesão com citação expressa do art. 51 do CDC",
    "Verificar e demonstrar a má-fé do fornecedor quando pleitear a devolução em dobro",
  ],
  extractionHints: [
    "Fatura: número, vencimento, valor original, descrição da cobrança contestada",
    "Protocolo: número, data, canal (SAC/e-mail/chat), resumo do atendimento e da resposta",
    "Negativação: órgão (Serasa/SPC), valor, data de inclusão, credor, código",
    "Nota fiscal: produto/serviço, valor, data, vendedor/CNPJ",
    "Print de tela: data e hora visíveis, conteúdo completo, plataforma",
  ],
  cautionaryNotes: [
    "Mero aborrecimento cotidiano não configura dano moral indenizável — a peça precisa descrever um fato específico com consequências concretas ao consumidor; a ausência dessa descrição é fragilidade real",
    "A devolução em dobro do art. 42, § único do CDC exige demonstração de má-fé do fornecedor — não é automática em qualquer cobrança indevida; não gere finding afirmando que a devolução é devida sem analisar o elemento subjetivo",
    "O prazo decadencial de vício do produto corre da data da entrega, não da data do conhecimento — calcule a partir do momento correto",
    "Relações B2B (empresa vs. empresa) não se submetem ao CDC salvo quando a empresa adquire como destinatária final sem expertise técnica no produto — a hipossuficiência técnica deve ser demonstrada",
    "O prazo do SAC (máximo 5 dias úteis de resposta) é regulatório e pode ser base para demonstrar descaso do fornecedor, mas a ausência de sua menção não é fragilidade automática",
  ],
  placeholderGuidance: "Dados tipicamente pendentes de confirmação: [PRODUTO/SERVIÇO], [DATA DA CONTRATAÇÃO], [DATA DA FALHA], [VALOR DO DANO MATERIAL], [VALOR DO DANO MORAL PLEITEADO], [NÚMERO DO PROTOCOLO], [DATA DA NEGATIVAÇÃO], [NÚMERO DO CONTRATO].",
};
