import type { DomainKnowledgePack } from "../domain-knowledge.types.js";

export const criminalKnowledgePack: DomainKnowledgePack = {
  domain: "CRIMINAL",
  label: "Direito Criminal",
  description: "Defesa criminal, habeas corpus, recursos, revisão criminal, absolvição, desclassificação e dosimetria.",
  reviewerGoals: [
    "Demonstrar a ausência de materialidade ou autoria quando presentes elementos que a afastem",
    "Fortalecer a tese de desclassificação para tipo penal menos grave demonstrando o elemento subjetivo ausente",
    "Documentar excludentes de ilicitude ou de culpabilidade com suporte fático detalhado",
    "Contestar a cadeia de custódia das provas quando houver falha verificável nos autos",
    "Apresentar tese de dosimetria favorável com análise individualizada das circunstâncias do art. 59 do CP",
    "Demonstrar constrangimento ilegal ou excesso de prazo quando cabível",
    "Verificar a aplicabilidade do ANPP (Acordo de Não Persecução Penal — art. 28-A do CPP)",
    "Identificar nulidades processuais absolutas e relativas com a arguição no momento oportuno",
  ],
  commonDocuments: [
    "Auto de Prisão em Flagrante (APF)",
    "Boletim de Ocorrência (BO)",
    "Laudo pericial (exame de corpo de delito, laudo necropápico, laudo toxicológico, laudo de informática)",
    "Laudo de avaliação de substância entorpecente",
    "Relatório policial (inquérito policial completo)",
    "Folha de antecedentes criminais",
    "Declaração de renda e residência fixa (para análise de prisão preventiva)",
    "Testemunhos e declarações prestadas na fase policial e judicial",
    "Mídia e gravações (quando existentes e com cadeia de custódia preservada)",
    "Registros médicos (quando houver lesão ou vítima)",
    "Comprovante de domicílio, trabalho e família (réu preso — fundamento de liberdade)",
    "Denúncia e peças processuais anteriores",
    "Certidão de antecedentes e folha corrida",
  ],
  commonProofs: [
    "Laudo de exame de corpo de delito assinado por perito oficial",
    "Filmagens e imagens que confirmem ou excluam a autoria (com cadeia de custódia preservada)",
    "Testemunhos oculares e declarações judicializadas",
    "Laudos periciais especializados (grafotécnico, computacional, de voz, toxicológico)",
    "Documentos que confirmem álibi (registros eletrônicos, transações, câmeras externas)",
    "Comunicações eletrônicas preservadas com integralidade e sem edição",
  ],
  commonWeaknesses: [
    "Ausência de exame de corpo de delito quando o crime deixa vestígios (art. 158 do CPP)",
    "Cadeia de custódia da prova não verificada ou comprometida por ruptura documentada",
    "Reconhecimento fotográfico ou pessoal realizado em desconformidade com o art. 226 do CPP",
    "Confissão isolada sem outros elementos de corroboração (confissão não é prova plena)",
    "Ausência de análise individualizada das circunstâncias judiciais do art. 59 do CP na dosimetria",
    "Tese de desclassificação sem demonstração do elemento subjetivo ausente (dolo, culpa, especial fim de agir)",
    "Excludente de ilicitude afirmada sem suporte fático detalhado e proporcional",
    "Nulidade arguida sem identificação do prejuízo concreto (pas de nullité sans grief)",
    "Prescrição não calculada para todas as fases (punitiva, retroativa, intercorrente)",
    "ANPP não verificado quando o crime e o imputado atendem aos requisitos do art. 28-A do CPP",
  ],
  commonDemonstrations: [
    "Linha do tempo dos fatos com base nos autos (denúncia, laudo, testemunhos)",
    "Análise da cadeia de custódia das provas principais (art. 158-A a 158-F do CPP)",
    "Demonstração do álibi com documentos, registros eletrônicos e testemunhas",
    "Análise individualizada das circunstâncias judiciais do art. 59 do CP",
    "Demonstração do excesso de prazo na prisão preventiva",
    "Confronto entre o depoimento das testemunhas e os fatos narrados na denúncia",
    "Demonstração dos requisitos do ANPP quando aplicável (pena mínima < 4 anos, confissão, não reincidente)",
    "Identificação e arguição de nulidade com o prejuízo concreto sofrido pela defesa",
  ],
  commonCalculations: [
    "Dosimetria da pena (3 fases: pena-base — agravantes/atenuantes — causas de aumento/diminuição)",
    "Pena-base com análise das 8 circunstâncias do art. 59 do CP (culpabilidade, antecedentes, conduta social, personalidade, motivos, circunstâncias, consequências, comportamento da vítima)",
    "Cálculo do regime de cumprimento de pena (fechado, semiaberto, aberto)",
    "Prescrição da pretensão punitiva (antes da sentença) e retroativa (após a sentença)",
    "Prazo para progressão de regime (40% ou 60% para crimes hediondos)",
    "Livramento condicional (1/3, 1/2 ou 2/3 conforme o caso)",
    "Detração penal (tempo de prisão cautelar a ser abatido da pena)",
  ],
  commonCounterArguments: [
    "Autoria demonstrada por flagrante, laudo pericial ou reconhecimento válido",
    "Inexistência de excludente — ausência de moderação ou proporcionalidade (legítima defesa)",
    "Reincidência como agravante da pena (art. 61, I do CP)",
    "Hediondez do crime como impeditivo de benefícios e progressão diferenciada",
    "Periculosidade do agente para manutenção da prisão preventiva (garantia da ordem pública)",
    "Ausência de álibi confirmado ou álibi contraditório",
    "Validade do reconhecimento pessoal (observância do art. 226 do CPP)",
  ],
  strengtheningOpportunities: [
    "Verificar e questionar detalhadamente a cadeia de custódia de cada prova relevante",
    "Apresentar análise individualizada das circunstâncias judiciais com argumentos favoráveis para cada uma",
    "Identificar precedentes do STJ/STF sobre o tema específico (nulidades, dosimetria, excludentes, ANPP)",
    "Documentar as condições pessoais favoráveis do réu (residência fixa, trabalho, família, primariedade)",
    "Confrontar a prova oral com laudos e documentos que indiquem contradição",
    "Demonstrar expressamente os elementos do tipo penal ausentes (para desclassificação)",
    "Verificar a aplicabilidade e os requisitos do ANPP (art. 28-A do CPP) quando não foi ofertado",
    "Arguir expressamente as nulidades processuais com o prejuízo concreto e o momento da arguição",
  ],
  extractionHints: [
    "APF: data, hora, local, circunstâncias do flagrante, itens apreendidos, autores da prisão",
    "Laudo pericial: tipo de laudo, conclusão, data, número do laudo, perito signatário",
    "Folha de antecedentes: condenações anteriores com trânsito em julgado, processos em curso",
    "BO: natureza da ocorrência, data, local, vítimas e suspeitos identificados, número da ocorrência",
    "Denúncia: tipo penal imputado, fatos narrados, data do fato, autoria atribuída",
  ],
  cautionaryNotes: [
    "O ANPP (art. 28-A do CPP) é ofertado pelo Ministério Público e não pela defesa — a ausência de menção ao ANPP na peça pode ser porque o MP não ofertou ou porque não é viável no caso; não gere finding presumindo omissão do advogado",
    "Prova ilícita pode ser arguida a qualquer tempo antes do trânsito em julgado — a não arguição em peça anterior não impede arguição posterior; não gere finding afirmando que o momento passou",
    "A confissão do réu não é prova absoluta e pode ser retratada — a existência de confissão nos autos não elimina a defesa de mérito; não gere finding presumindo que a confissão encerrou a questão da autoria",
    "Reconhecimento realizado em desconformidade com o art. 226 do CPP é causa de nulidade relativa ou absoluta conforme o STJ — verificar se houve arguição no momento oportuno",
    "Detração penal (art. 42 do CP) é direito do condenado e deve ser calculada — a ausência de cálculo expresso pode ser omissão relevante ou mera questão de execução penal a tratar depois",
    "Hediondez pode ser afastada se a qualificadora determinante não está provada — não presuma que o crime é hediondo sem verificar o tipo penal e as qualificadoras provadas",
  ],
  placeholderGuidance: "Dados tipicamente pendentes de confirmação: [TIPO PENAL IMPUTADO], [DATA DO FATO], [PENA MÍNIMA/MÁXIMA], [PENA-BASE FIXADA], [REGIME DE CUMPRIMENTO], [DATA DO FLAGRANTE], [NÚMERO DO PROCESSO], [NOME DO RÉU], [ANTECEDENTES CRIMINAIS].",
};
