import type { DomainKnowledgePack } from "../domain-knowledge.types.js";

export const familiaKnowledgePack: DomainKnowledgePack = {
  domain: "FAMILIA",
  label: "Direito de Família",
  description: "Alimentos, guarda, divórcio, partilha, inventário, adoção e demais questões de família.",
  reviewerGoals: [
    "Demonstrar a necessidade do alimentando com despesas discriminadas e rotina documentada",
    "Demonstrar a possibilidade econômica do alimentante com renda e patrimônio (formal e informal)",
    "Fortalecer a narrativa dos fatos com a rotina e o histórico familiar documentado",
    "Documentar o vínculo afetivo ou a dependência econômica quando relevante",
    "Apresentar proposta de guarda e convivência fundamentada no melhor interesse da criança",
    "Antecipar a contestação sobre capacidade financeira e necessidade",
    "Demonstrar episódios de alienação parental com documentação e testemunhos",
    "Identificar bens comuns e o regime de bens para fundamentar a partilha",
  ],
  commonDocuments: [
    "Certidão de nascimento dos filhos",
    "Certidão de casamento ou de união estável",
    "Comprovante de renda do alimentante (holerites, declaração de IR, extrato bancário)",
    "Comprovante de renda do alimentando ou do guardião",
    "Comprovante de despesas (escola, saúde, moradia, alimentação, lazer)",
    "Comprovante de matrícula e mensalidade escolar",
    "Notas fiscais e recibos médicos, odontológicos e terapêuticos",
    "Mensagens e e-mails demonstrando descumprimento de acordos ou alienação parental",
    "Boletim de Ocorrência (violência doméstica ou alienação parental)",
    "Laudo psicossocial ou estudo de caso do CREAS",
    "Escritura de união estável ou separação consensual anterior",
    "IRPF com declaração de dependentes e patrimônio declarado",
    "Escritura de imóveis e documentos de veículos (partilha)",
    "Extrato de investimentos e aplicações financeiras (partilha)",
  ],
  commonProofs: [
    "Extratos bancários demonstrando renda e despesas",
    "Testemunhos de familiares e vizinhos sobre rotina e convivência",
    "Laudo psicológico e psicossocial",
    "Prints de mensagens demonstrando descumprimento de acordos ou episódios de alienação parental",
    "Fotos e vídeos da rotina do menor",
    "Declaração de IRPF do alimentante (patrimônio e renda declarados)",
    "Certidão de matrícula de imóveis e documentos de veículos",
  ],
  commonWeaknesses: [
    "Necessidade do alimentando descrita de forma genérica sem discriminação de despesas",
    "Possibilidade do alimentante não demonstrada com renda real (inclui renda informal e patrimônio)",
    "Ausência de rotina documentada da criança (escola, atividades, saúde)",
    "Ausência de discriminação das despesas mensais com valores e comprovantes",
    "Fatos sobre a convivência e o relacionamento familiar sem base documental",
    "Guarda compartilhada ou unilateral sem fundamentação no melhor interesse da criança",
    "Alienação parental sem documentação dos episódios específicos",
    "Partilha sem identificação do regime de bens e dos bens comuns",
    "Renda informal do alimentante não explorada (atividade autônoma, aluguel, negócios)",
    "Violência doméstica sem contextualização das medidas protetivas em vigor",
  ],
  commonDemonstrations: [
    "Quadro de despesas mensais discriminadas por categoria (moradia, saúde, educação, alimentação, lazer)",
    "Rotina documentada da criança (escola, atividades extracurriculares, consultas médicas)",
    "Linha do tempo dos fatos familiares relevantes (casamento/união, separação, incidentes, medidas judiciais)",
    "Demonstração do vínculo afetivo e da convivência",
    "Demonstração da capacidade econômica do alimentante (renda formal + informal + patrimônio)",
    "Quadro de convivência proposta (quando há disputa de guarda)",
    "Relação de bens comuns com avaliação e fundamentação no regime de bens",
  ],
  commonCalculations: [
    "Binômio necessidade-possibilidade com valores documentados",
    "Proposta de alimentos em salários mínimos ou valor fixo",
    "Atualização de alimentos fixados em data anterior (revisional)",
    "Partilha de bens do regime de comunhão com avaliação dos bens",
    "Meação do patrimônio adquirido na constância da união",
    "Alimentos gravídicos: estimativa de despesas da gestação",
  ],
  commonCounterArguments: [
    "Capacidade do guardião de suprir as necessidades sem alimentos",
    "Renda do alimentante insuficiente para o valor pleiteado",
    "Filhos maiores e capazes sem necessidade comprovada (exoneração de alimentos)",
    "Guarda compartilhada que diluiria a necessidade de alimentos fixos",
    "Alienação parental pelo guardião como argumento de revisão de guarda",
    "Separação de fato e inexistência de patrimônio comum a partilhar",
    "Bem excluído da comunhão por ser anterior ao casamento ou herança",
  ],
  strengtheningOpportunities: [
    "Apresentar quadro de despesas mensais com notas fiscais e recibos organizados por categoria",
    "Incluir demonstrativo comparativo de renda do alimentante (holerites + IR + patrimônio + renda informal)",
    "Documentar a rotina da criança com horários, escola e atividades extracurriculares",
    "Apresentar laudo ou relatório psicossocial para sustentar a guarda pretendida",
    "Antecipar a contestação de que a criança tem necessidades menores com comprovantes específicos",
    "Juntar prints de mensagens demonstrando descumprimento de visitas ou acordos anteriores",
    "Identificar e documentar renda informal do alimentante (atividade autônoma, aluguéis, participações)",
    "Verificar medidas protetivas da Lei Maria da Penha em vigor e sua relevância para a guarda",
  ],
  extractionHints: [
    "Certidão de nascimento: nome do filho, data de nascimento, filiação",
    "Holerite do alimentante: salário base, descontos, líquido recebido, empresa",
    "Comprovante de despesa: valor, data, estabelecimento, natureza (saúde/educação/moradia)",
    "IRPF: renda bruta, bens declarados, dependentes, renda de aluguéis",
    "Escritura de imóvel: localização, área, data de aquisição, valor declarado",
  ],
  cautionaryNotes: [
    "Alimentos gravídicos são devidos desde a concepção e têm rito próprio — não confundir com alimentos definitivos; a ausência de pedido de alimentos gravídicos na inicial pode ser estratégica",
    "Guarda compartilhada é a regra no direito brasileiro atual — a ausência de pedido expresso pela modalidade não é fragilidade; a peça pode ter fundamentação adequada ainda assim",
    "Renda informal do alimentante é prova difícil de produzir; a ausência de documentação não significa que não há renda informal, e o advogado pode estar aguardando depoimento",
    "O regime de separação de bens não implica ausência de partilha em toda situação — há hipóteses de comunhão parcial de fato reconhecidas judicialmente; não gere finding presumindo que separação = sem partilha",
    "Violência doméstica com medida protetiva em vigor pode afetar o regime de guarda e visitas — a não menção não é necessariamente omissão relevante se os autos já tratam disso separadamente",
  ],
  placeholderGuidance: "Dados tipicamente pendentes de confirmação: [NOME DOS FILHOS], [IDADES], [VALOR DOS ALIMENTOS PLEITEADOS], [RENDA DO ALIMENTANTE], [TOTAL DE DESPESAS MENSAIS], [REGIME DE BENS], [RELAÇÃO DE BENS COMUNS], [DATA DA SEPARAÇÃO DE FATO].",
};
