import type { DomainKnowledgePack } from "../domain-knowledge.types.js";

export const fazendaPublicaKnowledgePack: DomainKnowledgePack = {
  domain: "FAZENDA_PUBLICA",
  label: "Fazenda Pública",
  description: "Ações contra o Estado — indenizações, responsabilidade civil do Estado, precatórios, mandados de segurança e atos administrativos.",
  reviewerGoals: [
    "Demonstrar a ilegalidade ou abusividade do ato administrativo com o fundamento normativo violado",
    "Fundamentar a responsabilidade objetiva ou subjetiva do Estado com os elementos configuradores",
    "Demonstrar o nexo causal entre a conduta estatal (comissiva ou omissiva) e o dano sofrido",
    "Apresentar cálculo dos valores devidos com juros e correção específicos de precatórios",
    "Antecipar as defesas processuais típicas da Fazenda (prescrição, ilegitimidade, reexame necessário)",
    "Identificar a via adequada (ação ordinária, mandado de segurança, ação popular)",
    "Verificar o prazo prescricional aplicável (Decreto 20.910/32 ou regras especiais)",
    "Identificar a pessoa jurídica de direito público responsável e sua competência jurisdicional",
  ],
  commonDocuments: [
    "Ato administrativo impugnado (portaria, decreto, resolução, ofício, despacho)",
    "Processo administrativo que gerou o ato impugnado",
    "Certidões e documentos funcionais (servidores)",
    "Contratos administrativos e aditivos",
    "Laudos e perícias relacionados ao dano",
    "Comprovantes de dano (material e moral)",
    "Boletim de Ocorrência (danos por agente público ou omissão estatal)",
    "Laudos médicos e prontuários (responsabilidade civil por omissão na saúde pública)",
    "Ata de sessão pública ou de julgamento administrativo",
    "Decisão do TCU ou TCE quando aplicável",
    "Edital de licitação e ata de julgamento (contratos administrativos)",
  ],
  commonProofs: [
    "Documentos oficiais demonstrando a conduta estatal comissiva ou omissiva",
    "Laudos periciais de dano (técnico, médico, engenharia)",
    "Testemunhos de servidores e terceiros",
    "Registros de câmeras públicas",
    "Prontuários e registros médicos (falha em serviço de saúde pública)",
    "Relatórios de controle interno ou órgãos fiscalizadores (CGU, TCU, TCE)",
  ],
  commonWeaknesses: [
    "Nexo causal entre o ato administrativo e o dano não demonstrado com evidências concretas",
    "Responsabilidade objetiva afirmada sem identificação da conduta e do dano específico",
    "Ausência de prova do dano material específico com documentação",
    "Prescrição quinquenal não analisada (Decreto 20.910/32 ou regra específica aplicável)",
    "Ilegitimidade passiva não antecipada (ente federal, estadual ou municipal)",
    "Ausência de esgotamento da via administrativa quando exigida (mandado de segurança)",
    "Cálculo sem observar a regra específica de juros contra a Fazenda (EC 113/2021)",
    "Pessoa jurídica demandada incorreta (União vs. ente estadual vs. autarquia)",
    "Ato discricionário confundido com ato vinculado — distinção não abordada",
  ],
  commonDemonstrations: [
    "Linha do tempo do ato administrativo e seus efeitos concretos no patrimônio ou na pessoa do autor",
    "Demonstração do nexo causal entre conduta estatal e dano (comissão ou omissão)",
    "Quadro comparativo entre o ato praticado e a legalidade esperada (fundamento normativo violado)",
    "Demonstração do dano material com documentação e valores",
    "Identificação da pessoa jurídica de direito público responsável e sua competência jurisdicional",
    "Demonstração do esgotamento administrativo quando necessário",
    "Análise da proporcionalidade e razoabilidade do ato administrativo questionado",
  ],
  commonCalculations: [
    "Atualização monetária (IPCA-E para precatórios após EC 113/2021)",
    "Juros de mora (SELIC para precatórios pós-EC 113/2021)",
    "Prescrição quinquenal (marcos: ato lesivo — conhecimento — ajuizamento)",
    "Honorários advocatícios (art. 85 do CPC e regras do § 3º para Fazenda)",
    "Valor do dano moral com parâmetros jurisprudenciais aplicados ao Estado",
    "Juros de mora anteriores à EC 113/2021 (art. 1º-F da Lei 9.494/97 — TR)",
  ],
  commonCounterArguments: [
    "Prescrição quinquenal consumada (Decreto 20.910/32)",
    "Ausência de nexo causal ou causa excludente (caso fortuito, fato de terceiro, culpa da vítima)",
    "Ato discricionário insuscetível de revisão judicial (mérito administrativo)",
    "Ilegitimidade passiva da pessoa jurídica demandada",
    "Ausência de dano ou dano não comprovado",
    "Necessidade de esgotamento da via administrativa (mandado de segurança)",
    "Responsabilidade da autarquia/fundação e não do ente político",
  ],
  strengtheningOpportunities: [
    "Identificar precisamente o ente responsável e o regime jurídico aplicável",
    "Incluir linha do tempo do ato e de seus efeitos concretos no patrimônio do autor",
    "Apresentar cálculo específico com os índices de correção e juros aplicáveis à Fazenda pós-EC 113/2021",
    "Antecipar a preliminar de prescrição com os marcos interruptivos (protocolo administrativo, notificação)",
    "Identificar precedentes do STJ/TRFs sobre o tema específico",
    "Demonstrar expressamente a ilegalidade do ato com o fundamento normativo violado",
    "Verificar se o ato é vinculado ou discricionário e adequar a tese à natureza do ato",
    "Antecipar a questão da ilegitimidade passiva identificando o ente correto",
  ],
  extractionHints: [
    "Ato administrativo: número, data, autoridade subscritora, fundamento legal, efeitos e destinatário",
    "Contrato administrativo: número, objeto, valor total, prazo, aditivos e CNPJ da contratada",
    "Prontuário médico: data do atendimento, diagnóstico, conduta adotada, intercorrências, alta",
    "Laudo pericial: tipo, data, conclusão, nexo causal atestado, valor do dano",
    "Decisão do TCU/TCE: número do acórdão, data, determinações, condenações",
  ],
  cautionaryNotes: [
    "A responsabilidade civil do Estado por atos omissivos exige demonstração de omissão específica e não genérica — a omissão do Estado de forma ampla não configura responsabilidade objetiva automaticamente",
    "Atos discricionários não podem ser revisados pelo Poder Judiciário quanto ao mérito, apenas quanto à legalidade — não gere finding afirmando que o Judiciário pode determinar a escolha administrativa",
    "O reexame necessário (duplo grau obrigatório) beneficia a Fazenda e pode reverter a decisão favorável ao autor — a menção a esse risco pode ser estratégica na peça, não é fragilidade automática",
    "EC 113/2021 unificou os índices de atualização e juros em precatórios pela SELIC — aplicação retroativa é questão controvertida que deve ser tratada no caso concreto",
    "Prescrição quinquenal do Decreto 20.910/32 corre a partir do conhecimento do dano, não necessariamente do ato — verifique o marco inicial antes de afirmar que não há prescrição",
  ],
  placeholderGuidance: "Dados tipicamente pendentes de confirmação: [ENTE FEDERATIVO RÉTICOLO], [ATO ADMINISTRATIVO Nº], [DATA DO ATO], [DATA DO CONHECIMENTO DO DANO], [VALOR DO DANO MATERIAL], [VALOR DO DANO MORAL PLEITEADO], [ÍNDICE DE ATUALIZAÇÃO APLICÁVEL], [NOME DO AGENTE PÚBLICO].",
};
