import type { DomainKnowledgePack } from "../domain-knowledge.types.js";

export const juizadoEspecialKnowledgePack: DomainKnowledgePack = {
  domain: "JUIZADO_ESPECIAL",
  label: "Juizado Especial",
  description: "Juizado Especial Cível e Criminal — causas de até 40 salários mínimos, simplicidade, oralidade e celeridade.",
  reviewerGoals: [
    "Narrar os fatos de forma simples, clara e direta adequada ao rito do JEC",
    "Documentar o pedido dentro do limite de alçada (40 SM para JEC, 60 SM para JEF)",
    "Demonstrar a tentativa de solução administrativa prévia",
    "Apresentar o cálculo do valor da causa com a soma de todos os pedidos",
    "Adequar o nível de complexidade ao rito oral e informal do juizado",
    "Antecipar a alegação de complexidade (risco de extinção por incompetência do JEC)",
    "Verificar se as partes têm capacidade para litigar no JEC (restrições do art. 8º da Lei 9.099/95)",
    "Adequar a linguagem para compreensão por pessoa sem formação jurídica (oralidade do JEC)",
  ],
  commonDocuments: [
    "Contrato, nota fiscal ou recibo da relação de consumo ou cível",
    "Protocolo de atendimento (SAC, e-mail, app, ouvidoria)",
    "Comprovante de pagamento",
    "Prints e mensagens demonstrando a falha ou o dano com data e hora visíveis",
    "Comprovante de negativação (quando for o caso)",
    "Fatura com cobrança indevida",
    "Documentos de identidade das partes",
    "Comprovante de residência (JEC exige residência na comarca ou vizinha)",
    "Orçamentos (dano material)",
  ],
  commonProofs: [
    "Documentos simples e de fácil compreensão (próprios para rito oral)",
    "Prints de tela com data e hora visíveis",
    "Protocolos de reclamação registrados",
    "Orçamentos e notas fiscais",
    "Testemunhas (máximo de 3 por parte no JEC)",
  ],
  commonWeaknesses: [
    "Valor da causa acima do limite do JEC sem justificativa de adequação",
    "Causa de alta complexidade probatória que pode gerar extinção por incompetência do juizado",
    "Ausência de descrição das tentativas de solução administrativa",
    "Pedido de perícia técnica complexa (incompatível com o rito do JEC)",
    "Fatos narrados com excesso de complexidade dificultando a compreensão oral",
    "Ausência de documento mínimo que sustente o pedido",
    "Dano moral pleiteado sem o fato específico individualizador",
    "Parte ré que não pode litigar no JEC (massa falida, incapaz, ente público em alguns estados)",
  ],
  commonDemonstrations: [
    "Linha do tempo simplificada dos fatos (curta e objetiva — adequada ao rito oral)",
    "Demonstração de que o valor do pedido está dentro do limite do JEC",
    "Demonstração da tentativa de solução extrajudicial (protocolo, e-mail, SAC)",
    "Prova documental simples e autoexplicativa",
    "Demonstração do dano com comprovante e valor específico",
  ],
  commonCalculations: [
    "Valor da causa = soma de todos os pedidos (dano material + moral + multa)",
    "Devolução em dobro de cobrança indevida (art. 42, § único do CDC)",
    "Dano moral (parâmetro local do juizado — usualmente menor que o da Vara Cível comum)",
    "Multa diária (astreinte) em caso de tutela de urgência no JEC",
    "Atualização do dano material pela data do ajuizamento",
    "Verificação do limite: 40 SM para JEC / 60 SM para JEF / 20 SM para JECRIM",
  ],
  commonCounterArguments: [
    "Incompetência do JEC por complexidade da causa (necessidade de perícia técnica)",
    "Valor acima do limite de alçada",
    "Ausência de relação de consumo (incompetência do JECB)",
    "Parte ré que não pode litigar no JEC (massa falida, incapaz, ente público não autorizado)",
    "Necessidade de perícia complexa que afasta o rito simplificado",
    "Prescrição do CDC (5 anos) ou civil (1 ou 3 anos conforme o caso)",
  ],
  strengtheningOpportunities: [
    "Simplificar a narrativa para adequação ao rito oral do JEC — linguagem clara e objetiva",
    "Calcular expressamente o valor da causa garantindo que está dentro do limite do JEC",
    "Juntar o protocolo de SAC ou e-mail demonstrando que a empresa foi notificada previamente",
    "Utilizar prints de tela e prints de protocolos como prova principal (adequados ao rito)",
    "Antecipar a possível alegação de complexidade demonstrando que a causa é simples",
    "Limitar os pedidos ao valor máximo do JEC para garantir a competência",
    "Verificar que a parte ré tem capacidade para litigar no JEC (art. 8º da Lei 9.099/95)",
  ],
  extractionHints: [
    "Nota fiscal: valor da compra/serviço (base para cálculo do valor da causa)",
    "Fatura: valor da cobrança indevida, data, descrição",
    "Protocolo: número, data, canal, confirmação de recebimento pela empresa",
    "Print: data, hora, conteúdo da mensagem ou tela, plataforma",
  ],
  cautionaryNotes: [
    "O JEC tem alçada de 40 salários mínimos para a Justiça Estadual e 60 para o JEF (Juizado Especial Federal) — não confundir os limites; o valor do JEF é maior",
    "Peças jurídicas extensas e complexas são inadequadas ao rito do JEC — a ausência de fundamentação extensiva pode ser uma escolha adequada, não uma fragilidade",
    "A ausência de advogado para causas de até 20 SM é permitida — não gere finding sobre representação processual quando a parte pode atuar sozinha",
    "Recursividade para o STJ não é cabível diretamente no JEC — os recursos são para a Turma Recursal; a menção a recursos para o STJ seria erro processual, não estratégia",
    "O réu pessoa jurídica pode litigar no JEC mas com representação obrigatória por preposto com carta de preposição — a ausência de menção a isso não é fragilidade da petição inicial",
    "Dano moral no JEC tende a ter valor menor que nas varas comuns por força da jurisprudência local — o pedido de valor alto pode ser estratégico, mas o advogado deve conhecer a prática local",
  ],
  placeholderGuidance: "Dados tipicamente pendentes de confirmação: [PRODUTO/SERVIÇO], [DATA DA FALHA], [VALOR DO DANO MATERIAL], [VALOR DO DANO MORAL PLEITEADO], [VALOR TOTAL DA CAUSA], [NÚMERO DO PROTOCOLO], [PARTE RÉ — CNPJ/CPF], [LIMITE DO JUIZADO APLICÁVEL].",
};
