import type { DomainKnowledgePack } from "../domain-knowledge.types.js";

export const rgpsKnowledgePack: DomainKnowledgePack = {
  domain: "RGPS",
  label: "Previdenciário RGPS",
  description: "Regime Geral de Previdência Social — aposentadorias, auxílios, pensões e demais benefícios do INSS.",
  reviewerGoals: [
    "Demonstrar cumprimento de todos os requisitos legais do benefício pretendido",
    "Fortalecer o quadro contributivo com períodos, carência e qualidade de segurado",
    "Documentar tempo especial com enquadramento profissional e agentes nocivos",
    "Demonstrar a incapacidade ou invalidez quando aplicável",
    "Apresentar cálculo da RMI e dos atrasados para fundamentar a pretensão financeira",
    "Antecipar questionamentos do INSS sobre a regularidade dos vínculos",
    "Verificar a viabilidade de reafirmação da DER quando mais vantajosa",
    "Fundamentar o direito à conversão de tempo especial para comum quando necessário",
  ],
  commonDocuments: [
    "CNIS (Cadastro Nacional de Informações Sociais)",
    "PPP (Perfil Profissiográfico Previdenciário)",
    "LTCAT (Laudo Técnico das Condições Ambientais do Trabalho)",
    "Carta de Concessão ou Carta de Indeferimento do INSS",
    "Processo Administrativo (NB/PA)",
    "Laudo Médico Pericial (administrativo ou judicial)",
    "Exames, laudos médicos e prontuários",
    "CTPS (Carteira de Trabalho e Previdência Social)",
    "Certidão de Tempo de Contribuição (CTC) de outros regimes",
    "Declaração de Imposto de Renda (comprovação de atividade)",
    "Comprovantes de exercício de atividade rural (quando aplicável)",
    "Declaração do sindicato ou colônia de pescadores (trabalhador rural)",
    "Laudos e atestados médicos com CID e grau de incapacidade",
    "Documentos de identidade e certidão de óbito (pensão por morte)",
  ],
  commonProofs: [
    "CNIS completo com todos os vínculos e competências",
    "PPP assinado por responsável técnico com o agente nocivo identificado",
    "LTCAT contemporâneo à exposição ao agente nocivo",
    "Laudos médicos com CID e grau de incapacidade",
    "Testemunhas de vínculos não formalizados ou tempo rural",
    "Documentos de identidade e comprovação de vínculo familiar (pensão por morte)",
    "Notas fiscais, contratos de arrendamento, documentos escolares rurais",
  ],
  commonWeaknesses: [
    "Carência não demonstrada com quadro de períodos e contribuições",
    "Qualidade de segurado não explorada ou não demonstrada na DER",
    "Tempo especial sem identificação do agente nocivo e enquadramento profissional",
    "Ausência de quadro de períodos contributivos e contagem total",
    "Ausência de cálculo do tempo total de contribuição",
    "DER (Data de Entrada do Requerimento) ou DIB (Data de Início do Benefício) não fixadas",
    "Períodos de graça não identificados quando relevantes",
    "Conversão de tempo especial para comum não demonstrada quando necessária",
    "Lacunas no CNIS não explicadas ou não justificadas",
    "LOAS/BPC: miserabilidade e incapacidade não suficientemente demonstradas",
    "Vínculos extemporâneos sem documentação alternativa ao CNIS",
    "Reafirmação da DER não avaliada quando poderia gerar benefício maior",
  ],
  commonDemonstrations: [
    "Quadro de tempo de contribuição com todos os períodos discriminados",
    "Quadro de carência (número de contribuições mensais exigidas e cumpridas)",
    "Quadro de períodos especiais com agentes e enquadramento profissional",
    "Linha do tempo contributiva (início — DER — DIB pretendida)",
    "Demonstração da qualidade de segurado na DER",
    "Quadro de períodos de graça quando aplicável",
    "Comparação entre tempo real e tempo convertido (especial/comum)",
    "Demonstração de miserabilidade (LOAS/BPC): renda per capita familiar e composição do núcleo",
    "Demonstração da incapacidade laboral (LOAS/BPC): laudo médico + CID + restrições funcionais",
  ],
  commonCalculations: [
    "Tempo de contribuição total (anos, meses, dias)",
    "Carência (número de contribuições mensais)",
    "RMI (Renda Mensal Inicial) com média dos salários de contribuição",
    "Atrasados (DIB até a citação ou data do acordo)",
    "Conversão de tempo especial para comum (fator 1,4 / 1,2 / 1,167 conforme o caso)",
    "Acréscimo de 25% (aposentadoria por invalidez com dependente de cuidados permanentes)",
    "Diferença entre o benefício concedido e o devido (revisão de benefício)",
    "Atualização da RMI com índices aplicáveis (INPC/IPCA)",
    "Cálculo da reafirmação da DER: comparativo entre datas",
  ],
  commonCounterArguments: [
    "Ausência de qualidade de segurado na DER",
    "Carência insuficiente",
    "Tempo especial sem prova do agente nocivo ou habitualidade permanente e não ocasional",
    "Vínculos no CNIS com divergência de remuneração ou período",
    "Períodos de contribuição como contribuinte individual não comprovados",
    "Prescrição quinquenal de parcelas anteriores ao ajuizamento",
    "Capacidade laboral residual (contestação à aposentadoria por incapacidade)",
    "Renda familiar acima de 1/4 do salário mínimo per capita (LOAS/BPC)",
    "Tempo especial: EPI eficaz neutralizando o agente nocivo",
  ],
  strengtheningOpportunities: [
    "Incluir quadro comparativo de períodos CNIS × CTPS quando houver divergência",
    "Juntar PPP e LTCAT contemporâneos para cada período especial distinto",
    "Apresentar linha do tempo visual das fases contribuição — DER — DIB pretendida",
    "Incluir memória de cálculo da RMI com planilha de salários de contribuição",
    "Demonstrar expressamente os períodos de graça mantendo a qualidade de segurado",
    "Antecipar a contestação sobre capacidade laboral com laudos detalhados e CID",
    "Verificar e demonstrar a viabilidade de reafirmação da DER quando mais vantajosa",
    "Para LOAS/BPC: juntar laudo médico detalhado + composição e renda familiar documentada",
    "Para tempo rural: juntar documentos alternativos ao CNIS (sindicato, contratos, fotos)",
    "Identificar vínculos extemporâneos sem CNIS e propor meio alternativo de prova",
  ],
  extractionHints: [
    "CNIS: competência, categoria, remuneração, indicadores de período especial",
    "PPP: razão social, CNPJ, agente nocivo, código, período de exposição, EPC/EPI",
    "LTCAT: agente nocivo, nível de exposição, data de elaboração, responsável técnico",
    "Laudo médico: CID, grau de incapacidade, data, CRM do perito, restrições funcionais",
    "CTPS: empresa, cargo, data de admissão, data de demissão, salário anotado",
    "Carta de indeferimento: NB, DER, motivo do indeferimento, fundamento legal",
  ],
  cautionaryNotes: [
    "Reafirmação da DER é estratégia legítima e não é erro — quando o benefício calculado em data posterior ao requerimento original é mais vantajoso, não gere finding sobre 'data errada'",
    "Vínculos extemporâneos (períodos antigos sem registro no CNIS) podem ser provados por outros meios documentais — a ausência de CNIS não significa ausência de contribuição",
    "Período de graça mantém a qualidade de segurado mesmo sem contribuições recentes — não presumir perda de qualidade sem verificar se a regra do período de graça se aplica",
    "Atividade rural anterior a 1991 não exige contribuição, apenas comprovação do exercício — a ausência de recolhimento nesse período não é fragilidade da peça",
    "EPI eficaz neutralizando o agente nocivo é argumento do INSS, não do segurado — não gere finding para o advogado incluir prova de EPI salvo se a peça já tratar desse argumento",
    "Placeholders de dados do processo administrativo (NB, DER, DIB, RMI) são esperados e normais — não gere finding apenas por sua presença",
  ],
  placeholderGuidance: "Dados tipicamente pendentes de OCR ou confirmação: [NB/PA], [DER], [DIB], [DCB], [RMI], [DATA DO ÓBITO] (pensão por morte), [COMPETÊNCIA CNIS], [AGENTE NOCIVO], [PERÍODO ESPECIAL], [TEMPO TOTAL DE CONTRIBUIÇÃO], [VALOR DA CAUSA].",
};
