import type { DomainKnowledgePack } from "../domain-knowledge.types.js";

export const rppsKnowledgePack: DomainKnowledgePack = {
  domain: "RPPS",
  label: "Previdenciário RPPS",
  description: "Regime Próprio de Previdência Social — servidores públicos federais, estaduais e municipais.",
  reviewerGoals: [
    "Demonstrar o enquadramento no regime próprio e os requisitos da regra de transição aplicável",
    "Fortalecer a comprovação do tempo de serviço público e do cargo efetivo",
    "Demonstrar a integralidade e paridade quando aplicáveis",
    "Documentar o exercício de cargo efetivo por período suficiente",
    "Apresentar o impacto financeiro da aposentadoria concedida versus a devida",
    "Identificar precisamente a regra de transição entre as ECs 41/2003, 47/2005 e EC 103/2019",
    "Demonstrar o direito ao abono de permanência quando o servidor completou os requisitos mas permaneceu em atividade",
  ],
  commonDocuments: [
    "Ficha funcional completa (assentamento funcional)",
    "Portaria ou decreto de nomeação e posse",
    "Registros de frequência e afastamentos",
    "Certidão de Tempo de Contribuição (CTC)",
    "Estatuto do servidor e lei do RPPS do ente",
    "Demonstrativos de remuneração (contracheques)",
    "Ato concessório anterior (se revisão de aposentadoria)",
    "Declaração de acumulação lícita ou ilícita de cargos",
    "Laudos médicos e perícia oficial (aposentadoria por invalidez)",
    "Publicações em Diário Oficial de nomeação, posse e exoneração",
    "Lei do RPPS do ente federativo e regulamento do fundo previdenciário",
  ],
  commonProofs: [
    "Ficha funcional e portaria de nomeação no Diário Oficial",
    "Certidão de tempo de serviço emitida pelo ente competente",
    "Laudos periciais médicos para aposentadoria por invalidez",
    "Testemunhos de servidores da mesma época (vínculos sem registros formais)",
    "Publicações em Diário Oficial confirmando ingresso e exercício",
  ],
  commonWeaknesses: [
    "Regra de transição aplicável não identificada com precisão (EC 41, EC 47 ou EC 103)",
    "Tempo de serviço em cargo efetivo não discriminado por cargo, ente e período",
    "Contagem de tempo especial no serviço público não demonstrada",
    "Integralidade e paridade não demonstradas quando aplicáveis ao caso concreto",
    "Ausência de cálculo comparativo entre proventos concedidos e devidos",
    "Períodos de contribuição para RGPS (tempo anterior) não computados via CTC",
    "EC 41/2003 e EC 47/2005 e EC 103/2019 não analisadas quanto à regra de transição mais favorável",
    "Cargo comissionado ou temporário indevidamente contado como efetivo",
    "Abono de permanência não identificado quando cabível",
  ],
  commonDemonstrations: [
    "Quadro de tempo de serviço público por cargo, ente e período",
    "Enquadramento na regra de transição aplicável (EC 41/2003 ou EC 47/2005 ou EC 103/2019)",
    "Demonstração da integralidade dos proventos quando cabível",
    "Demonstração da paridade com servidores ativos quando cabível",
    "Linha do tempo: ingresso no serviço público — marcos das ECs — cumprimento dos requisitos — aposentadoria",
    "Quadro de tempo de contribuição acumulado (RPPS + RGPS quando houver)",
    "Demonstração do direito ao abono de permanência e período de percepção",
  ],
  commonCalculations: [
    "Tempo de efetivo exercício no cargo efetivo",
    "Tempo de serviço público total (inclusive tempo anterior ao cargo atual)",
    "Proventos na integralidade da remuneração do cargo efetivo quando cabível",
    "Diferença entre proventos concedidos e devidos (base para pedido de revisão)",
    "Abono de permanência (equivalente à contribuição previdenciária do servidor)",
    "Sistema de pontos da EC 103/2019 e progressão anual",
  ],
  commonCounterArguments: [
    "Cargo ocupado não era efetivo (comissionado, temporário ou sem concurso)",
    "Tempo de serviço em outro regime não averbável no RPPS",
    "Aplicação da EC 41/2003 excluindo integralidade e paridade",
    "Tempo mínimo no cargo ou no serviço público insuficiente",
    "Prescrição das diferenças de proventos anteriores",
    "Acumulação ilícita de cargos que invalida o cômputo do tempo",
  ],
  strengtheningOpportunities: [
    "Identificar expressamente a regra de transição aplicável com os seus requisitos e demonstrar o cumprimento de cada um",
    "Incluir quadro comparativo de proventos na regra pleiteada vs. regra aplicada pelo ente",
    "Demonstrar tempo de contribuição de outros regimes com a CTC correspondente",
    "Apresentar linha do tempo dos marcos temporais relevantes (ingresso, ECs 41, 47, 103, cumprimento dos requisitos)",
    "Antecipar a questão sobre a natureza efetiva do cargo com a lei de criação do cargo e portaria de concurso",
    "Verificar e demonstrar o direito ao abono de permanência com o período e o valor correspondente",
  ],
  extractionHints: [
    "Ficha funcional: cargo, lotação, data de posse, data de exoneração ou aposentadoria",
    "CTC: tempo averbado, origem (RGPS/RPPS/outro ente), ente emitente",
    "Contracheque: base de cálculo, vantagens percebidas, descontos previdenciários",
    "Portaria/Decreto: número, data, autoridade, cargo, fundamento legal",
  ],
  cautionaryNotes: [
    "A integralidade e a paridade não se aplicam a todos os servidores — dependem da regra de transição pela qual a aposentadoria é concedida; não gere finding presumindo que são sempre devidas",
    "O cargo comissionado sem concurso não conta para tempo de efetivo exercício no RPPS, mas pode ter contribuições para o RGPS que sejam averbáveis — a questão é técnica e depende da legislação do ente",
    "EC 103/2019 trouxe novas regras que coexistem com as anteriores para quem ingressou antes; não presuma que uma só regra se aplica sem verificar a data de ingresso no serviço público",
    "O abono de permanência é direito do servidor que completou os requisitos mas continuou em atividade — sua ausência na peça pode ser omissão relevante ou simplesmente inviável no caso concreto",
  ],
  placeholderGuidance: "Dados tipicamente pendentes de confirmação: [CARGO], [ENTE FEDERATIVO], [DATA DE POSSE], [DATA DA APOSENTADORIA], [TEMPO DE SERVIÇO TOTAL], [PROVENTOS CONCEDIDOS], [PROVENTOS DEVIDOS], [DIFERENÇA MENSAL], [REGRA DE TRANSIÇÃO APLICÁVEL].",
};
