import type { DomainKnowledgePack } from "../domain-knowledge.types.js";

export const trabalhistaKnowledgePack: DomainKnowledgePack = {
  domain: "TRABALHISTA",
  label: "Direito do Trabalho",
  description: "Reclamações trabalhistas, rescisões, verbas rescisórias, horas extras, danos morais e materiais trabalhistas.",
  reviewerGoals: [
    "Demonstrar o vínculo empregatício com todos os seus elementos (subordinação, pessoalidade, habitualidade, onerosidade)",
    "Fortalecer a prova da jornada para fundamentar horas extras e reflexos",
    "Documentar as verbas rescisórias devidas com memória de cálculo",
    "Demonstrar o fato específico que gerou o dano moral trabalhista",
    "Antecipar a defesa da empresa sobre prescrição, enquadramento e jornada",
    "Apresentar planilha de verbas com reflexos (férias, 13º, FGTS, aviso prévio)",
    "Identificar a CCT/ACT aplicável e as cláusulas normativamente relevantes ao caso",
    "Demonstrar o desvio de função ou acúmulo de funções quando configurados",
  ],
  commonDocuments: [
    "CTPS (Carteira de Trabalho e Previdência Social)",
    "TRCT (Termo de Rescisão do Contrato de Trabalho)",
    "Holerites / contracheques de todo o período",
    "Controles de ponto (eletrônicos, manuais ou biométricos)",
    "Contrato de trabalho e aditivos contratuais",
    "Recibos de pagamento de verbas rescisórias",
    "Mensagens, e-mails e comunicações com o empregador",
    "Advertências e suspensões disciplinares",
    "Laudos de insalubridade ou periculosidade",
    "PPP (quando houver exposição a agentes nocivos)",
    "Recibo de aviso prévio",
    "Extrato do FGTS",
    "Convenção Coletiva de Trabalho (CCT) e Acordo Coletivo de Trabalho (ACT)",
    "Comprovantes de pagamento de PLR e outros benefícios",
  ],
  commonProofs: [
    "Controles de ponto (eletrônicos e manuais)",
    "Testemunhos de colegas de trabalho",
    "Registros de câmeras ou sistemas eletrônicos internos",
    "Prints de conversas e ordens via aplicativo de mensagens",
    "E-mails com horários de envio comprobatórios da jornada",
    "Laudos periciais de insalubridade e periculosidade",
    "Extratos bancários demonstrando depósitos de FGTS e remuneração",
  ],
  commonWeaknesses: [
    "Jornada de trabalho afirmada sem prova documental correspondente",
    "Horas extras sem quadro comparativo de horários e reflexos calculados",
    "Vínculo empregatício sem demonstração dos elementos (subordinação, habitualidade, pessoalidade, onerosidade)",
    "Dano moral trabalhista descrito de forma genérica sem o fato específico e suas consequências",
    "Verbas rescisórias sem planilha de cálculo individual com reflexos",
    "Enquadramento sindical e convenção coletiva aplicável não identificados",
    "Data de início real do vínculo não demonstrada quando diferente da CTPS",
    "Habitualidade de horas extras sem identificação dos períodos e frequência",
    "Desvio de função sem discriminação das funções contratada e efetivamente exercida",
    "Assédio moral sem identificação das condutas, autores, datas e testemunhas",
    "Justa causa contestada sem identificação dos vícios do procedimento disciplinar",
  ],
  commonDemonstrations: [
    "Quadro de jornada contratada × jornada praticada × horas extras por período",
    "Quadro de verbas rescisórias com cálculo individual de cada verba",
    "Linha do tempo do contrato de trabalho (admissão — fatos relevantes — rescisão)",
    "Demonstração dos elementos da subordinação jurídica (ordens, metas, controle, exclusividade)",
    "Demonstração da habitualidade de horas extras com frequência e período",
    "Demonstração do nexo causal entre conduta do empregador e dano moral sofrido",
    "Quadro de reflexos das horas extras em férias, 13º, FGTS e aviso prévio",
    "Demonstração do desvio de função com as atribuições do cargo anotado vs. exercidas",
  ],
  commonCalculations: [
    "Horas extras e adicional (50% ou 100% conforme CCT/ACT)",
    "Reflexos das horas extras em férias, 13º, FGTS e aviso prévio",
    "Adicional de insalubridade (10%, 20% ou 40% do salário mínimo ou base)",
    "Adicional de periculosidade (30% do salário-base)",
    "Aviso prévio proporcional ao tempo de serviço (pós-Lei 12.506/2011)",
    "Multa de 40% do FGTS",
    "Verbas rescisórias (saldo de salário, férias vencidas e proporcionais, 13º proporcional)",
    "FGTS não depositado e multa",
    "Indenização por dano moral com parâmetros jurisprudenciais",
    "Diferença salarial por desvio de função com reflexos",
  ],
  commonCounterArguments: [
    "Prescrição bienal (extinção do contrato) e quinquenal (parcelas anteriores)",
    "Vínculo autônomo (PJ, parceiro comercial, prestador independente sem subordinação)",
    "Controle de ponto fidedigno negando as horas extras alegadas",
    "Compensação de jornada (banco de horas ou acordo coletivo válido)",
    "Justa causa como motivo da rescisão (eliminando certas verbas)",
    "Ausência de dano ou mero aborrecimento cotidiano (dano moral)",
    "Categoria diferente e norma coletiva diversa da aplicada pelo reclamante",
    "Reforma trabalhista (Lei 13.467/2017): alterações aplicáveis ao contrato em questão",
  ],
  strengtheningOpportunities: [
    "Incluir planilha de horas extras com todos os dias e reflexos calculados",
    "Identificar expressamente a CCT aplicável, a data-base e as cláusulas relevantes",
    "Descrever o fato gerador do dano moral com datas, autores e testemunhas",
    "Juntar extrato do FGTS para demonstrar depósitos insuficientes ou ausentes",
    "Apresentar linha do tempo do contrato de trabalho com os eventos principais",
    "Antecipar a alegação de trabalho autônomo com os elementos de subordinação jurídica",
    "Identificar expressamente o cargo descrito na CTPS vs. o cargo efetivamente exercido (desvio de função)",
    "Verificar aplicabilidade das normas pré e pós-reforma trabalhista ao contrato específico",
  ],
  extractionHints: [
    "CTPS: empregador, cargo anotado, data de admissão, data de saída, salário anotado",
    "Holerite: salário base, horas extras declaradas, adicionais, descontos, FGTS retido",
    "Ponto eletrônico: horários de entrada/saída por dia, intervalos intrajornada",
    "TRCT: verbas pagas discriminadas, data de homologação, motivo da rescisão",
    "CCT/ACT: vigência, data-base, cláusulas sobre horas extras, adicionais e benefícios",
  ],
  cautionaryNotes: [
    "A reforma trabalhista (Lei 13.467/2017) alterou regras sobre banco de horas, negociação coletiva e dano moral — verifique a data do contrato antes de aplicar as regras antigas ou novas",
    "Horas in itinere foram extintas pela reforma trabalhista para contratos iniciados após novembro de 2017 — não gere finding sobre sua ausência em contratos posteriores à reforma",
    "Acordo coletivo de compensação de jornada válido afasta o direito às horas extras — não presuma que o banco de horas é inválido sem verificar se há acordo coletivo",
    "O dano moral trabalhista pós-reforma tem parâmetros tarifados por lei — a ausência de valor expresso na inicial pode ser intencional (pedido ilíquido)",
    "PLR não integra a remuneração e não gera reflexos — não gere finding sobre ausência de reflexos de PLR",
  ],
  placeholderGuidance: "Dados tipicamente pendentes de confirmação: [DATA DE ADMISSÃO], [DATA DE DEMISSÃO], [SALÁRIO BASE], [MOTIVO DA RESCISÃO], [TOTAL DE HORAS EXTRAS], [VALOR DA CAUSA], [CCT APLICÁVEL], [DATA-BASE], [ADICIONAL DE INSALUBRIDADE — GRAU].",
};
