import type { DomainKnowledgePack } from "../domain-knowledge.types.js";

export const tributarioKnowledgePack: DomainKnowledgePack = {
  domain: "TRIBUTARIO",
  label: "Direito Tributário",
  description: "Defesa fiscal, repetição de indébito, ações anulatórias, mandados de segurança tributários e execuções fiscais.",
  reviewerGoals: [
    "Demonstrar a ilegalidade ou inconstitucionalidade da exigência fiscal",
    "Delimitar com precisão o crédito tributário questionado (tributo, período, valor)",
    "Demonstrar decadência ou prescrição quando aplicáveis",
    "Fundamentar a repetição do indébito com cálculo do valor pago indevidamente",
    "Antecipar a contestação fazendária sobre a constitucionalidade da norma e a regularidade do lançamento",
    "Apresentar demonstrativo de impacto financeiro da tese para o cliente",
    "Identificar precedentes vinculantes do STF/STJ aplicáveis à tese e eventual modulação de efeitos",
    "Verificar a existência de parcelamentos ou compensações que afetem o crédito tributário",
  ],
  commonDocuments: [
    "Auto de Infração (AI) ou Notificação de Lançamento",
    "CDA (Certidão de Dívida Ativa)",
    "DARF, DAS, GPS ou outro documento de pagamento",
    "Processo Administrativo Fiscal (PAF) completo",
    "Decisão administrativa (1ª instância e CARF quando houver)",
    "Notificações fiscais e intimações",
    "Comprovantes de pagamento do tributo questionado",
    "Declarações fiscais (DCTF, EFD, SPED, ECF, PGDAS)",
    "Notas fiscais e contratos (quando a exigência recair sobre operação específica)",
    "Certidão Negativa ou Positiva com Efeitos de Negativa (CND/CPEN)",
    "Comprovante de parcelamento ou adesão a programa de regularização fiscal (REFIS/PERT/RELP)",
  ],
  commonProofs: [
    "DARFs e comprovantes de pagamento com autenticação bancária",
    "Documentos contábeis (balanço, razão contábil, livros fiscais)",
    "Declarações fiscais retificadoras",
    "Laudos e pareceres técnicos contábeis",
    "Planilhas de apuração do tributo",
    "Pareceres jurídicos e precedentes judiciais favoráveis",
    "Extrato de parcelamento demonstrando pagamentos e saldo devedor",
  ],
  commonWeaknesses: [
    "Decadência não demonstrada com linha do tempo do fato gerador e do lançamento",
    "Prescrição não demonstrada com a data de constituição definitiva do crédito",
    "Período de apuração do crédito tributário não delimitado",
    "Ausência de cálculo do indébito ou do crédito contestado",
    "Ausência de demonstração comparativa entre o regime tributário correto e o exigido",
    "Contestação da base de cálculo sem memória de cálculo própria",
    "Legislação aplicável à época dos fatos não identificada",
    "Modulação de efeitos de precedente do STF não analisada (pode limitar o alcance temporal da tese)",
    "Ilegitimidade ativa não antecipada (contribuinte de fato × contribuinte de direito)",
    "Parcelamento ativo não mencionado quando pode interferir na tese de prescrição ou compensação",
  ],
  commonDemonstrations: [
    "Linha do tempo do crédito tributário (fato gerador — lançamento — impugnação — decisão)",
    "Quadro de decadência por período de apuração",
    "Quadro de prescrição com a data de constituição definitiva",
    "Cálculo do indébito tributário com juros SELIC e correção",
    "Demonstração do pagamento indevido por período",
    "Comparativo entre base de cálculo aplicada pelo fisco e a base correta",
    "Demonstrativo de impacto financeiro da tese para o cliente",
    "Análise da modulação de efeitos do precedente do STF quando aplicável",
  ],
  commonCalculations: [
    "Decadência (art. 150 ou 173 do CTN conforme o tipo de lançamento)",
    "Prescrição quinquenal e marcos de interrupção",
    "Repetição do indébito com juros SELIC",
    "Diferença entre o tributo exigido e o tributo efetivamente devido",
    "Penalidades e multas aplicadas vs. limite legal (100% ou 150%)",
    "Créditos de compensação disponíveis e estimativa de aproveitamento",
    "Saldo de parcelamento e impacto sobre o crédito questionado",
  ],
  commonCounterArguments: [
    "Regularidade do lançamento e observância do contraditório administrativo",
    "Ausência de decadência ou prescrição (interrupção ou suspensão do prazo)",
    "Constitucionalidade da norma (repercussão geral julgada desfavorável ou sem precedente favorável)",
    "Base de cálculo correta conforme a legislação aplicável",
    "Multa proporcional dentro dos limites legais",
    "Ilegitimidade ativa para a repetição (contribuinte de fato × contribuinte de direito)",
    "Modulação dos efeitos da decisão do STF restringindo o período de aproveitamento do indébito",
  ],
  strengtheningOpportunities: [
    "Incluir linha do tempo detalhada do crédito tributário com todas as datas relevantes",
    "Apresentar planilha de cálculo do indébito com SELIC mês a mês",
    "Identificar e citar os precedentes vinculantes do STF/STJ aplicáveis à tese",
    "Demonstrar expressamente a decadência por período de apuração",
    "Antecipar a contestação da Fazenda com fundamentos já enfrentados em julgados",
    "Quantificar o impacto financeiro total da tese para o cliente",
    "Verificar e endereçar expressamente a modulação de efeitos quando o precedente a previu",
    "Antecipar a questão da ilegitimidade ativa (contribuinte de fato vs. de direito) quando a tese envolve repasse ao consumidor",
  ],
  extractionHints: [
    "Auto de infração: tributo, período, base de cálculo, alíquota, valor principal, multa, fundamento legal",
    "DARF: código da receita, período de apuração, data de pagamento, valor",
    "CDA: número, devedor, valor total, fundamento legal da inscrição, data de inscrição",
    "Decisão administrativa: órgão julgador, data, resultado (procedente/improcedente), fundamentos",
    "Parcelamento: programa, número do parcelamento, total de parcelas, saldo devedor",
  ],
  cautionaryNotes: [
    "A modulação de efeitos de precedente do STF pode restringir o período de aproveitamento do indébito — não presuma que a tese vale desde sempre se houve modulação",
    "Contribuinte de fato (consumidor que suportou o tributo) geralmente não tem legitimidade para a repetição — a legitimidade pertence ao contribuinte de direito (quem recolheu); não gere finding contrário a isso",
    "Parcelamento ativo implica confissão do débito e pode suspender a prescrição — não gere finding sobre prescrição sem verificar se há parcelamento em curso",
    "A distinção entre lançamento por homologação (art. 150 CTN) e de ofício (art. 173 CTN) altera o prazo decadencial — o prazo depende do tipo de lançamento, não é uniformemente 5 anos",
    "Compensação tributária exige prévia habilitação administrativa — a ausência desse pedido na inicial pode ser estratégica e não é fragilidade automática",
  ],
  placeholderGuidance: "Dados tipicamente pendentes de confirmação: [TRIBUTO], [PERÍODO DE APURAÇÃO], [VALOR DO INDÉBITO], [VALOR ATUALIZADO PELA SELIC], [AUTO DE INFRAÇÃO Nº], [CNPJ DO CONTRIBUINTE], [FUNDAMENTO NORMATIVO DA TESE], [PRECEDENTE DO STF/STJ APLICÁVEL].",
};
