import type { JurisdicaoRule } from "./base.rules.js";

export const TRIBUNAL_RULES: Record<string, JurisdicaoRule> = {
  TRABALHO: {
    descricao: "Justiça do Trabalho",
    tribunal_primeiro_grau: "VARA DO TRABALHO",
    tribunal_segundo_grau: "TRT",
    tribunal_superior: "TST",
    artigos_bloqueados: [
      "art. 85 CPC",
      "art. 85 §2º CPC",
      "apelação",
      "apelação cível",
      "embargos infringentes",
      "art. 475-J CPC",
    ],
    diplomas_prioritarios: ["CLT", "CF/88 art. 7º", "CPC subsidiário"],
    recursos_validos: ["Recurso Ordinário", "Recurso de Revista", "Agravo de Instrumento", "Embargos de Declaração"],
    honorarios_artigo: "art. 791-A CLT",
    custas_artigo: "art. 789 CLT",
  },
  FEDERAL: {
    descricao: "Justiça Federal",
    tribunal_primeiro_grau: "VARA FEDERAL",
    tribunal_segundo_grau: "TRF",
    tribunal_superior: "STJ / STF",
    artigos_bloqueados: [],
    diplomas_prioritarios: ["CPC/2015", "CF/88", "Leis especiais federais"],
    recursos_validos: ["Apelação", "Agravo de Instrumento", "Recurso Especial", "Recurso Extraordinário"],
    honorarios_artigo: "art. 85 CPC/2015",
    custas_artigo: "art. 82 CPC/2015",
  },
  ESTADUAL: {
    descricao: "Justiça Estadual",
    tribunal_primeiro_grau: "VARA CÍVEL / VARA CRIMINAL",
    tribunal_segundo_grau: "TJXX",
    tribunal_superior: "STJ / STF",
    artigos_bloqueados: [],
    diplomas_prioritarios: ["CPC/2015", "CF/88", "Código Civil/2002", "CPP (se criminal)"],
    recursos_validos: ["Apelação", "Apelação Criminal (CPP art. 593)", "RESE", "Habeas Corpus", "Agravo de Instrumento"],
    honorarios_artigo: "art. 85 CPC/2015 (cível) | sem honorários (criminal)",
    custas_artigo: "art. 82 CPC/2015",
  },
  JEF: {
    descricao: "Juizado Especial Federal (Lei 10.259/01)",
    tribunal_primeiro_grau: "JEF",
    tribunal_segundo_grau: "Turma Recursal Federal",
    tribunal_superior: "TNU (Turma Nacional de Uniformização)",
    artigos_bloqueados: ["apelação", "recurso ordinário"],
    diplomas_prioritarios: ["Lei 10.259/01", "Lei 9.099/95", "CPC subsidiário", "CF/88"],
    recursos_validos: ["Recurso Inominado", "Embargos de Declaração", "Pedido de Uniformização"],
    honorarios_artigo: "sem condenação em honorários (art. 55 Lei 9.099/95 c/c art. 1º Lei 10.259/01)",
    custas_artigo: "sem custas em primeiro grau (art. 54 Lei 9.099/95)",
  },
  JEC: {
    descricao: "Juizado Especial Cível (Lei 9.099/95)",
    tribunal_primeiro_grau: "JEC",
    tribunal_segundo_grau: "Turma Recursal Estadual",
    tribunal_superior: "STJ (questão federal)",
    artigos_bloqueados: ["apelação", "recurso ordinário"],
    diplomas_prioritarios: ["Lei 9.099/95", "CC/2002", "CDC", "CF/88"],
    recursos_validos: ["Recurso Inominado", "Embargos de Declaração"],
    honorarios_artigo: "sem honorários em 1º grau, possível em 2º (art. 55 Lei 9.099/95)",
    custas_artigo: "sem custas em 1º grau (art. 54 Lei 9.099/95)",
  },
  CRIMINAL: {
    descricao: "Justiça Criminal (Estadual ou Federal)",
    tribunal_primeiro_grau: "VARA CRIMINAL / VARA DO JÚRI",
    tribunal_segundo_grau: "TJXX / TRF",
    tribunal_superior: "STJ / STF",
    artigos_bloqueados: ["art. 85 CPC", "art. 85 §2º CPC"],
    diplomas_prioritarios: ["CPP", "CP", "CF/88 art. 5º", "Lei 7.210/84 (LEP)"],
    recursos_validos: ["Apelação Criminal (art. 593 CPP)", "RESE (art. 581 CPP)", "Habeas Corpus", "Embargos de Declaração"],
    honorarios_artigo: "sem honorários advocatícios em matéria criminal",
    custas_artigo: "art. 804 CPP",
  },
  EXECUCAO_FISCAL: {
    descricao: "Execução Fiscal (Lei 6.830/80)",
    tribunal_primeiro_grau: "VARA DE EXECUÇÃO FISCAL / VARA FEDERAL",
    tribunal_segundo_grau: "TRF / TJXX",
    tribunal_superior: "STJ / STF",
    artigos_bloqueados: [],
    diplomas_prioritarios: ["Lei 6.830/80", "CTN", "CPC subsidiário", "CF/88"],
    recursos_validos: ["Apelação", "Agravo de Instrumento", "Embargos à Execução Fiscal"],
    honorarios_artigo: "art. 85 CPC/2015",
    custas_artigo: "art. 82 CPC/2015",
  },
  INDETERMINADA: {
    descricao: "Jurisdição não identificada com segurança",
    tribunal_primeiro_grau: "[A DETERMINAR]",
    tribunal_segundo_grau: "[A DETERMINAR]",
    tribunal_superior: "[A DETERMINAR]",
    artigos_bloqueados: [],
    diplomas_prioritarios: [],
    recursos_validos: [],
    honorarios_artigo: "[A DETERMINAR conforme jurisdição]",
    custas_artigo: "[A DETERMINAR conforme jurisdição]",
  },
};
