/**
 * FASE 9.0.5A — Gold Corpus Sintético V1
 *
 * 100 casos controlados para avaliação do AI Legal Strength Reviewer.
 * Cada caso define o cenário, os defeitos planejados, os findings esperados
 * e a faixa de score esperada.
 *
 * IMPORTANTE: Este arquivo é especificação de dados — sem lógica executável.
 * Não conecta ao reviewer real nesta fase.
 *
 * Distribuição:
 *   RGPS: 15 | RPPS: 5 | TRABALHISTA: 10 | TRIBUTARIO: 10 | FAMILIA: 10
 *   CONSUMIDOR: 10 | CRIMINAL: 10 | FAZENDA_PUBLICA: 10 | AMBIENTAL: 5
 *   CIVEL: 10 | JUIZADO_ESPECIAL: 5
 *   Total: 100
 *
 * Mapeamento de tipos não canônicos:
 *   EMBARGOS              → RECURSO      (+ subtype: "EMBARGOS")
 *   EXCECAO_PRE_EXECUTIVIDADE → PETICAO_INICIAL (+ subtype: "EXCECAO_PRE_EXECUTIVIDADE")
 */

import type { GoldCorpusCase } from "./gold-corpus.types.js";

export const goldCorpusV1: GoldCorpusCase[] = [

  // ── RGPS — 15 casos ───────────────────────────────────────────────────────

  {
    id: "RGPS-001",
    domain: "RGPS",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Aposentadoria por idade urbana com idade, carência, CNIS e DER bem demonstrados.",
    plantedIssues: [],
    expectedFindings: [],
    unexpectedFindings: [
      "não apontar ausência de PPP",
      "não apontar ausência de LTCAT",
    ],
    expectedScoreRange: { min: 88, max: 96 },
    notes: "Aposentadoria por idade não exige PPP/LTCAT — findings sobre sua ausência seriam falsos positivos.",
  },

  {
    id: "RGPS-002",
    domain: "RGPS",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Aposentadoria especial com menção genérica a PPP, mas sem análise de agente nocivo, intensidade, habitualidade e permanência.",
    plantedIssues: ["fundamentação insuficiente do tempo especial"],
    expectedFindings: [
      "ausência de análise concreta do PPP",
      "ausência de habitualidade/permanência",
    ],
    expectedScoreRange: { min: 70, max: 82 },
  },

  {
    id: "RGPS-003",
    domain: "RGPS",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "SEVERE_ISSUES",
    scenario: "Benefício por incapacidade com laudo pericial desfavorável, mas o recurso ignora a conclusão técnica.",
    plantedIssues: ["não enfrentamento da perícia"],
    expectedFindings: [
      "enfrentamento insuficiente da prova pericial",
      "ausência de contraponto técnico",
    ],
    expectedScoreRange: { min: 55, max: 70 },
  },

  {
    id: "RGPS-004",
    domain: "RGPS",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "LOAS/BPC com deficiência alegada, mas sem desenvolver miserabilidade, grupo familiar e renda.",
    plantedIssues: ["miserabilidade insuficiente"],
    expectedFindings: ["análise socioeconômica insuficiente"],
    expectedScoreRange: { min: 62, max: 76 },
  },

  {
    id: "RGPS-005",
    domain: "RGPS",
    documentType: "RECURSO",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Revisão de aposentadoria com erro de salário de contribuição demonstrado por CNIS e carta de concessão.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "RGPS-006",
    domain: "RGPS",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Aposentadoria rural por idade sem indicação mínima de início de prova material.",
    plantedIssues: ["ausência de início de prova material"],
    expectedFindings: ["prova rural insuficientemente demonstrada"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "RGPS-007",
    domain: "RGPS",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "LIGHT_ISSUES",
    scenario: "Tempo especial com PPP juntado, mas análise superficial dos campos técnicos.",
    plantedIssues: ["análise superficial do PPP"],
    expectedFindings: ["fundamentação técnica incompleta"],
    expectedScoreRange: { min: 72, max: 84 },
  },

  {
    id: "RGPS-008",
    domain: "RGPS",
    documentType: "CUMPRIMENTO_SENTENCA",
    difficulty: "HARD",
    quality: "MODERATE_ISSUES",
    scenario: "Cumprimento de sentença previdenciário com valor final, mas sem memória de cálculo detalhada.",
    plantedIssues: ["cálculo sem memória"],
    expectedFindings: ["ausência de memória de cálculo verificável"],
    expectedScoreRange: { min: 62, max: 76 },
  },

  {
    id: "RGPS-009",
    domain: "RGPS",
    documentType: "RECURSO",
    difficulty: "MEDIUM",
    quality: "LIGHT_ISSUES",
    scenario: "Reafirmação da DER seria útil, mas não foi considerada apesar de haver tempo posterior indicado.",
    plantedIssues: ["não exploração da reafirmação da DER"],
    expectedFindings: ["oportunidade argumentativa não explorada"],
    expectedScoreRange: { min: 72, max: 84 },
  },

  {
    id: "RGPS-010",
    domain: "RGPS",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Benefício por incapacidade com discussão sobre qualidade de segurado, mas sem enfrentar período de graça.",
    plantedIssues: ["período de graça ignorado"],
    expectedFindings: ["qualidade de segurado mal fundamentada"],
    expectedScoreRange: { min: 64, max: 78 },
  },

  {
    id: "RGPS-011",
    domain: "RGPS",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Aposentadoria com carência demonstrada mês a mês e documentos bem organizados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 90, max: 97 },
  },

  {
    id: "RGPS-012",
    domain: "RGPS",
    documentType: "RECURSO",
    difficulty: "MEDIUM",
    quality: "LIGHT_ISSUES",
    scenario: "Conversão de tempo especial em comum mencionada, mas com fundamentação genérica.",
    plantedIssues: ["fundamentação superficial da conversão"],
    expectedFindings: ["tese de conversão pouco desenvolvida"],
    expectedScoreRange: { min: 72, max: 84 },
  },

  {
    id: "RGPS-013",
    domain: "RGPS",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Auxílio por incapacidade com laudos, profissão, limitações funcionais e qualidade de segurado bem descritos.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "RGPS-014",
    domain: "RGPS",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Pensão por morte com dependência econômica alegada, mas pouco demonstrada.",
    plantedIssues: ["dependência econômica fraca"],
    expectedFindings: ["prova de dependência econômica insuficiente"],
    expectedScoreRange: { min: 64, max: 78 },
  },

  {
    id: "RGPS-015",
    domain: "RGPS",
    documentType: "CUMPRIMENTO_SENTENCA",
    difficulty: "HARD",
    quality: "GOOD",
    scenario: "Cumprimento de julgado previdenciário com DIB, DIP, RMI, atrasados e critérios de correção bem explicados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 90, max: 98 },
  },

  // ── RPPS — 5 casos ────────────────────────────────────────────────────────

  {
    id: "RPPS-001",
    domain: "RPPS",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Aposentadoria de servidor com cargo efetivo, tempo de contribuição, idade e regra aplicável demonstrados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "RPPS-002",
    domain: "RPPS",
    documentType: "PETICAO_INICIAL",
    difficulty: "HARD",
    quality: "MODERATE_ISSUES",
    scenario: "Pedido de integralidade e paridade sem identificar a regra constitucional ou transição aplicável.",
    plantedIssues: ["regra de integralidade/paridade não identificada"],
    expectedFindings: ["fundamentação insuficiente da regra aplicável"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "RPPS-003",
    domain: "RPPS",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Abono de permanência com preenchimento dos requisitos de aposentadoria e permanência em atividade bem demonstrados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "RPPS-004",
    domain: "RPPS",
    documentType: "RECURSO",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Averbação por CTC mencionada, mas sem explicar origem do tempo e compatibilidade com o RPPS.",
    plantedIssues: ["averbação mal demonstrada"],
    expectedFindings: ["CTC/averbação insuficientemente enfrentada"],
    expectedScoreRange: { min: 64, max: 78 },
  },

  {
    id: "RPPS-005",
    domain: "RPPS",
    documentType: "PETICAO_INICIAL",
    difficulty: "HARD",
    quality: "GOOD",
    scenario: "Regra de transição da EC 103/2019 bem aplicada ao histórico funcional do servidor.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  // ── TRABALHISTA — 10 casos ─────────────────────────────────────────────────

  {
    id: "TRAB-001",
    domain: "TRABALHISTA",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Horas extras com jornada, cartões de ponto, intervalo e reflexos bem descritos.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "TRAB-002",
    domain: "TRABALHISTA",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Pedido de horas extras sem indicar jornada efetivamente cumprida.",
    plantedIssues: ["jornada não demonstrada"],
    expectedFindings: ["pedido de horas extras sem base fática suficiente"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "TRAB-003",
    domain: "TRABALHISTA",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Vínculo empregatício alegado, mas sem enfrentar subordinação, pessoalidade, onerosidade e habitualidade.",
    plantedIssues: ["elementos do vínculo não enfrentados"],
    expectedFindings: ["fundamentação insuficiente do vínculo empregatício"],
    expectedScoreRange: { min: 60, max: 76 },
  },

  {
    id: "TRAB-004",
    domain: "TRABALHISTA",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Equiparação salarial com paradigma, função, período e identidade de tarefas bem demonstrados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "TRAB-005",
    domain: "TRABALHISTA",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "SEVERE_ISSUES",
    scenario: "Insalubridade negada por laudo técnico, mas recurso ignora o laudo.",
    plantedIssues: ["não enfrentamento do laudo"],
    expectedFindings: ["enfrentamento insuficiente da prova técnica"],
    expectedScoreRange: { min: 55, max: 70 },
  },

  {
    id: "TRAB-006",
    domain: "TRABALHISTA",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "FGTS com extratos, período contratual e diferenças bem demonstradas.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "TRAB-007",
    domain: "TRABALHISTA",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "LIGHT_ISSUES",
    scenario: "Pejotização alegada com fatos relevantes, mas fundamentação jurídica superficial.",
    plantedIssues: ["fundamentação superficial"],
    expectedFindings: ["tese de fraude contratual pouco desenvolvida"],
    expectedScoreRange: { min: 72, max: 84 },
  },

  {
    id: "TRAB-008",
    domain: "TRABALHISTA",
    documentType: "RECURSO",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Justa causa discutida sem enfrentar proporcionalidade, imediatidade e gradação da pena.",
    plantedIssues: ["justa causa mal enfrentada"],
    expectedFindings: ["ausência de análise da proporcionalidade da penalidade"],
    expectedScoreRange: { min: 62, max: 76 },
  },

  {
    id: "TRAB-009",
    domain: "TRABALHISTA",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "GOOD",
    scenario: "Assédio moral com condutas, frequência, testemunhas e consequências descritas.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "TRAB-010",
    domain: "TRABALHISTA",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Verbas rescisórias com datas, parcelas, base de cálculo e pedidos bem organizados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 90, max: 97 },
  },

  // ── TRIBUTARIO — 10 casos ─────────────────────────────────────────────────

  {
    id: "TRIB-001",
    domain: "TRIBUTARIO",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Repetição de indébito com pagamento indevido, período, base legal e cálculo bem demonstrados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "TRIB-002",
    domain: "TRIBUTARIO",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "MODERATE_ISSUES",
    scenario: "Prescrição alegada sem enfrentar parcelamento anterior como possível causa interruptiva/suspensiva.",
    plantedIssues: ["marco interruptivo ignorado"],
    expectedFindings: ["prescrição insuficientemente fundamentada"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "TRIB-003",
    domain: "TRIBUTARIO",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "GOOD",
    scenario: "Decadência bem analisada com fato gerador, lançamento e regra aplicável.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "TRIB-004",
    domain: "TRIBUTARIO",
    documentType: "RECURSO",
    subtype: "EMBARGOS",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Embargos à execução fiscal que mencionam CDA, mas não discutem liquidez, certeza ou exigibilidade.",
    plantedIssues: ["CDA não enfrentada"],
    expectedFindings: ["fundamentação insuficiente contra a CDA"],
    expectedScoreRange: { min: 62, max: 76 },
    notes: "Tipo original: EMBARGOS — mapeado para RECURSO por não constar no enum DocumentType.",
  },

  {
    id: "TRIB-005",
    domain: "TRIBUTARIO",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "MODERATE_ISSUES",
    scenario: "Responsabilidade tributária de sócio alegada de forma genérica, sem fatos de gestão ou dissolução irregular.",
    plantedIssues: ["responsabilidade tributária genérica"],
    expectedFindings: ["ausência de suporte fático para redirecionamento/responsabilidade"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "TRIB-006",
    domain: "TRIBUTARIO",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "GOOD",
    scenario: "Imunidade tributária com natureza da entidade, finalidade e documentos bem indicados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "TRIB-007",
    domain: "TRIBUTARIO",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Compensação tributária pedida sem demonstrar crédito líquido, certo e procedimento aplicável.",
    plantedIssues: ["requisitos da compensação ignorados"],
    expectedFindings: ["pedido de compensação insuficientemente instruído"],
    expectedScoreRange: { min: 60, max: 76 },
  },

  {
    id: "TRIB-008",
    domain: "TRIBUTARIO",
    documentType: "PETICAO_INICIAL",
    subtype: "EXCECAO_PRE_EXECUTIVIDADE",
    difficulty: "MEDIUM",
    quality: "GOOD",
    scenario: "Redirecionamento questionado com base em ausência de dissolução irregular e prova documental pré-constituída.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
    notes: "Tipo original: EXCECAO_PRE_EXECUTIVIDADE — mapeado para PETICAO_INICIAL por não constar no enum DocumentType.",
  },

  {
    id: "TRIB-009",
    domain: "TRIBUTARIO",
    documentType: "PETICAO_INICIAL",
    subtype: "EXCECAO_PRE_EXECUTIVIDADE",
    difficulty: "HARD",
    quality: "LIGHT_ISSUES",
    scenario: "Exceção de pré-executividade com tese possível, mas argumentação pouco objetiva.",
    plantedIssues: ["argumentação fraca"],
    expectedFindings: ["tese defensiva pouco desenvolvida"],
    expectedScoreRange: { min: 70, max: 82 },
    notes: "Tipo original: EXCECAO_PRE_EXECUTIVIDADE — mapeado para PETICAO_INICIAL por não constar no enum DocumentType.",
  },

  {
    id: "TRIB-010",
    domain: "TRIBUTARIO",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "GOOD",
    scenario: "Recurso tributário com prescrição, CDA, modulação de efeitos e jurisprudência bem articuladas.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 90, max: 98 },
  },

  // ── FAMILIA — 10 casos ────────────────────────────────────────────────────

  {
    id: "FAM-001",
    domain: "FAMILIA",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Guarda compartilhada com foco no melhor interesse da criança e convivência equilibrada.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "FAM-002",
    domain: "FAMILIA",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Alimentos pedidos sem demonstração das necessidades do alimentando.",
    plantedIssues: ["necessidade não demonstrada"],
    expectedFindings: ["binômio necessidade/possibilidade incompleto"],
    expectedScoreRange: { min: 62, max: 76 },
  },

  {
    id: "FAM-003",
    domain: "FAMILIA",
    documentType: "CONTESTACAO",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Contestação de alimentos sem demonstrar a possibilidade econômica do alimentante.",
    plantedIssues: ["possibilidade econômica não enfrentada"],
    expectedFindings: ["ausência de prova sobre capacidade financeira"],
    expectedScoreRange: { min: 62, max: 76 },
  },

  {
    id: "FAM-004",
    domain: "FAMILIA",
    documentType: "PETICAO_INICIAL",
    difficulty: "HARD",
    quality: "MODERATE_ISSUES",
    scenario: "Alienação parental alegada com afirmações graves, mas sem elementos mínimos de prova.",
    plantedIssues: ["provas frágeis"],
    expectedFindings: ["alegação grave sem lastro probatório suficiente"],
    expectedScoreRange: { min: 58, max: 72 },
  },

  {
    id: "FAM-005",
    domain: "FAMILIA",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "GOOD",
    scenario: "União estável com convivência pública, duradoura, contínua e intenção familiar demonstradas.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "FAM-006",
    domain: "FAMILIA",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Investigação de paternidade com pedido de DNA e elementos mínimos de relação entre as partes.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "FAM-007",
    domain: "FAMILIA",
    documentType: "CUMPRIMENTO_SENTENCA",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Execução de alimentos sem clareza sobre parcelas vencidas, atualização e rito escolhido.",
    plantedIssues: ["falha procedimental"],
    expectedFindings: ["pedido executivo pouco claro"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "FAM-008",
    domain: "FAMILIA",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Divórcio consensual com partilha, guarda, alimentos e convivência bem delimitados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 90, max: 97 },
  },

  {
    id: "FAM-009",
    domain: "FAMILIA",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "LIGHT_ISSUES",
    scenario: "Partilha de bens com indicação de patrimônio, mas fundamentação superficial sobre regime de bens.",
    plantedIssues: ["fundamentação superficial"],
    expectedFindings: ["regime de bens pouco desenvolvido"],
    expectedScoreRange: { min: 72, max: 84 },
  },

  {
    id: "FAM-010",
    domain: "FAMILIA",
    documentType: "PETICAO_INICIAL",
    difficulty: "HARD",
    quality: "GOOD",
    scenario: "Ação de guarda, alimentos e convivência com estudo psicossocial, rotina da criança e melhor interesse bem articulados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 90, max: 98 },
  },

  // ── CONSUMIDOR — 10 casos ─────────────────────────────────────────────────

  {
    id: "CONS-001",
    domain: "CONSUMIDOR",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Negativação indevida com prova de inexistência do débito, inscrição e dano demonstrados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "CONS-002",
    domain: "CONSUMIDOR",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Vício de produto alegado sem demonstrar reclamação, prazo decadencial ou tentativa de solução.",
    plantedIssues: ["vício mal demonstrado"],
    expectedFindings: ["ausência de narrativa probatória do vício"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "CONS-003",
    domain: "CONSUMIDOR",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Falha em serviço de transporte com atraso, dano material e nexo causal bem demonstrados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "CONS-004",
    domain: "CONSUMIDOR",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "LIGHT_ISSUES",
    scenario: "Dano moral por cobrança abusiva com boa narrativa, mas pouca individualização do abalo.",
    plantedIssues: ["dano moral pouco individualizado"],
    expectedFindings: ["fundamentação do dano moral superficial"],
    expectedScoreRange: { min: 72, max: 84 },
  },

  {
    id: "CONS-005",
    domain: "CONSUMIDOR",
    documentType: "CONTESTACAO",
    difficulty: "HARD",
    quality: "GOOD",
    scenario: "Defesa com culpa exclusiva do consumidor e ausência de nexo causal bem demonstradas.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "CONS-006",
    domain: "CONSUMIDOR",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Contrato bancário com alegação de abusividade, mas sem indicar cláusulas ou encargos questionados.",
    plantedIssues: ["abusividade genérica"],
    expectedFindings: ["pedido revisional sem delimitação concreta"],
    expectedScoreRange: { min: 58, max: 72 },
  },

  {
    id: "CONS-007",
    domain: "CONSUMIDOR",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Repetição de indébito com cobrança indevida, pagamentos e pedido de devolução bem delimitados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "CONS-008",
    domain: "CONSUMIDOR",
    documentType: "RECURSO",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Recurso pede devolução em dobro sem enfrentar má-fé ou engano justificável.",
    plantedIssues: ["devolução em dobro mal fundamentada"],
    expectedFindings: ["ausência de fundamentação para repetição em dobro"],
    expectedScoreRange: { min: 62, max: 76 },
  },

  {
    id: "CONS-009",
    domain: "CONSUMIDOR",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "LIGHT_ISSUES",
    scenario: "Falha de serviço digital com prints e protocolos, mas sem organizar cronologia.",
    plantedIssues: ["cronologia confusa"],
    expectedFindings: ["narrativa fática pouco organizada"],
    expectedScoreRange: { min: 72, max: 84 },
  },

  {
    id: "CONS-010",
    domain: "CONSUMIDOR",
    documentType: "PETICAO_INICIAL",
    difficulty: "HARD",
    quality: "GOOD",
    scenario: "Ação consumerista complexa com falha de serviço, dano material, dano moral, inversão do ônus e nexo bem articulados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 90, max: 98 },
  },

  // ── CRIMINAL — 10 casos ───────────────────────────────────────────────────

  {
    id: "CRIM-001",
    domain: "CRIMINAL",
    documentType: "RECURSO",
    difficulty: "MEDIUM",
    quality: "GOOD",
    scenario: "Apelação criminal com materialidade, autoria, dosimetria e regime inicial bem enfrentados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "CRIM-002",
    domain: "CRIMINAL",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "MODERATE_ISSUES",
    scenario: "Recurso criminal contesta condenação, mas não enfrenta prova de autoria usada na sentença.",
    plantedIssues: ["autoria não enfrentada"],
    expectedFindings: ["ausência de enfrentamento da prova central de autoria"],
    expectedScoreRange: { min: 58, max: 72 },
  },

  {
    id: "CRIM-003",
    domain: "CRIMINAL",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "MODERATE_ISSUES",
    scenario: "Nulidade por reconhecimento pessoal alegada sem confrontar procedimento do art. 226 do CPP.",
    plantedIssues: ["nulidade mal fundamentada"],
    expectedFindings: ["tese de reconhecimento pessoal insuficientemente desenvolvida"],
    expectedScoreRange: { min: 62, max: 76 },
  },

  {
    id: "CRIM-004",
    domain: "CRIMINAL",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "GOOD",
    scenario: "Habeas corpus contra prisão preventiva com ausência de fundamentação concreta bem demonstrada.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "CRIM-005",
    domain: "CRIMINAL",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "MODERATE_ISSUES",
    scenario: "Dosimetria impugnada de forma genérica, sem analisar circunstâncias judiciais do art. 59.",
    plantedIssues: ["dosimetria genérica"],
    expectedFindings: ["impugnação da pena-base insuficiente"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "CRIM-006",
    domain: "CRIMINAL",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "LIGHT_ISSUES",
    scenario: "Pedido de ANPP menciona primariedade e pena mínima, mas não analisa confissão formal.",
    plantedIssues: ["ANPP incompleto"],
    expectedFindings: ["requisitos do ANPP parcialmente enfrentados"],
    expectedScoreRange: { min: 70, max: 82 },
  },

  {
    id: "CRIM-007",
    domain: "CRIMINAL",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "GOOD",
    scenario: "Cadeia de custódia questionada com datas, lacres, responsáveis e inconsistências documentadas.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "CRIM-008",
    domain: "CRIMINAL",
    documentType: "RECURSO",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Prova ilícita alegada sem explicar origem da ilicitude nem nexo com a condenação.",
    plantedIssues: ["prova ilícita mal fundamentada"],
    expectedFindings: ["nulidade probatória insuficientemente demonstrada"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "CRIM-009",
    domain: "CRIMINAL",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Pedido de liberdade provisória com residência fixa, primariedade, ausência de risco e medidas cautelares alternativas.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "CRIM-010",
    domain: "CRIMINAL",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "GOOD",
    scenario: "Apelação robusta com materialidade, autoria, nulidade subsidiária, dosimetria e regime bem organizados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 90, max: 98 },
  },

  // ── FAZENDA_PUBLICA — 10 casos ────────────────────────────────────────────

  {
    id: "FAZ-001",
    domain: "FAZENDA_PUBLICA",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Servidor público pede adicional com lei local, vínculo e período bem demonstrados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "FAZ-002",
    domain: "FAZENDA_PUBLICA",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Responsabilidade civil do Estado por omissão, mas sem demonstrar nexo causal específico.",
    plantedIssues: ["nexo causal fraco"],
    expectedFindings: ["responsabilidade estatal insuficientemente fundamentada"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "FAZ-003",
    domain: "FAZENDA_PUBLICA",
    documentType: "RECURSO",
    difficulty: "MEDIUM",
    quality: "GOOD",
    scenario: "Concurso público com preterição comprovada por ordem de classificação e contratações temporárias.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "FAZ-004",
    domain: "FAZENDA_PUBLICA",
    documentType: "CUMPRIMENTO_SENTENCA",
    difficulty: "HARD",
    quality: "MODERATE_ISSUES",
    scenario: "Cumprimento contra Fazenda Pública sem distinguir RPV, precatório e critérios de correção.",
    plantedIssues: ["regime de pagamento não enfrentado"],
    expectedFindings: ["cumprimento contra Fazenda mal estruturado"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "FAZ-005",
    domain: "FAZENDA_PUBLICA",
    documentType: "CONTESTACAO",
    difficulty: "MEDIUM",
    quality: "LIGHT_ISSUES",
    scenario: "Contestação invoca prescrição quinquenal, mas sem demonstrar termo inicial.",
    plantedIssues: ["prescrição superficial"],
    expectedFindings: ["marco inicial prescricional pouco desenvolvido"],
    expectedScoreRange: { min: 70, max: 82 },
  },

  {
    id: "FAZ-006",
    domain: "FAZENDA_PUBLICA",
    documentType: "PETICAO_INICIAL",
    difficulty: "HARD",
    quality: "GOOD",
    scenario: "Licitação com ilegalidade concreta no edital e prejuízo competitivo bem demonstrados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "FAZ-007",
    domain: "FAZENDA_PUBLICA",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Ato administrativo impugnado sem distinguir ato vinculado e discricionário.",
    plantedIssues: ["controle do ato mal fundamentado"],
    expectedFindings: ["fundamentação insuficiente sobre limites do controle judicial"],
    expectedScoreRange: { min: 62, max: 76 },
  },

  {
    id: "FAZ-008",
    domain: "FAZENDA_PUBLICA",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "GOOD",
    scenario: "Recurso sobre servidor temporário com nulidade contratual, verbas devidas e tese bem delimitada.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "FAZ-009",
    domain: "FAZENDA_PUBLICA",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Pedido contra Administração com interesse público mencionado apenas de forma retórica.",
    plantedIssues: ["argumentação genérica"],
    expectedFindings: ["fundamentação de interesse público abstrata"],
    expectedScoreRange: { min: 64, max: 78 },
  },

  {
    id: "FAZ-010",
    domain: "FAZENDA_PUBLICA",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "GOOD",
    scenario: "Recurso com prescrição, regime de pagamento, lei local e provas administrativas bem articuladas.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 90, max: 98 },
  },

  // ── AMBIENTAL — 5 casos ───────────────────────────────────────────────────

  {
    id: "AMB-001",
    domain: "AMBIENTAL",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "GOOD",
    scenario: "Dano ambiental em APP com auto de infração, fotos, perícia e pedido de reparação integral.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "AMB-002",
    domain: "AMBIENTAL",
    documentType: "CONTESTACAO",
    difficulty: "HARD",
    quality: "MODERATE_ISSUES",
    scenario: "Contestação nega responsabilidade ambiental, mas não enfrenta responsabilidade objetiva e nexo causal.",
    plantedIssues: ["responsabilidade objetiva ignorada"],
    expectedFindings: ["defesa ambiental juridicamente incompleta"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "AMB-003",
    domain: "AMBIENTAL",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "LIGHT_ISSUES",
    scenario: "Licenciamento ambiental discutido com documentos, mas sem explicar condicionantes violadas.",
    plantedIssues: ["condicionantes não individualizadas"],
    expectedFindings: ["violação ambiental pouco delimitada"],
    expectedScoreRange: { min: 70, max: 82 },
  },

  {
    id: "AMB-004",
    domain: "AMBIENTAL",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "MODERATE_ISSUES",
    scenario: "Auto de infração ambiental impugnado sem discutir prescrição administrativa ou regularidade do procedimento.",
    plantedIssues: ["procedimento administrativo ignorado"],
    expectedFindings: ["impugnação administrativa insuficiente"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "AMB-005",
    domain: "AMBIENTAL",
    documentType: "PETICAO_INICIAL",
    difficulty: "HARD",
    quality: "GOOD",
    scenario: "Ação ambiental com dano, nexo, responsabilidade solidária, perícia e medidas de recuperação bem articuladas.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 90, max: 98 },
  },

  // ── CIVEL — 10 casos ──────────────────────────────────────────────────────

  {
    id: "CIV-001",
    domain: "CIVEL",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Cobrança contratual com contrato, inadimplemento, vencimento e valor bem demonstrados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "CIV-002",
    domain: "CIVEL",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Indenização por dano material sem prova clara do prejuízo econômico.",
    plantedIssues: ["dano material não comprovado"],
    expectedFindings: ["ausência de demonstração do prejuízo"],
    expectedScoreRange: { min: 60, max: 74 },
  },

  {
    id: "CIV-003",
    domain: "CIVEL",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "GOOD",
    scenario: "Obrigação de fazer com contrato, inadimplemento e tutela de urgência bem fundamentados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "CIV-004",
    domain: "CIVEL",
    documentType: "CONTESTACAO",
    difficulty: "MEDIUM",
    quality: "LIGHT_ISSUES",
    scenario: "Contestação invoca prescrição, mas sem indicar termo inicial e prazo aplicável.",
    plantedIssues: ["prescrição superficial"],
    expectedFindings: ["prejudicial de prescrição mal desenvolvida"],
    expectedScoreRange: { min: 70, max: 82 },
  },

  {
    id: "CIV-005",
    domain: "CIVEL",
    documentType: "PETICAO_INICIAL",
    difficulty: "HARD",
    quality: "MODERATE_ISSUES",
    scenario: "Usucapião com posse alegada, mas sem delimitar tempo, animus domini e cadeia possessória.",
    plantedIssues: ["posse mal demonstrada"],
    expectedFindings: ["requisitos da usucapião insuficientemente demonstrados"],
    expectedScoreRange: { min: 58, max: 72 },
  },

  {
    id: "CIV-006",
    domain: "CIVEL",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "GOOD",
    scenario: "Responsabilidade civil com conduta, dano, nexo causal e culpa bem estruturados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "CIV-007",
    domain: "CIVEL",
    documentType: "RECURSO",
    difficulty: "HARD",
    quality: "MODERATE_ISSUES",
    scenario: "Recurso contra sentença de improcedência sem enfrentar fundamento central da decisão.",
    plantedIssues: ["fundamento central ignorado"],
    expectedFindings: ["dialeticidade recursal insuficiente"],
    expectedScoreRange: { min: 55, max: 70 },
  },

  {
    id: "CIV-008",
    domain: "CIVEL",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "LIGHT_ISSUES",
    scenario: "Lucros cessantes pedidos com boa narrativa, mas cálculo pouco explicado.",
    plantedIssues: ["lucros cessantes mal quantificados"],
    expectedFindings: ["quantificação do prejuízo insuficiente"],
    expectedScoreRange: { min: 70, max: 82 },
  },

  {
    id: "CIV-009",
    domain: "CIVEL",
    documentType: "CONTESTACAO",
    difficulty: "MEDIUM",
    quality: "GOOD",
    scenario: "Defesa contratual com mora do credor, exceção do contrato não cumprido e documentos adequados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 86, max: 94 },
  },

  {
    id: "CIV-010",
    domain: "CIVEL",
    documentType: "PETICAO_INICIAL",
    difficulty: "HARD",
    quality: "GOOD",
    scenario: "Ação cível complexa com tutela de urgência, provas, pedidos subsidiários e nexo causal bem articulados.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 90, max: 98 },
  },

  // ── JUIZADO_ESPECIAL — 5 casos ─────────────────────────────────────────────

  {
    id: "JEC-001",
    domain: "JUIZADO_ESPECIAL",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Ação simples de consumo dentro do valor de alçada, com prova documental suficiente.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "JEC-002",
    domain: "JUIZADO_ESPECIAL",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Ação proposta no Juizado com necessidade clara de perícia complexa.",
    plantedIssues: ["inadequação ao rito do Juizado"],
    expectedFindings: ["possível incompetência do Juizado por complexidade probatória"],
    expectedScoreRange: { min: 58, max: 72 },
  },

  {
    id: "JEC-003",
    domain: "JUIZADO_ESPECIAL",
    documentType: "RECURSO",
    difficulty: "MEDIUM",
    quality: "LIGHT_ISSUES",
    scenario: "Recurso inominado com razões existentes, mas pedidos recursais pouco claros.",
    plantedIssues: ["pedido recursal confuso"],
    expectedFindings: ["conclusão recursal pouco delimitada"],
    expectedScoreRange: { min: 70, max: 82 },
  },

  {
    id: "JEC-004",
    domain: "JUIZADO_ESPECIAL",
    documentType: "PETICAO_INICIAL",
    difficulty: "EASY",
    quality: "GOOD",
    scenario: "Cobrança simples com contrato, comprovante de entrega e valor dentro da alçada.",
    plantedIssues: [],
    expectedFindings: [],
    expectedScoreRange: { min: 88, max: 96 },
  },

  {
    id: "JEC-005",
    domain: "JUIZADO_ESPECIAL",
    documentType: "PETICAO_INICIAL",
    difficulty: "MEDIUM",
    quality: "MODERATE_ISSUES",
    scenario: "Pedido de dano moral em Juizado com narrativa genérica e sem individualização do abalo.",
    plantedIssues: ["dano moral genérico"],
    expectedFindings: ["dano moral insuficientemente fundamentado"],
    expectedScoreRange: { min: 62, max: 76 },
  },
];
