export enum FindingType {
  INSUFFICIENT_FACTUAL_SUPPORT = "INSUFFICIENT_FACTUAL_SUPPORT",
  CONCLUSORY_ASSERTION = "CONCLUSORY_ASSERTION",
  LOGICAL_GAP = "LOGICAL_GAP",
  MISSING_DOCUMENT_SUPPORT = "MISSING_DOCUMENT_SUPPORT",
  MISSING_DATE_SUPPORT = "MISSING_DATE_SUPPORT",
  MISSING_CALCULATION = "MISSING_CALCULATION",
  UNADDRESSED_VULNERABILITY = "UNADDRESSED_VULNERABILITY",
  COUNTER_ARGUMENT_RISK = "COUNTER_ARGUMENT_RISK",
  WEAK_ARGUMENTATION = "WEAK_ARGUMENTATION",
  LITIGATION_RISK = "LITIGATION_RISK",
}
