export enum StrengthFindingType {
  MISSING_DEMONSTRATION          = "MISSING_DEMONSTRATION",
  MISSING_COMPARATIVE_TABLE      = "MISSING_COMPARATIVE_TABLE",
  MISSING_CALCULATION            = "MISSING_CALCULATION",
  MISSING_SUPPORTING_DOCUMENT    = "MISSING_SUPPORTING_DOCUMENT",
  MISSING_DATE_ANCHOR            = "MISSING_DATE_ANCHOR",
  MISSING_LEGAL_ANCHOR           = "MISSING_LEGAL_ANCHOR",
  UNUSED_EXTRACTED_DATA          = "UNUSED_EXTRACTED_DATA",
  FACTUAL_ENRICHMENT_OPPORTUNITY = "FACTUAL_ENRICHMENT_OPPORTUNITY",
  STRENGTHEN_ARGUMENT            = "STRENGTHEN_ARGUMENT",
  ANTICIPATE_COUNTERARGUMENT     = "ANTICIPATE_COUNTERARGUMENT",
  WEAK_FACTUAL_FOUNDATION        = "WEAK_FACTUAL_FOUNDATION",
}
