import type { DocumentElement } from "../gold-corpus-v2.types.js";
import { DocumentSection } from "../gold-corpus-v2.types.js";
import type { CaseSeedData } from "../gold-corpus-v2.types.js";
import type { FamiliaScenarioConfig } from "./familia-scenario.types.js";

function h(s: string): number {
  let n = 2166136261;
  for (let i = 0; i < s.length; i++) n = Math.imul(n ^ s.charCodeAt(i), 16777619);
  return n >>> 0;
}

function dn(seed: CaseSeedData, salt: string, min: number, range: number): number {
  return min + (h(seed.cpf + salt) % range);
}

function fmt(cents: number): string {
  return `R$ ${(cents / 100).toFixed(2).replace(".", ",")}`;
}

function conjuge(seed: CaseSeedData): string {
  const nomes = ["Carlos Eduardo Souza", "Roberto Alves Lima", "Marcos Pereira Santos", "André Figueiredo Costa"];
  return nomes[h(seed.cpf + "cj") % nomes.length];
}

function filho(seed: CaseSeedData, n: number): string {
  const nomes = ["Lucas", "Gabriel", "Matheus", "Pedro", "Beatriz", "Isabela", "Ana Clara", "Sofia"];
  return nomes[(h(seed.cpf + `f${n}`) % nomes.length)];
}

// ─── FAM-001: DIVORCIO_LITIGIOSO (GOOD) ───────────────────────────────────────
function buildDivorcioLitigioso(seed: CaseSeedData): DocumentElement[] {
  const cj = conjuge(seed);
  const anosMarriage = dn(seed, "am1", 5, 20);
  const anoUniao = 2026 - anosMarriage;
  const regimeBens = ["comunhão parcial de bens (CC art. 1.658)", "separação convencional de bens (CC art. 1.687)", "comunhão universal de bens (CC art. 1.667)"][h(seed.cpf + "rb1") % 3];
  const imovelCents = dn(seed, "im1", 20000000, 80000000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE DIVÓRCIO LITIGIOSO\n\nem face de ${cj.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, cj] },
    { id: "fatos_casamento", section: DocumentSection.DOS_FATOS, fullContent: `As partes se casaram em ${seed.baseDate} sob o regime de ${regimeBens}. Da união, que perdurou ${anosMarriage} anos, resultaram ${dn(seed, "nf1", 1, 3)} filho(s) menor(es) de idade. A convivência tornou-se insuportável a partir de ${seed.derDate}, em decorrência de ${["desentendimentos irreconciliáveis", "infidelidade conjugal", "abandono do lar conjugal", "violência doméstica"][h(seed.cpf + "mo1") % 4]}.`, lightContent: `As partes foram casadas e a convivência se tornou insuportável, justificando o divórcio.`, omittedContent: `[data do casamento, regime de bens e causa da ruptura não identificados]`, omissionDescription: "ausência de identificação da data do casamento, do regime de bens e da causa da ruptura conjugal", correctPresenceKeywords: [seed.baseDate, regimeBens.split(" ")[0], String(anosMarriage)] },
    { id: "causas_dissolucao", section: DocumentSection.DOS_FATOS, fullContent: `O art. 1.571 do CC e a EC 66/2010 dispensam a discussão de culpa para o divórcio. A separação de fato ocorreu em ${seed.derDate}. O(A) autor(a) tem interesse na dissolução do vínculo conjugal para regularizar sua situação civil e proceder à partilha dos bens comuns adquiridos na constância do casamento, notadamente o imóvel situado na ${seed.city}, avaliado em ${fmt(imovelCents)}.`, lightContent: `A dissolução do casamento é requerida com base na separação de fato das partes.`, omittedContent: `[data da separação de fato e bens comuns a partilhar não identificados]`, omissionDescription: "ausência de identificação da data da separação de fato e dos bens comuns a serem partilhados", correctPresenceKeywords: [seed.derDate, fmt(imovelCents), "EC 66"] },
    { id: "partilha_preliminar", section: DocumentSection.DO_DIREITO, fullContent: `Nos termos do CC art. 1.658, sob o regime de ${regimeBens}, comunicam-se os bens adquiridos na constância do casamento: imóvel (${fmt(imovelCents)}) e demais bens móveis a serem inventariados. A partilha igualitária (50/50) é o regime supletivo. O(A) autor(a) requer a concessão de alimentos provisórios no valor de ${fmt(dn(seed, "alp1", 150000, 300000))} até a dissolução final.`, lightContent: `Os bens comuns serão partilhados conforme o regime de bens do casamento.`, omittedContent: `[bens a partilhar, valores e critérios de divisão não identificados]`, omissionDescription: "ausência de identificação dos bens a partilhar com valores e critérios de divisão segundo o regime de bens", correctPresenceKeywords: ["CC art. 1.658", "partilha", "imóvel"] },
    { id: "pedidos_divorcio", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) decretação do divórcio (EC 66/2010; CC art. 1.571 IV); (b) partilha dos bens comuns (50% para cada parte); (c) fixação de alimentos provisórios; (d) guarda compartilhada dos filhos menores; (e) regulamentação de visitas; (f) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer o divórcio com partilha de bens e fixação de alimentos.`, omittedContent: `[pedidos do divórcio sem especificação do regime de partilha e dos alimentos]`, omissionDescription: "pedidos do divórcio litigioso sem especificação do regime de partilha e do valor dos alimentos pleiteados", correctPresenceKeywords: ["EC 66", "CC art. 1.571", "alimentos"] },
  ];
}

// ─── FAM-002: ALIMENTOS_FILHOS (MODERATE) ─────────────────────────────────────
function buildAlimentosFilhos(seed: CaseSeedData): DocumentElement[] {
  const cj = conjuge(seed);
  const f1 = filho(seed, 1);
  const idadeFilho = dn(seed, "id2", 3, 12);
  const alimentosCents = dn(seed, "al2", 100000, 400000);
  const rendaReuCents = dn(seed, "rr2", 300000, 1500000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, na qualidade de representante legal do menor ${f1.toUpperCase()}, vem propor\n\nAÇÃO DE ALIMENTOS\n\nem face de ${cj.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, f1] },
    { id: "fatos_filiacao", section: DocumentSection.DOS_FATOS, fullContent: `${f1}, ${idadeFilho} anos, é filho(a) biológico(a) de ${cj}, conforme certidão de nascimento (matrícula ${dn(seed, "mat2", 100000, 899999)}). As partes encerraram a convivência em ${seed.baseDate}, ficando a guarda do menor com o(a) autor(a). O réu/ré, que aufere renda mensal de ${fmt(rendaReuCents)}, jamais contribuiu espontaneamente para o sustento do filho.`, lightContent: `O alimentando é filho do réu/ré e necessita de alimentos para seu sustento.`, omittedContent: `[filiação, data de separação e renda do alimentante não identificadas com precisão]`, omissionDescription: "ausência de identificação precisa da filiação, da data de separação e da renda do alimentante para fundamentar o pedido de alimentos", correctPresenceKeywords: [f1, String(idadeFilho), seed.baseDate] },
    { id: "demonstrativo_necessidades", section: DocumentSection.DOS_FATOS, fullContent: `Necessidades mensais do menor ${f1} (${idadeFilho} anos):\n• Alimentação: ${fmt(dn(seed, "a2a", 40000, 30000))}/mês\n• Escola/mensalidade: ${fmt(dn(seed, "a2e", 50000, 100000))}/mês\n• Material escolar: ${fmt(dn(seed, "a2m", 10000, 15000))}/mês\n• Saúde/plano médico: ${fmt(dn(seed, "a2s", 15000, 20000))}/mês\n• Vestuário e lazer: ${fmt(dn(seed, "a2v", 20000, 25000))}/mês\n• Total necessário: ${fmt(alimentosCents)}/mês (binômio necessidade-possibilidade: CC art. 1.694 §1.º)`, lightContent: `As necessidades do alimentando justificam a fixação de alimentos no valor pleiteado.`, omittedContent: `[demonstrativo das necessidades do alimentando com itens e valores não apresentado]`, omissionDescription: "ausência de demonstrativo das necessidades mensais do alimentando com itens individualizados e valores (educação, saúde, alimentação, vestuário)", correctPresenceKeywords: [fmt(alimentosCents), "CC art. 1.694", f1] },
    { id: "direito_alimentos", section: DocumentSection.DO_DIREITO, fullContent: `O CC arts. 1.694 a 1.710 e o ECA arts. 22 e 23 consagram o dever alimentar dos pais. O binômio necessidade-possibilidade (CC art. 1.694 §1.º) orienta a fixação. A renda do alimentante de ${fmt(rendaReuCents)} suporta o encargo de ${fmt(alimentosCents)}/mês, correspondente a ${Math.round(alimentosCents / rendaReuCents * 100)}% dos seus rendimentos. A Súmula 309 do STJ orienta a prisão civil em caso de inadimplemento.`, lightContent: `O dever alimentar dos pais está previsto no CC e no ECA, devendo ser fixado conforme o binômio necessidade-possibilidade.`, omittedContent: `[fundamento legal dos alimentos e demonstração do binômio necessidade-possibilidade não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal dos alimentos e da demonstração do binômio necessidade-possibilidade com valores concretos", correctPresenceKeywords: ["CC art. 1.694", "ECA", "Súmula 309"] },
    { id: "pedidos_alimentos", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) fixação de alimentos provisórios de ${fmt(alimentosCents)}/mês (CPC art. 303); (b) citação do réu/ré para oferecer resposta; (c) ao final, condenação em alimentos definitivos; (d) desconto em folha (Lei 5.478/1968 art. 17); (e) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a fixação de alimentos provisórios e definitivos para o menor alimentando.`, omittedContent: `[pedido de alimentos sem valor especificado e sem indicação da forma de pagamento]`, omissionDescription: "pedido de alimentos sem especificação do valor pretendido e da forma de pagamento (desconto em folha ou depósito)", correctPresenceKeywords: [fmt(alimentosCents), "CPC art. 303", "Lei 5.478"] },
  ];
}

// ─── FAM-003: GUARDA_COMPARTILHADA (SEVERE) ───────────────────────────────────
function buildGuardaCompartilhada(seed: CaseSeedData): DocumentElement[] {
  const cj = conjuge(seed);
  const f1 = filho(seed, 1);
  const idadeFilho = dn(seed, "id3", 4, 10);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, apresenta\n\nRECURSO DE APELAÇÃO\n\nem face de sentença que negou a guarda compartilhada de ${f1}\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, f1] },
    { id: "decisao_recorrida_guarda", section: DocumentSection.DOS_FATOS, fullContent: `A sentença recorrida deferiu a guarda unilateral de ${f1} (${idadeFilho} anos) ao(à) ${cj}, negando a guarda compartilhada pleiteada pelo recorrente, sob o argumento de "conflito entre os genitores". O recorrente aponta que o conflito não é crônico e que a guarda compartilhada é a regra (CC art. 1.584 §2.º; Lei 13.058/2014), devendo ser afastada apenas em casos excepcionais de risco.`, lightContent: `A sentença negou a guarda compartilhada por entender que o conflito entre os genitores a inviabilizaria.`, omittedContent: `[sentença recorrida e fundamento para negar a guarda compartilhada não identificados]`, omissionDescription: "ausência de identificação da sentença recorrida e do fundamento utilizado para negar a guarda compartilhada de " + f1, correctPresenceKeywords: [f1, "CC art. 1.584", "guarda compartilhada"] },
    { id: "laudo_psicossocial", section: DocumentSection.DOS_FATOS, fullContent: `Laudo psicossocial elaborado pela equipe multiprofissional do Tribunal de Justiça de ${seed.city} (Processo n.º ${seed.processNumber}) concluiu que: (a) ${f1} tem vínculo afetivo com ambos os genitores; (b) o recorrente é referência positiva para a criança; (c) a guarda compartilhada é recomendável, devendo ser implementada gradualmente com apoio terapêutico.`, lightContent: `O laudo psicossocial avaliou a situação familiar e a relação de ${f1} com ambos os genitores.`, omittedContent: `[laudo psicossocial que avalia a aptidão dos genitores e a viabilidade da guarda compartilhada não mencionado]`, omissionDescription: "ausência de menção ao laudo psicossocial que avalia a aptidão dos genitores e a viabilidade da guarda compartilhada de " + f1, correctPresenceKeywords: [f1, "laudo psicossocial", "vínculo afetivo"] },
    { id: "historico_convivencia", section: DocumentSection.DOS_FATOS, fullContent: `O recorrente comprova que esteve presente na vida de ${f1} desde o nascimento: (a) acompanhou consultas médicas (${dn(seed, "cons3", 10, 30)} registros); (b) participou de reuniões escolares; (c) realizou atividades de lazer semanais com a criança; (d) não possui antecedentes de violência doméstica (certidão negativa judicial).`, lightContent: `O recorrente tem histórico de convivência regular com o filho.`, omittedContent: "", omissionDescription: "ausência de documentação do histórico de convivência do recorrente com o filho, fundamental para demonstrar a aptidão para a guarda compartilhada", absentContent: null, correctPresenceKeywords: ["consultas médicas", "reuniões escolares", f1] },
    { id: "pedido_recursal_guarda", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer o provimento do apelo para: (a) decretar a guarda compartilhada de ${f1} (CC art. 1.584 §2.º); (b) estabelecer residência alternada quinzenal; (c) manter alimentos no valor atual; (d) honorários recursais.`, lightContent: `Requer a reforma da sentença para estabelecer a guarda compartilhada do menor.`, omittedContent: `[pedido recursal de guarda compartilhada sem identificação da criança e da modalidade pretendida]`, omissionDescription: "pedido recursal de guarda compartilhada sem identificação do menor e da modalidade de guarda e residência pretendida", correctPresenceKeywords: [f1, "CC art. 1.584", "residência alternada"] },
  ];
}

// ─── FAM-004: REGULAMENTACAO_VISITAS (MODERATE) ───────────────────────────────
function buildRegulamentacaoVisitas(seed: CaseSeedData): DocumentElement[] {
  const cj = conjuge(seed);
  const f1 = filho(seed, 1);
  const idadeFilho = dn(seed, "id4", 5, 10);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nREGULAMENTAÇÃO DE VISITAS\n\nem face de ${cj.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, cj] },
    { id: "fatos_separacao", section: DocumentSection.DOS_FATOS, fullContent: `As partes se separaram em ${seed.baseDate}, ficando a guarda de ${f1} (${idadeFilho} anos) com o(a) réu(ré). Desde a separação, o(a) autor(a) tem sido impedido(a) de exercer o direito de visitas ao filho, sob alegação de que as visitas seriam prejudiciais à criança — argumento sem fundamento e que configura alienação parental (Lei 12.318/2010).`, lightContent: `O(A) autor(a) tem sido impedido(a) de visitar o filho desde a separação.`, omittedContent: `[data da separação, guarda atribuída e impedimentos às visitas não identificados]`, omissionDescription: "ausência de identificação da data da separação, de quem detém a guarda e dos episódios concretos de impedimento às visitas", correctPresenceKeywords: [seed.baseDate, f1, "alienação parental"] },
    { id: "justificativa_visitas", section: DocumentSection.DOS_FATOS, fullContent: `O autor(a) propõe regulamentação de visitas: (a) fins de semana alternados (sexta 18h a domingo 18h); (b) metade das férias escolares; (c) datas festivas alternadas (aniversário do filho, Natal, Ano Novo, Dia dos Pais/Mães); (d) uma tarde semanal fixa. A proposta é compatível com a idade de ${f1} (${idadeFilho} anos) e com a distância entre as residências (${dn(seed, "dist4", 5, 25)} km).`, lightContent: `O(A) autor(a) propõe regulamentação de visitas periódicas ao filho.`, omittedContent: `[proposta concreta de regulamentação de visitas com horários e datas específicas não apresentada]`, omissionDescription: "ausência de proposta concreta de regulamentação de visitas com especificação de horários, dias e datas festivas", correctPresenceKeywords: [String(idadeFilho), "fins de semana", "férias"] },
    { id: "direito_visitas", section: DocumentSection.DO_DIREITO, fullContent: `O CC art. 1.589 e o ECA art. 19 garantem ao genitor que não detém a guarda o direito de visitas e de convivência com o filho. O direito de convivência familiar é direito fundamental da criança (CF/88 art. 227; ECA art. 4.º). O impedimento injustificado configura alienação parental (Lei 12.318/2010 art. 2.º) e pode implicar alteração da guarda (art. 6.º).`, lightContent: `O direito de visitas ao filho é garantido pelo CC e pelo ECA como direito fundamental da criança.`, omittedContent: `[fundamento legal do direito de visitas e consequências do impedimento injustificado não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal do direito de visitas e das consequências jurídicas do impedimento injustificado (alienação parental)", correctPresenceKeywords: ["CC art. 1.589", "ECA art. 19", "Lei 12.318"] },
    { id: "pedidos_visitas", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) regulamentação de visitas conforme proposta acima (CC art. 1.589; ECA art. 19); (b) tutela de urgência para visitas imediatas ao filho; (c) aplicação das sanções da Lei 12.318/2010 em caso de descumprimento; (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a regulamentação das visitas ao filho e a aplicação das sanções em caso de descumprimento.`, omittedContent: `[pedido de regulamentação de visitas sem proposta concreta de horários e sanções]`, omissionDescription: "pedido de regulamentação de visitas sem especificação de horários concretos e das sanções em caso de descumprimento", correctPresenceKeywords: ["CC art. 1.589", "Lei 12.318", "tutela de urgência"] },
  ];
}

// ─── FAM-005: RECONHECIMENTO_UNIAO_ESTAVEL (GOOD) ─────────────────────────────
function buildReconhecimentoUniaoEstavel(seed: CaseSeedData): DocumentElement[] {
  const cj = conjuge(seed);
  const anosUniao = dn(seed, "au5", 3, 12);
  const imovelCents = dn(seed, "im5", 25000000, 100000000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE RECONHECIMENTO E DISSOLUÇÃO DE UNIÃO ESTÁVEL\n\nem face de ${cj.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, cj] },
    { id: "fatos_uniao", section: DocumentSection.DOS_FATOS, fullContent: `A autora e ${cj} conviveram em união estável de ${seed.baseDate} a ${seed.derDate} (${anosUniao} anos), com notoriedade pública, em residência comum na Rua ${["das Flores", "Ipiranga", "São Paulo", "Brasil"][h(seed.cpf + "ru5") % 4]}, n.º ${dn(seed, "nu5", 100, 900)}, ${seed.city}. Preenchem-se os requisitos do CC art. 1.723: convivência pública, contínua, duradoura e com objetivo de constituição de família.`, lightContent: `A autora e o réu conviveram em união estável por período superior a 3 anos.`, omittedContent: `[período, endereço e requisitos da união estável não identificados]`, omissionDescription: "ausência de identificação do período, do endereço comum e dos requisitos legais da união estável (CC art. 1.723)", correctPresenceKeywords: [seed.baseDate, seed.derDate, String(anosUniao)] },
    { id: "provas_convivencia", section: DocumentSection.DAS_PROVAS, fullContent: `Comprovam a união estável: (a) declaração de convivência assinada por ${dn(seed, "test5", 2, 4)} testemunhas; (b) extratos de conta conjunta no Banco ${["Itaú", "Bradesco", "Santander", "Caixa"][h(seed.cpf + "ba5") % 4]}; (c) contrato de locação em nome de ambos de ${seed.baseDate}; (d) declarações de IR com informação de companheiro; (e) fotos e comunicações do período.`, lightContent: `A convivência em união estável será comprovada por documentos e testemunhas.`, omittedContent: `[meios de prova da convivência em união estável não especificados]`, omissionDescription: "ausência de especificação dos meios de prova da convivência em união estável (documentos bancários, contratos, IR, testemunhas)", correctPresenceKeywords: ["conta conjunta", "declarações de IR", "testemunhas"] },
    { id: "direito_uniao", section: DocumentSection.DO_DIREITO, fullContent: `A CF/88 art. 226 §3.º e o CC arts. 1.723-1.727 reconhecem a união estável como entidade familiar. O regime supletivo é o da comunhão parcial de bens (CC art. 1.725), comunicando os bens adquiridos na constância da união a título oneroso, notadamente o imóvel adquirido em ${seed.derDate.slice(-4)} avaliado em ${fmt(imovelCents)}. O STJ (REsp 1.309.137/SP) consolidou a partilha igualitária.`, lightContent: `A união estável é reconhecida pela CF/88 e pelo CC, com comunicação dos bens adquiridos na constância da convivência.`, omittedContent: `[fundamento constitucional e legal da união estável e regime de bens aplicável não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento constitucional da união estável e do regime de bens aplicável com identificação dos bens comuns", correctPresenceKeywords: ["CF/88 art. 226", "CC art. 1.723", fmt(imovelCents)] },
    { id: "pedidos_uniao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) reconhecimento da união estável de ${seed.baseDate} a ${seed.derDate} (CC art. 1.723); (b) dissolução da entidade familiar; (c) partilha dos bens comuns (50% para cada parte), incluindo o imóvel (${fmt(imovelCents)}); (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer o reconhecimento e a dissolução da união estável com partilha dos bens comuns.`, omittedContent: `[pedido de reconhecimento de união estável sem identificação do período e dos bens comuns a partilhar]`, omissionDescription: "pedido de reconhecimento de união estável sem identificação do período de convivência e dos bens comuns a serem partilhados", correctPresenceKeywords: [seed.baseDate, fmt(imovelCents), "CC art. 1.723"] },
  ];
}

// ─── FAM-006: PARTILHA_BENS (MODERATE) ────────────────────────────────────────
function buildPartilhaBens(seed: CaseSeedData): DocumentElement[] {
  const cj = conjuge(seed);
  const imovel1Cents = dn(seed, "ib1", 25000000, 80000000);
  const imovel2Cents = dn(seed, "ib2", 15000000, 40000000);
  const veiculoCents = dn(seed, "vb", 4000000, 15000000);
  const totalCents = imovel1Cents + imovel2Cents + veiculoCents;
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE PARTILHA DE BENS\n\nem face de ${cj.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, cj] },
    { id: "fatos_regime_bens", section: DocumentSection.DOS_FATOS, fullContent: `As partes foram casadas sob o regime de comunhão parcial de bens (CC art. 1.658) de ${seed.baseDate} a ${seed.derDate}. Na constância do casamento, adquiriram os seguintes bens comuns: (a) imóvel residencial em ${seed.city} (${fmt(imovel1Cents)}); (b) imóvel comercial (${fmt(imovel2Cents)}); (c) veículo ${["Toyota Corolla", "Honda Civic", "Volkswagen Jetta", "Chevrolet Cruze"][h(seed.cpf + "vei") % 4]} (${fmt(veiculoCents)}). Total: ${fmt(totalCents)}.`, lightContent: `As partes foram casadas em comunhão parcial e adquiriram bens comuns durante o matrimônio.`, omittedContent: `[bens comuns adquiridos na constância do casamento e seus valores não identificados]`, omissionDescription: "ausência de identificação dos bens comuns adquiridos na constância do casamento com seus valores individuais e total do patrimônio comum", correctPresenceKeywords: [seed.baseDate, fmt(imovel1Cents), fmt(totalCents)] },
    { id: "inventario_bens", section: DocumentSection.DOS_FATOS, fullContent: `Inventário dos bens comuns:\n1. Imóvel residencial — matrícula ${dn(seed, "mat6a", 10000, 89999)} CRI ${seed.city} — valor venal: ${fmt(imovel1Cents)}\n2. Imóvel comercial — matrícula ${dn(seed, "mat6b", 10000, 89999)} CRI ${seed.city} — valor venal: ${fmt(imovel2Cents)}\n3. Veículo — RENAVAM ${dn(seed, "ren6", 10000000, 89999999)} — valor FIPE: ${fmt(veiculoCents)}\nTotal do patrimônio comum: ${fmt(totalCents)}\nParte de cada cônjuge (50%): ${fmt(Math.round(totalCents / 2))}`, lightContent: `Os bens comuns estão relacionados e serão partilhados igualmente entre os cônjuges.`, omittedContent: `[inventário dos bens comuns com matrículas, valores individuais e total do patrimônio não apresentado]`, omissionDescription: "ausência de inventário dos bens comuns com identificação das matrículas dos imóveis, RENAVAM do veículo, valores individuais e total do patrimônio", correctPresenceKeywords: [fmt(totalCents), fmt(Math.round(totalCents / 2)), "RENAVAM"] },
    { id: "direito_partilha", section: DocumentSection.DO_DIREITO, fullContent: `O CC arts. 1.658-1.666 regem a comunhão parcial de bens. Os bens adquiridos a título oneroso na constância do casamento comunicam-se (CC art. 1.660 I). A partilha igualitária (50% a cada cônjuge) é a regra (CC art. 1.658). Os imóveis devem ser avaliados pelo valor de mercado para fins de partilha (CPC art. 630).`, lightContent: `O CC regula a partilha dos bens comuns em igualdade de partes entre os cônjuges.`, omittedContent: `[fundamento legal da partilha e critérios de avaliação dos bens não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal da partilha de bens em comunhão parcial e dos critérios de avaliação dos bens", correctPresenceKeywords: ["CC art. 1.658", "CC art. 1.660", "CPC art. 630"] },
    { id: "pedidos_partilha", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) partilha dos bens comuns (${fmt(totalCents)}) em igualdade de partes; (b) adjudicação do imóvel residencial ao(à) autor(a) mediante reposição em dinheiro; (c) avaliação judicial dos bens; (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a partilha dos bens comuns em igualdade de partes com adjudicação do imóvel.`, omittedContent: `[pedido de partilha sem identificação dos bens e do critério de adjudicação]`, omissionDescription: "pedido de partilha de bens sem identificação dos bens a partilhar e do critério de adjudicação pleiteado", correctPresenceKeywords: [fmt(totalCents), "adjudicação", "avaliação"] },
  ];
}

// ─── FAM-007: ALIENACAO_PARENTAL (LIGHT) ──────────────────────────────────────
function buildAlienacaoParental(seed: CaseSeedData): DocumentElement[] {
  const cj = conjuge(seed);
  const f1 = filho(seed, 1);
  const idadeFilho = dn(seed, "id7", 5, 10);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE INIBIÇÃO À ALIENAÇÃO PARENTAL\n\nem face de ${cj.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, cj] },
    { id: "fatos_alienacao", section: DocumentSection.DOS_FATOS, fullContent: `Desde a separação em ${seed.baseDate}, o(a) réu(ré) ${cj} tem promovido alienação parental em desfavor do(a) autor(a), impedindo o contato com ${f1} (${idadeFilho} anos) e fazendo falsas imputações de abuso. A criança passou a demonstrar ansiedade e recusa às visitas — sinais clássicos de SAP (Síndrome de Alienação Parental), configurando infração ao art. 2.º da Lei 12.318/2010.`, lightContent: `O(A) réu(ré) pratica atos de alienação parental que impedem o contato do autor(a) com o filho.`, omittedContent: `[atos específicos de alienação parental com datas e episódios concretos não narrados]`, omissionDescription: "ausência de narração de atos específicos de alienação parental com datas e episódios concretos das condutas do alienador", correctPresenceKeywords: [seed.baseDate, f1, "Lei 12.318"] },
    { id: "evidencias_alienacao", section: DocumentSection.DAS_PROVAS, fullContent: `Comprovam a alienação parental: (a) laudos psicológicos de ${f1} em ${dn(seed, "lp7", 2, 4)} sessões com a Psicóloga CRP ${dn(seed, "crp7", 10000, 89999)}; (b) registro de ${dn(seed, "reg7", 5, 15)} episódios de impedimento de visitas; (c) mensagens de áudio e texto nas quais o réu/ré denigre a imagem do autor(a); (d) laudo do CAPS Infantil de ${seed.city}.`, lightContent: `A alienação parental será comprovada por laudos e registros de impedimentos às visitas.`, omittedContent: `[evidências concretas da alienação parental (laudos, mensagens, registros) não especificadas]`, omissionDescription: "ausência de especificação das evidências concretas da alienação parental (laudos psicológicos, mensagens, registros de impedimentos)", correctPresenceKeywords: ["laudos psicológicos", "CRP", "mensagens"] },
    { id: "direito_alienacao", section: DocumentSection.DO_DIREITO, fullContent: `A Lei 12.318/2010 tipifica a alienação parental (art. 2.º) e prevê sanções que vão desde advertência até a inversão da guarda (art. 6.º). O ECA art. 19 garante à criança a convivência familiar saudável. O STJ, no REsp 1.251.000/MG, reconheceu a aplicação das sanções sem necessidade de processo autônomo.`, lightContent: `A alienação parental é tipificada pela Lei 12.318/2010 e sujeita o alienador às sanções legais.`, omittedContent: `[fundamento legal da alienação parental e sanções aplicáveis não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal da alienação parental e das sanções aplicáveis ao alienador (Lei 12.318/2010)", correctPresenceKeywords: ["Lei 12.318", "art. 6.º", "REsp 1.251.000"] },
    { id: "pedidos_alienacao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) declaração da alienação parental praticada pelo(a) réu(ré) (Lei 12.318/2010 art. 2.º); (b) aplicação de multa de ${fmt(dn(seed, "mul7", 50000, 200000))}/mês por descumprimento; (c) estudo psicossocial da família; (d) tutela de urgência para visitas imediatas; (e) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer o reconhecimento da alienação parental e a aplicação das sanções legais.`, omittedContent: `[pedido de reconhecimento de alienação parental sem especificação das sanções e das medidas urgentes]`, omissionDescription: "pedido de alienação parental sem especificação das sanções (multa, inversão de guarda) e das medidas urgentes de convivência", correctPresenceKeywords: ["Lei 12.318", "multa", "tutela de urgência"] },
  ];
}

// ─── FAM-008: EXONERACAO_ALIMENTOS (MODERATE) ─────────────────────────────────
function buildExoneracaoAlimentos(seed: CaseSeedData): DocumentElement[] {
  const cj = conjuge(seed);
  const f1 = filho(seed, 1);
  const idadeFilho = dn(seed, "id8", 22, 5);
  const alimentosCents = dn(seed, "al8", 100000, 300000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, apresenta\n\nRECURSO DE APELAÇÃO\n\nem face de sentença que negou a exoneração de alimentos a ${f1}\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, f1] },
    { id: "decisao_recorrida_alimentos", section: DocumentSection.DOS_FATOS, fullContent: `A sentença recorrida negou a exoneração de alimentos pagos pelo recorrente ao(à) filho(a) ${f1} (${idadeFilho} anos), no valor de ${fmt(alimentosCents)}/mês, sob o argumento de que o alimentando ainda cursaria faculdade. O recorrente demonstra que ${f1} obteve aprovação em concurso público em ${seed.baseDate} e exerce emprego remunerado desde ${seed.derDate}, cessando a necessidade de alimentos (CC art. 1.694 §1.º).`, lightContent: `A sentença manteve os alimentos por entender que o filho ainda necessita do valor para custear seus estudos.`, omittedContent: `[sentença recorrida e fundamento para manter os alimentos não identificados]`, omissionDescription: "ausência de identificação da sentença recorrida e do fundamento para manter os alimentos ao filho maior de idade", correctPresenceKeywords: [f1, String(idadeFilho), fmt(alimentosCents)] },
    { id: "fatos_exoneracao", section: DocumentSection.DO_DIREITO, fullContent: `O CC art. 1.694 §1.º vincula os alimentos à necessidade do alimentando e à possibilidade do alimentante. ${f1}, com ${idadeFilho} anos, aprovado em concurso público (Edital n.º ${dn(seed, "ed8", 1, 99)}/${seed.baseDate.slice(-4)}) e empregado desde ${seed.derDate}, tem plena capacidade de auto-sustento. A Súmula 358 do STJ orienta que a maioridade não extingue automaticamente os alimentos, mas cessa a presunção de necessidade, que deve ser provada.`, lightContent: `O filho atingiu a maioridade e obteve emprego, cessando a necessidade de alimentos.`, omittedContent: `[fatos que demonstram a cessação da necessidade do alimentando (emprego, renda) não identificados]`, omissionDescription: "ausência de identificação dos fatos que demonstram a cessação da necessidade do alimentando (aprovação em concurso, emprego e renda auferida)", correctPresenceKeywords: [f1, "CC art. 1.694", "Súmula 358"] },
    { id: "prova_mudanca_capacidade", section: DocumentSection.DAS_PROVAS, fullContent: `Comprovam a auto-suficiência do alimentando: (a) certidão de aprovação no concurso (Edital n.º ${dn(seed, "ed8", 1, 99)}/${seed.baseDate.slice(-4)}); (b) contrato de trabalho com remuneração de ${fmt(dn(seed, "rem8", 300000, 800000))}/mês; (c) declaração de IR do alimentando com renda própria; (d) extrato bancário demonstrando depósitos regulares.`, lightContent: `A auto-suficiência do alimentando será comprovada por documentos de emprego e renda.`, omittedContent: `[prova da mudança de capacidade do alimentando (contrato de trabalho, renda) não juntada]`, omissionDescription: "ausência de juntada da prova da mudança de capacidade do alimentando (contrato de trabalho, renda auferida, declaração de IR)", correctPresenceKeywords: [fmt(dn(seed, "rem8", 300000, 800000)), "contrato de trabalho", "declaração de IR"] },
    { id: "pedido_recursal_exoneracao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer o provimento do apelo para: (a) exonerar o recorrente dos alimentos de ${fmt(alimentosCents)}/mês (CC art. 1.694 §1.º); (b) declarar cessada a obrigação alimentar desde ${seed.derDate}; (c) honorários recursais.`, lightContent: `Requer a exoneração dos alimentos pagos ao filho maior de idade com emprego.`, omittedContent: `[pedido de exoneração de alimentos sem valor do encargo e fundamento da cessação da necessidade]`, omissionDescription: "pedido de exoneração de alimentos sem identificação do valor do encargo, da data de cessação e do fundamento legal da exoneração", correctPresenceKeywords: [fmt(alimentosCents), seed.derDate, "CC art. 1.694"] },
  ];
}

// ─── FAM-009: INVESTIGACAO_PATERNIDADE (LIGHT) ────────────────────────────────
function buildInvestigacaoPaternidade(seed: CaseSeedData): DocumentElement[] {
  const putativoPai = conjuge(seed);
  const f1 = filho(seed, 1);
  const idadeFilho = dn(seed, "id9", 2, 15);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, na qualidade de representante legal do menor ${f1.toUpperCase()}, vem propor\n\nAÇÃO DE INVESTIGAÇÃO DE PATERNIDADE\n\nem face de ${putativoPai.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, f1] },
    { id: "fatos_relacao", section: DocumentSection.DOS_FATOS, fullContent: `O menor ${f1} nasceu em ${seed.baseDate}, sendo filho biológico de ${putativoPai}, com quem a autora manteve relacionamento afetivo de ${seed.derDate.slice(-4)} a ${seed.baseDate.slice(-4)}. O réu nega a paternidade e recusa-se a reconhecer voluntariamente o filho, impedindo o registro paterno e o acesso aos direitos decorrentes da filiação (CC arts. 1.596 e 1.597).`, lightContent: `O menor é filho biológico do réu, que nega a paternidade e recusa o reconhecimento voluntário.`, omittedContent: `[período do relacionamento, data de nascimento do menor e recusa do réu não identificados]`, omissionDescription: "ausência de identificação do período do relacionamento entre as partes, da data de nascimento do menor e da recusa do réu ao reconhecimento voluntário da paternidade", correctPresenceKeywords: [seed.baseDate, f1, "CC art. 1.596"] },
    { id: "exame_dna", section: DocumentSection.DAS_PROVAS, fullContent: `Requer a realização de exame de DNA pelo Instituto de Genética Forense (material coletado do menor e do investigado), com encaminhamento ao laboratório credenciado pelo INMETRO. O exame tem probabilidade de paternidade de ≥99,99% (art. 2.º, §3.º, Lei 8.560/1992; Resolução CNJ 300/2014). Junta-se declaração da genitora afirmando a exclusividade do relacionamento no período da concepção.`, lightContent: `O exame de DNA será requerido para confirmar a paternidade biológica do investigado.`, omittedContent: `[requerimento de exame de DNA com fundamento legal e metodologia não especificados]`, omissionDescription: "ausência de especificação do requerimento de exame de DNA com identificação do fundamento legal e da metodologia a ser utilizada para determinação da paternidade", correctPresenceKeywords: ["DNA", "Lei 8.560", "INMETRO"] },
    { id: "direito_paternidade", section: DocumentSection.DO_DIREITO, fullContent: `A CF/88 art. 227 §6.º e o CC art. 1.596 vedam qualquer distinção entre filhos. O direito à identidade genética é direito fundamental (STF, RE 898.060/SC — repercussão geral). A lei 8.560/1992 regula a investigação de paternidade. O reconhecimento gera registro paterno, direito a alimentos e herança.`, lightContent: `A investigação de paternidade é garantida pela CF/88 e pelo CC como direito fundamental do menor.`, omittedContent: `[fundamento constitucional e legal da investigação de paternidade não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento constitucional e legal da investigação de paternidade e dos direitos decorrentes do reconhecimento", correctPresenceKeywords: ["CF/88 art. 227", "CC art. 1.596", "RE 898.060"] },
    { id: "pedidos_paternidade", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) realização de exame de DNA (Lei 8.560/1992 art. 2.º §3.º); (b) declaração judicial de paternidade com registro em BNAFAR; (c) inclusão no registro civil; (d) fixação de alimentos provisionais; (e) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a realização do exame de DNA, o reconhecimento da paternidade e os alimentos provisionais.`, omittedContent: `[pedidos de investigação de paternidade sem especificação do exame de DNA e dos alimentos]`, omissionDescription: "pedido de investigação de paternidade sem especificação do exame de DNA, do reconhecimento a ser declarado e dos alimentos provisionais", correctPresenceKeywords: ["Lei 8.560", "alimentos", "registro civil"] },
  ];
}

// ─── FAM-010: ALTERACAO_GUARDA (MODERATE) ─────────────────────────────────────
function buildAlteracaoGuarda(seed: CaseSeedData): DocumentElement[] {
  const cj = conjuge(seed);
  const f1 = filho(seed, 1);
  const idadeFilho = dn(seed, "id10", 7, 8);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE ALTERAÇÃO DE GUARDA\n\nem face de ${cj.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, cj] },
    { id: "fatos_guarda_atual", section: DocumentSection.DOS_FATOS, fullContent: `A guarda de ${f1} (${idadeFilho} anos) foi deferida ao(à) réu(ré) ${cj} pela sentença proferida em ${seed.baseDate}. Desde então, surgiram fatos novos que comprometem o bem-estar da criança e justificam a alteração da guarda para o(a) autor(a), nos termos do CC art. 1.584 §5.º.`, lightContent: `A guarda de ${f1} foi deferida ao réu/ré e há fatos novos que justificam sua alteração.`, omittedContent: `[guarda atual e sentença que a estabeleceu não identificados]`, omissionDescription: "ausência de identificação da guarda atual, da sentença que a estabeleceu e dos fatos novos que justificam a alteração", correctPresenceKeywords: [f1, seed.baseDate, "CC art. 1.584"] },
    { id: "fatos_mudanca_circunstancias", section: DocumentSection.DOS_FATOS, fullContent: `Os fatos novos que comprometem o bem-estar de ${f1}: (a) o(a) guardião(ã) mudou de cidade para ${["São Paulo", "Rio de Janeiro", "Curitiba", "Manaus"][h(seed.cpf + "cid10") % 4]} sem prévia autorização judicial (CC art. 1.584 §5.º); (b) a criança relatou ao professor(a) que não frequenta a escola regularmente; (c) laudo psicológico de ${seed.derDate} aponta sinais de negligência; (d) o guardião(ã) contraiu novo relacionamento que expõe a criança a situação de risco.`, lightContent: `Surgiram fatos novos que comprometem o bem-estar do menor e justificam a alteração da guarda.`, omittedContent: `[fatos concretos que justificam a alteração da guarda e comprometem o bem-estar do menor não identificados]`, omissionDescription: "ausência de identificação dos fatos concretos que justificam a alteração da guarda e comprometem o bem-estar do menor", correctPresenceKeywords: [f1, seed.derDate, "CC art. 1.584"] },
    { id: "direito_alteracao", section: DocumentSection.DO_DIREITO, fullContent: `O CC art. 1.584 §5.º e o ECA art. 23 §1.º autorizam a alteração da guarda quando verificada a modificação das circunstâncias. O melhor interesse da criança (CF/88 art. 227; Convenção sobre Direitos da Criança, art. 3.º) é o princípio norteador. O STJ, no REsp 1.251.000/MG, consolidou que a mudança de cidade sem autorização judicial justifica a alteração da guarda.`, lightContent: `A alteração da guarda é cabível quando há modificação das circunstâncias e melhor interesse da criança.`, omittedContent: `[fundamento legal para a alteração da guarda e precedente do STJ não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal para a alteração da guarda e do critério do melhor interesse da criança com precedentes do STJ", correctPresenceKeywords: ["CC art. 1.584", "melhor interesse", "ECA art. 23"] },
    { id: "pedidos_alteracao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) tutela de urgência para alteração provisória da guarda de ${f1} para o(a) autor(a) (CPC art. 300); (b) no mérito, alteração definitiva da guarda (CC art. 1.584 §5.º); (c) estudo social; (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a alteração da guarda de forma provisória e definitiva, com estudo social.`, omittedContent: `[pedido de alteração de guarda sem identificação do menor e do fundamento para a tutela de urgência]`, omissionDescription: "pedido de alteração de guarda sem identificação do menor, do fundamento para a tutela de urgência e dos fatos que a justificam", correctPresenceKeywords: [f1, "CPC art. 300", "CC art. 1.584"] },
  ];
}

// ─── FAM-011: DISSOLUCAO_UNIAO_ESTAVEL (GOOD) ─────────────────────────────────
function buildDisssolucaoUniaoEstavel(seed: CaseSeedData): DocumentElement[] {
  const cj = conjuge(seed);
  const anosUniao = dn(seed, "au11", 4, 15);
  const imovelCents = dn(seed, "im11", 30000000, 120000000);
  const investimentosCents = dn(seed, "inv11", 5000000, 30000000);
  const totalCents = imovelCents + investimentosCents;
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE DISSOLUÇÃO DE UNIÃO ESTÁVEL\n\nem face de ${cj.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, cj] },
    { id: "fatos_uniao_estavel", section: DocumentSection.DOS_FATOS, fullContent: `A autora e ${cj} conviveram em união estável de ${seed.baseDate} a ${seed.derDate} (${anosUniao} anos), com o objetivo de constituir família (CC art. 1.723). A ruptura ocorreu em ${seed.derDate} por iniciativa mútua. O contrato de convivência (CC art. 1.725), lavrado em ${seed.baseDate.slice(-4)}, estabeleceu o regime de comunhão parcial de bens.`, lightContent: `A autora e o réu viveram em união estável por ${anosUniao} anos, com contrato de convivência estabelecendo o regime de bens.`, omittedContent: `[período da união estável, regime de bens e data de ruptura não identificados]`, omissionDescription: "ausência de identificação do período de convivência, do regime de bens e da data de ruptura da união estável", correctPresenceKeywords: [seed.baseDate, String(anosUniao), "CC art. 1.723"] },
    { id: "partilha_uniao", section: DocumentSection.DOS_FATOS, fullContent: `Bens comuns a partilhar: (a) imóvel — matrícula ${dn(seed, "mat11", 10000, 89999)} CRI ${seed.city}: ${fmt(imovelCents)}; (b) investimentos financeiros em aplicações conjuntas: ${fmt(investimentosCents)}. Total: ${fmt(totalCents)}. Parte de cada companheiro: ${fmt(Math.round(totalCents / 2))}. O imóvel será avaliado por perito judicial.`, lightContent: `Os bens comuns da união estável serão partilhados conforme o contrato de convivência.`, omittedContent: `[bens comuns a partilhar com valores e matrícula dos imóveis não identificados]`, omissionDescription: "ausência de identificação dos bens comuns da união estável com matrículas dos imóveis, saldos dos investimentos e total do patrimônio", correctPresenceKeywords: [fmt(imovelCents), fmt(totalCents), "matrícula"] },
    { id: "direito_dissolucao", section: DocumentSection.DO_DIREITO, fullContent: `A CF/88 art. 226 §3.º e o CC arts. 1.723-1.727 regulam a dissolução da união estável. O regime de comunhão parcial (CC art. 1.725) impõe a partilha igualitária dos bens adquiridos na constância. A dissolução extingue os efeitos da união (CC art. 1.727), mas preserva o direito à partilha e a alimentos eventualmente fixados.`, lightContent: `A dissolução da união estável é regulada pelo CC e implica a partilha dos bens adquiridos em comum.`, omittedContent: `[fundamento legal da dissolução, regime de bens e direitos decorrentes não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal da dissolução da união estável e do regime de bens aplicável com identificação dos bens comuns", correctPresenceKeywords: ["CF/88 art. 226", "CC art. 1.723", "CC art. 1.725"] },
    { id: "pedidos_dissolucao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) decretação da dissolução da união estável (CC art. 1.723); (b) partilha dos bens comuns (${fmt(totalCents)}) em igualdade de partes; (c) adjudicação do imóvel à autora mediante pagamento da diferença; (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a dissolução da união estável com partilha igualitária dos bens comuns.`, omittedContent: `[pedido de dissolução sem especificação do patrimônio a partilhar e do critério de adjudicação]`, omissionDescription: "pedido de dissolução da união estável sem especificação do patrimônio total a partilhar e do critério de adjudicação pleiteado", correctPresenceKeywords: [fmt(totalCents), "CC art. 1.723", "adjudicação"] },
  ];
}

// ─── FAM-012: INTERDICAO (LIGHT) ──────────────────────────────────────────────
function buildInterdicao(seed: CaseSeedData): DocumentElement[] {
  const interditando = ["João Carlos da Silva", "Maria Aparecida Santos", "Antonio Ferreira Lima", "Rosa Maria Pereira"][h(seed.cpf + "int12") % 4];
  const doenca = ["Alzheimer (CID G30)", "esquizofrenia grave (CID F20)", "deficiência intelectual grave (CID F73)", "demência senil (CID F03)"][h(seed.cpf + "d12") % 4];
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, vem promover\n\nAÇÃO DE INTERDIÇÃO\n\nem favor de ${interditando.toUpperCase()}, CPF n.º ${seed.cpf.split("").reverse().join("")}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, interditando] },
    { id: "fatos_incapacidade", section: DocumentSection.DOS_FATOS, fullContent: `${interditando}, nascido(a) em ${seed.baseDate}, portador(a) de ${doenca}, encontra-se absolutamente incapaz de exercer os atos da vida civil (CC art. 3.º I; CC art. 1.767 I). A incapacidade foi diagnosticada em ${seed.derDate} e progressivamente suprimiu a capacidade de autodeterminação do(a) interditando(a), que não consegue praticar atos cotidianos sem assistência.`, lightContent: `O(A) interditando(a) é portador(a) de doença grave que o(a) torna incapaz de gerir seus atos civis.`, omittedContent: `[doença, data do diagnóstico e grau de incapacidade do interditando não identificados]`, omissionDescription: "ausência de identificação da doença, da data do diagnóstico e do grau de incapacidade do interditando que justifica a interdição", correctPresenceKeywords: [interditando, doenca.split(" ")[0], seed.derDate] },
    { id: "laudo_medico_interdicao", section: DocumentSection.DAS_PROVAS, fullContent: `Laudo médico elaborado pelo Dr. ${["Pedro Alves", "Maria Costa", "João Lima", "Ana Santos"][h(seed.cpf + "dr12") % 4]} (CRM ${dn(seed, "crm12", 10000, 89999)}) em ${seed.derDate} atesta que ${interditando} é portador(a) de ${doenca}, estando absolutamente incapaz de praticar atos da vida civil por si só, necessitando de representação para todos os atos da vida civil (CC art. 3.º I).`, lightContent: `O laudo médico comprovando a incapacidade do interditando será juntado com a petição inicial.`, omittedContent: `[laudo médico comprobatório da incapacidade do interditando não juntado à petição inicial]`, omissionDescription: "ausência de juntada do laudo médico comprobatório da incapacidade do interditando, requisito essencial da ação de interdição (CC art. 1.771)", correctPresenceKeywords: [interditando, "laudo médico", "CRM"] },
    { id: "direito_interdicao", section: DocumentSection.DO_DIREITO, fullContent: `O CC arts. 3.º I e 1.767 I autorizam a interdição de pessoa absolutamente incapaz. O CPC arts. 747-758 regulam o procedimento da ação de interdição. O Estatuto da Pessoa com Deficiência (Lei 13.146/2015) exige que a curatela seja medida de último recurso e seja proporcional à necessidade do interditando. O (a) autor(a) é legitimado(a) pelo CC art. 1.768 I (cônjuge ou família próxima).`, lightContent: `A interdição é regulada pelo CC e pelo CPC, devendo ser proporcional à necessidade do interditando.`, omittedContent: `[fundamento legal da interdição, legitimidade do autor e caráter proporcional da curatela não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal da interdição, da legitimidade do autor e do caráter proporcional e subsidiário da curatela", correctPresenceKeywords: ["CC art. 3.º", "Lei 13.146", "CPC art. 747"] },
    { id: "pedidos_interdicao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) decretação da interdição de ${interditando} por incapacidade absoluta (CC art. 3.º I); (b) nomeação do(a) autor(a) como curador(a); (c) realização de perícia médica judicial (CPC art. 753); (d) publicação de editais (CPC art. 755); (e) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a decretação da interdição e a nomeação do autor como curador do interditando.`, omittedContent: `[pedido de interdição sem identificação do interditando e dos fundamentos da incapacidade]`, omissionDescription: "pedido de interdição sem identificação do interditando, do grau de incapacidade e do fundamento legal para a curatela", correctPresenceKeywords: [interditando, "CPC art. 753", "curador"] },
  ];
}

// ─── FAM-013: REVISAO_ALIMENTOS (GOOD) ────────────────────────────────────────
function buildRevisaoAlimentos(seed: CaseSeedData): DocumentElement[] {
  const cj = conjuge(seed);
  const f1 = filho(seed, 1);
  const idadeFilho = dn(seed, "id13", 8, 10);
  const alimentosAntigosCents = dn(seed, "aa13", 80000, 120000);
  const alimentosNovosCents = alimentosAntigosCents + dn(seed, "ad13", 50000, 150000);
  const rendaAtualCents = dn(seed, "ra13", 500000, 2000000);
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, na qualidade de representante de ${f1.toUpperCase()}, vem propor\n\nAÇÃO DE REVISÃO DE ALIMENTOS\n\nem face de ${cj.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, cj] },
    { id: "fatos_alimentandos_atual", section: DocumentSection.DOS_FATOS, fullContent: `Os alimentos de ${fmt(alimentosAntigosCents)}/mês foram fixados em ${seed.baseDate} (processo n.º ${seed.processNumber.split("-")[0]}-ant). Desde então, as necessidades de ${f1} (${idadeFilho} anos) cresceram substancialmente: ingresso no Ensino Médio com escola particular, atividades extracurriculares e despesas médicas regulares.`, lightContent: `Os alimentos foram fixados anteriormente e as necessidades do menor cresceram desde então.`, omittedContent: `[valor dos alimentos anteriores, data de fixação e crescimento das necessidades do menor não identificados]`, omissionDescription: "ausência de identificação do valor dos alimentos anteriores, da data de fixação e do crescimento concreto das necessidades do menor alimentando", correctPresenceKeywords: [fmt(alimentosAntigosCents), seed.baseDate, f1] },
    { id: "fatos_mudanca_financeira", section: DocumentSection.DOS_FATOS, fullContent: `Houve mudança significativa na situação financeira do alimentante ${cj}: (a) promoção no emprego em ${seed.derDate} com aumento salarial para ${fmt(rendaAtualCents)}/mês; (b) aquisição de imóvel próprio em ${seed.derDate.slice(-4)}; (c) redução das despesas com a criança (filho mora com a autora). O novo bionômio necessidade-possibilidade justifica a revisão para ${fmt(alimentosNovosCents)}/mês (CC art. 1.699).`, lightContent: `O alimentante passou por melhora financeira significativa, justificando a revisão dos alimentos.`, omittedContent: `[mudança concreta na situação financeira do alimentante com valores e data não identificados]`, omissionDescription: "ausência de identificação das mudanças concretas na situação financeira do alimentante com valores e data da melhora", correctPresenceKeywords: [fmt(rendaAtualCents), seed.derDate, "CC art. 1.699"] },
    { id: "calculo_revisao", section: DocumentSection.DOS_FATOS, fullContent: `Demonstrativo da revisão: Renda atual do alimentante: ${fmt(rendaAtualCents)}/mês. Encargo pretendido: ${fmt(alimentosNovosCents)}/mês = ${Math.round(alimentosNovosCents / rendaAtualCents * 100)}% da renda. Necessidades mensais de ${f1}: escola ${fmt(dn(seed, "esc13", 80000, 120000))} + saúde ${fmt(dn(seed, "sau13", 20000, 40000))} + outras ${fmt(dn(seed, "out13", 30000, 50000))} ≈ ${fmt(alimentosNovosCents)}/mês. Aumento proposto: de ${fmt(alimentosAntigosCents)} para ${fmt(alimentosNovosCents)}.`, lightContent: `A revisão propõe aumento de alimentos compatível com a nova situação das partes.`, omittedContent: `[cálculo da revisão com renda do alimentante, necessidades do menor e novo valor proposto não apresentado]`, omissionDescription: "ausência de cálculo da revisão com renda atual do alimentante, necessidades do menor e demonstração do novo valor proposto", correctPresenceKeywords: [fmt(alimentosNovosCents), fmt(rendaAtualCents), String(Math.round(alimentosNovosCents / rendaAtualCents * 100))] },
    { id: "pedidos_revisao", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) revisão dos alimentos de ${fmt(alimentosAntigosCents)} para ${fmt(alimentosNovosCents)}/mês (CC art. 1.699); (b) fixação de alimentos provisórios no novo valor (CPC art. 303); (c) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer a revisão dos alimentos para o novo valor proporcional à mudança das circunstâncias.`, omittedContent: `[pedido de revisão sem identificação do valor atual, do novo valor proposto e do fundamento legal]`, omissionDescription: "pedido de revisão de alimentos sem especificação do valor atual, do novo valor proposto e do fundamento legal (CC art. 1.699)", correctPresenceKeywords: [fmt(alimentosAntigosCents), fmt(alimentosNovosCents), "CC art. 1.699"] },
  ];
}

// ─── FAM-014: TUTELA_CRIANCA (MODERATE) ───────────────────────────────────────
function buildTutelaCrianca(seed: CaseSeedData): DocumentElement[] {
  const crianca = filho(seed, 1);
  const idadeCrianca = dn(seed, "ic14", 2, 12);
  const tutor = seed.personName;
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${tutor.toUpperCase()}, CPF n.º ${seed.cpf}, vem propor\n\nAÇÃO DE TUTELA DE CRIANÇA\n\nem favor do menor ${crianca.toUpperCase()}\n\nProcesso n.º ${seed.processNumber} — Valor da causa: ${seed.causeValue}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [tutor, crianca] },
    { id: "fatos_crianca", section: DocumentSection.DOS_FATOS, fullContent: `${crianca}, ${idadeCrianca} anos, encontra-se em situação de abandono desde ${seed.baseDate}, após o falecimento do pai e o abandono da genitora, que saiu do lar em ${seed.derDate} sem deixar contato. O(A) autor(a) ${tutor}, tio(a)/avô(ó) da criança, vem assistindo-lhe desde então, sendo a pessoa de referência afetiva do menor.`, lightContent: `O menor está em situação de abandono e necessita de tutor para representação legal.`, omittedContent: `[situação de abandono da criança, data e circunstâncias que geraram a necessidade de tutela não identificados]`, omissionDescription: "ausência de identificação da situação de abandono da criança, da data em que ocorreu e das circunstâncias que geraram a necessidade de tutela", correctPresenceKeywords: [crianca, seed.baseDate, String(idadeCrianca)] },
    { id: "situacao_risco", section: DocumentSection.DOS_FATOS, fullContent: `A situação de risco de ${crianca} é documentada pelo Conselho Tutelar de ${seed.city} (Registro n.º ${dn(seed, "ct14", 1000, 9999)}/CT/${seed.baseDate.slice(-4)}): (a) criança encontrada sozinha em ${dn(seed, "ep14", 3, 8)} ocasiões; (b) desnutrição leve (laudo do UBS de ${seed.derDate}); (c) ausência às aulas em ${dn(seed, "fa14", 30, 60)}% dos dias letivos. O CRAS atende a família desde ${seed.baseDate}.`, lightContent: `A situação de risco do menor está documentada pelo Conselho Tutelar.`, omittedContent: `[documentação da situação de risco da criança pelo Conselho Tutelar e registros de atendimento não apresentados]`, omissionDescription: "ausência de apresentação dos registros do Conselho Tutelar que documentam a situação de risco da criança, fundamentais para o pedido de tutela", correctPresenceKeywords: [crianca, "Conselho Tutelar", seed.baseDate] },
    { id: "direito_tutela", section: DocumentSection.DO_DIREITO, fullContent: `O CC arts. 1.728-1.766 regem a tutela. O ECA art. 19 garante à criança o direito à convivência familiar segura. O(A) autor(a) é legitimado(a) pelo CC art. 1.731 I (parente) e preenche os requisitos: idoneidade moral, capacidade para exercer a tutela e ausência de impedimentos (CC art. 1.735). O melhor interesse da criança (CF/88 art. 227) impõe a deferência da tutela ao(à) requerente.`, lightContent: `A tutela é regulada pelo CC e garante à criança representação legal e proteção de seus interesses.`, omittedContent: `[fundamento legal da tutela e legitimidade do autor para exercê-la não desenvolvidos]`, omissionDescription: "ausência de desenvolvimento do fundamento legal da tutela e da demonstração da legitimidade e idoneidade do autor para exercê-la", correctPresenceKeywords: ["CC art. 1.728", "ECA art. 19", "CF/88 art. 227"] },
    { id: "pedidos_tutela", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) deferimento da tutela provisória de ${crianca} ao(à) autor(a) (CC art. 1.728; CPC art. 759); (b) prestação de contas anual do tutor; (c) nomeação de curador especial para o menor; (d) honorários. Valor da causa: ${seed.causeValue}.`, lightContent: `Requer o deferimento da tutela do menor ao autor(a) com prestação de contas anual.`, omittedContent: `[pedido de tutela sem identificação do menor e dos requisitos legais do tutor]`, omissionDescription: "pedido de tutela da criança sem identificação do menor, dos requisitos do tutor e da necessidade de curador especial", correctPresenceKeywords: [crianca, "CC art. 1.728", "curador"] },
  ];
}

// ─── FAM-015: CUMPRIMENTO_ALIMENTOS (GOOD) ────────────────────────────────────
function buildCumprimentoAlimentos(seed: CaseSeedData): DocumentElement[] {
  const cj = conjuge(seed);
  const f1 = filho(seed, 1);
  const mesesAtraso = dn(seed, "ma15", 3, 9);
  const alimentosCents = dn(seed, "al15", 100000, 400000);
  const totalDevidoCents = alimentosCents * mesesAtraso;
  return [
    { id: "cabecalho", section: DocumentSection.CABECALHO, fullContent: `MM. JUÍZO DA ${seed.courtName.toUpperCase()} — ${seed.city.toUpperCase()}\n\n${seed.personName.toUpperCase()}, CPF n.º ${seed.cpf}, na qualidade de representante de ${f1.toUpperCase()}, apresenta\n\nCUMPRIMENTO DE SENTENÇA — EXECUÇÃO DE ALIMENTOS\n\nem face de ${cj.toUpperCase()}\n\nProcesso n.º ${seed.processNumber}`, lightContent: "", omittedContent: "", omissionDescription: "", correctPresenceKeywords: [seed.personName, f1] },
    { id: "titulo_alimentos", section: DocumentSection.DOS_FATOS, fullContent: `A sentença transitada em julgado em ${seed.baseDate} condenou ${cj} ao pagamento de alimentos de ${fmt(alimentosCents)}/mês em favor de ${f1}. O executado está inadimplente há ${mesesAtraso} meses (${seed.derDate.slice(3)} a ${seed.baseDate.slice(3)}), totalizando ${fmt(totalDevidoCents)} de parcelas vencidas e não pagas.`, lightContent: `A sentença condenou o executado ao pagamento de alimentos mensais ao filho, estando inadimplente.`, omittedContent: `[título executivo, valor dos alimentos e período de inadimplência não identificados]`, omissionDescription: "ausência de identificação do título executivo, do valor dos alimentos, do período de inadimplência e do total devido", correctPresenceKeywords: [seed.baseDate, fmt(alimentosCents), String(mesesAtraso)] },
    { id: "parametros_alimentos", section: DocumentSection.DO_DIREITO, fullContent: `A execução de alimentos segue o rito do CPC art. 528 (prisão civil) ou art. 529 (desconto em folha). O crédito alimentar goza de privilégio especial (CC art. 965 II). Alimentos vencidos há menos de 3 meses permitem prisão civil (Súm. 309 STJ). O valor atualizado de ${fmt(totalDevidoCents)} acresce juros de 1%/mês (CC art. 406) desde cada vencimento.`, lightContent: `A execução de alimentos pode se dar por prisão civil ou desconto em folha, conforme o CPC.`, omittedContent: `[rito da execução de alimentos, privilégio do crédito e atualização por juros não identificados]`, omissionDescription: "ausência de identificação do rito da execução de alimentos, do privilégio do crédito alimentar e da atualização por juros de mora", correctPresenceKeywords: ["CPC art. 528", "Súm. 309", "CC art. 406"] },
    { id: "memoria_calculo_alimentos", section: DocumentSection.DAS_PROVAS, fullContent: `Memória de cálculo: ${mesesAtraso} parcelas × ${fmt(alimentosCents)} = ${fmt(totalDevidoCents)} (principal). Atualizado: ${fmt(Math.round(totalDevidoCents * 1.05))} (juros de 1%/mês × ${mesesAtraso} meses aprox.). Parcelas: ${Array.from({ length: mesesAtraso }, (_, i) => `${String(parseInt(seed.derDate.slice(3, 5)) + i).padStart(2, "0")}/${seed.derDate.slice(-4)}`).join(", ")}.`, lightContent: `As parcelas de alimentos em atraso serão calculadas e atualizadas monetariamente.`, omittedContent: `[memória de cálculo das parcelas em atraso com valores individuais e atualização não apresentada]`, omissionDescription: "ausência de memória de cálculo detalhada das parcelas de alimentos em atraso com valores individuais e atualização", correctPresenceKeywords: [fmt(totalDevidoCents), String(mesesAtraso), fmt(alimentosCents)] },
    { id: "pedidos_alimentos_exec", section: DocumentSection.DOS_PEDIDOS, fullContent: `Requer: (a) intimação de ${cj} para pagar ${fmt(Math.round(totalDevidoCents * 1.05))} em 3 dias sob pena de prisão civil (CPC art. 528 §3.º); (b) alternativamente, desconto em folha (CPC art. 529); (c) inclusão no Cadastro de Devedores de Alimentos (Lei 14.331/2022); (d) honorários.`, lightContent: `Requer o pagamento dos alimentos atrasados sob pena de prisão civil.`, omittedContent: `[pedido executivo sem valor total atualizado, prazo e fundamento da prisão civil]`, omissionDescription: "pedido executivo de alimentos sem indicação do valor total atualizado, do prazo legal e do fundamento legal para a prisão civil", correctPresenceKeywords: [fmt(Math.round(totalDevidoCents * 1.05)), "CPC art. 528", "prisão civil"] },
  ];
}

// ─── Dispatch ──────────────────────────────────────────────────────────────────

export function buildFamiliaElements(
  config: FamiliaScenarioConfig,
  seed: CaseSeedData,
): DocumentElement[] {
  switch (config.issueType) {
    case "DIVORCIO_LITIGIOSO":           return buildDivorcioLitigioso(seed);
    case "ALIMENTOS_FILHOS":             return buildAlimentosFilhos(seed);
    case "GUARDA_COMPARTILHADA":         return buildGuardaCompartilhada(seed);
    case "REGULAMENTACAO_VISITAS":       return buildRegulamentacaoVisitas(seed);
    case "RECONHECIMENTO_UNIAO_ESTAVEL": return buildReconhecimentoUniaoEstavel(seed);
    case "PARTILHA_BENS":               return buildPartilhaBens(seed);
    case "ALIENACAO_PARENTAL":           return buildAlienacaoParental(seed);
    case "EXONERACAO_ALIMENTOS":         return buildExoneracaoAlimentos(seed);
    case "INVESTIGACAO_PATERNIDADE":     return buildInvestigacaoPaternidade(seed);
    case "ALTERACAO_GUARDA":             return buildAlteracaoGuarda(seed);
    case "DISSOLUCAO_UNIAO_ESTAVEL":     return buildDisssolucaoUniaoEstavel(seed);
    case "INTERDICAO":                   return buildInterdicao(seed);
    case "REVISAO_ALIMENTOS":            return buildRevisaoAlimentos(seed);
    case "TUTELA_CRIANCA":               return buildTutelaCrianca(seed);
    case "CUMPRIMENTO_ALIMENTOS":        return buildCumprimentoAlimentos(seed);
    default:
      throw new Error(`Builder não encontrado para issueType: ${(config as { issueType: string }).issueType}`);
  }
}
